### ISSUE TITLE
ApigeeX API list_organization_sharedflow_deployments does not return service account name 

### ISSUE THREAD

**Issue by kapil-lloyds** [googleapis/google-api-ruby-client#11053]
list_organization_sharedflow_deployments API for ApigeeX under service.rb does not provide service account field in it's response output. However, the same API via REST provides service account name in the output response.

Ruby API:
![image](https://user-images.githubusercontent.com/101562351/179485798-3f323239-c29a-4fa2-b482-bdb7d42c1749.png)

REST API:
![image](https://user-images.githubusercontent.com/101562351/179485578-d5e20748-d96c-4f56-8bf9-900264be8cef.png)

We need a Ruby API in ApigeeX which would fetch us service account being used by it . The way we have it in REST API response.

**Comment by bajajneha27** [comment]
Hi @kapil-lloyds 
Thanks for reaching out to us.
I don't see service account in the response of this API https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.sharedflows.deployments/list . Am I missing something here?

**Comment by dazuma** [comment]
Closing from lack of response from the original poster. Please feel free to reopen if you are still having an issue and have additional information.

One thing to note: The google-api-client monolithic gem where you're looking at this code, is deprecated and is no longer being updated (hence, the client may be out of date compared with the service). Instead, please use the standalone apigee v1 client called google-apis-apigee_v1 (see https://github.com/googleapis/google-api-ruby-client/tree/main/generated/google-apis-apigee_v1)
