### ISSUE TITLE
Ruby API client to fetch KVM from ApigeeX

### ISSUE THREAD

**Issue by kapil-lloyds** [googleapis/google-api-ruby-client#11054]
Currently, we have API's to create or delete any KVM's from ApigeeX but there aren't any API's available to fetch KVM's from ApigeeX. 
From security point of view, it would be good to have a security control which validates the incoming IP ranges to ApigeeX which are usually stored inside KVM's. Hence, a ruby client API which can fetch the KVM's name/value will allow us to create a security control around ApigeeX.

**Comment by bajajneha27** [comment]
Hi @kapil-lloyds 
Can you please point us the APIs you're referring to?

**Comment by dazuma** [comment]
Closing from lack of response from the original poster. Please feel free to reopen if you are still having an issue and have additional information.

Note: there are calls for `get_organization_keyvaluemap_entry` and `list_organization_keyvaluemap_entries`, and similar for `organization_environment`, and `organization_api`. If these are not sufficient for your needs, please contact Apigee support (find links at https://cloud.google.com/apigee/docs/support). The Ruby client is autogenerated based on the Apigee API definition. We cannot add functionality to the API directly; it must be done by the Apigee team itself.
