### ISSUE TITLE
androidpublisher_v3 - no support for mandatory new google subscription purchase api 

### ISSUE THREAD

**Issue by pmcam** [googleapis/google-api-ruby-client#11570]
The new google play billing library requires a mandatory upgrade from **Method: purchases.subscriptions.get** to **Method: purchases.subscriptionsv2.get** however this method is not available in this repository. Currently the only way to request the google subscription purchase object is with the deprecated method located here https://github.com/googleapis/google-api-ruby-client/blob/a722b87c106ecb88e9d9621c6247ff780be96f32/google-api-client/generated/google/apis/androidpublisher_v3/service.rb#L1963

Can we please get support for the current version added here as we are not able to modify our google subscription products until we complete this upgrade https://developer.android.com/google/play/billing/compatibility.

**Comment by hassan-ahmed** [comment]
It seems the v2 method was merged in this  [PR](https://github.com/googleapis/google-api-ruby-client/pull/9380) however it's not available in main & latest release 🤔

**Comment by bajajneha27** [comment]
@pmcam May be you can use [get_purchase_subscriptionsv2](https://github.com/yoshi-code-bot/google-api-ruby-client/blob/main/generated/google-apis-androidpublisher_v3/lib/google/apis/androidpublisher_v3/service.rb#L3168)

**Comment by shivgautam** [comment]
This is available now
