### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 1) /app/vendor/bundle/ruby/3.0.0/gems/google-apis-drive_v3-0.28.0/lib/google/apis/drive_v3/service.rb:1145:in `get_file'

### ISSUE THREAD

**Issue by Sophia-Sergio** [googleapis/google-api-ruby-client#12126]
#### Environment details

  - OS: Mac - Linux
  - Ruby version: 3.0.2
  - Gem name and version: google-apis-drive_v3 0.28.0

#### Steps to reproduce

  1. Try to use method called get_file. Is not accepting new way of dealing with key parameters. 

#### Code example

```ruby
ArgumentError: wrong number of arguments (given 2, expected 1)
/app/vendor/bundle/ruby/3.0.0/gems/google-apis-drive_v3-0.27.0/lib/google/apis/drive_v3/service.rb:1145:in `get_file'
/app/vendor/bundle/ruby/3.0.0/gems/google_drive-3.0.7/lib/google_drive/file.rb:97:in `download_to_file'
```

Thanks!

**Comment by shivgautam** [comment]
Hi @Sophia-Sergio, this a bug in the 3rd party gem google-drive-ruby (https://github.com/gimite/google-drive-ruby). Unfortunately there isn't much we can do here as we don't own that code. 
That gem is not compatible with ruby 3 completely. Please raise a bug against that repo. 

I'm closing this bug.

**Comment by shivgautam** [comment]
These lines have the bug: https://github.com/gimite/google-drive-ruby/blob/master/lib/google_drive/file.rb#L96-L100
