### ISSUE TITLE
google-api-client gem shows deprecated

### ISSUE THREAD

**Issue by FernandoZX** [googleapis/google-api-ruby-client#12965]
Hi after bundling the  gem `google-api-client` display that message
```
The google-api-client gem is deprecated and will likely not be updated further.

Instead, please install the gem corresponding to the specific service to use.
For example, to use the Google Drive V3 client, install google-apis-drive_v3.
For more information, see the FAQ in the OVERVIEW.md file or the YARD docs.
```
and i want to install the calendar client where can i find the calendar client in the repo?

**Comment by dazuma** [comment]
The calendar client is https://rubygems.org/gems/google-apis-calendar_v3.
Its code is located here: https://github.com/googleapis/google-api-ruby-client/tree/main/generated/google-apis-calendar_v3.
