### ISSUE TITLE
raise file system errors like permission denied

### ISSUE THREAD

**Issue by tachiba** [googleapis/google-api-ruby-client#134]
https://github.com/google/google-api-ruby-client/blob/a49e63847551b2a97603b0ba19fe7ce60f062f59/lib/google/api_client/auth/key_utils.rb#L79-90

The above codes does not raises File system errors like 'permission denied'.
It is not kind for users.

I rewrite the codes as follows and now raises required errors to investigate problems.
https://github.com/tachiba/google-api-ruby-client/commit/f2344cc163b0909327e9b3cc541c40300716dbed

I read the guidelines for contributing, so I wait for your review.
Thanks!

**Comment by dazuma** [comment]
The code in question here has been deprecated and the logic moved to the googleauth gem. Closing.
