### ISSUE TITLE
Support for using FeedLabel on Products

### ISSUE THREAD

**Issue by SabracNL** [googleapis/google-api-ruby-client#14242]
A while back, the Google Content (v2.1) API put the targetCountry parameter as deprecated and has introduced the feedLabel parameter as an alternative.
https://ads-developers.googleblog.com/2022/08/feed-label-replaces-target-country-in.html

Sadly, using this gem does not work with the feedLabel option, the Products class does not contain this attribute.

My request involves adding this parameter to the Products class and add support for sending this functionality to the Google Content 2.1 API

**Comment by bajajneha27** [comment]
Thanks @SabracNL for bringing this to our notice. You can now use the [Google Content (v2.1) Gem](https://rubygems.org/gems/google-apis-content_v2_1) to use `feed_label` option.
