### ISSUE TITLE
No longer 'other' type

### ISSUE THREAD

**Issue by Set27** [googleapis/google-api-ruby-client#14444]
![img-2023-04-04-21-12-54](https://user-images.githubusercontent.com/49077110/229881244-209f6dc8-f090-4098-8538-878fe65ee1a2.png)

How I can use  **OAuth client ID**?

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by dazuma** [comment]
This doesn't seem to be related to the legacy Ruby api client libraries. Can you provide any more information about where this screenshot comes from, so that we can help you route your question to the right place?

**Comment by Set27** [comment]
> This doesn't seem to be related to the legacy Ruby api client libraries. Can you provide any more information about where this screenshot comes from, so that we can help you route your question to the right place?

Here is sample that I find in readme of this repos
![img-2023-04-06-20-53-22](https://user-images.githubusercontent.com/49077110/230457592-eaa83867-53f8-4b28-a1b8-c4cd124e531f.png)
Here is google API (https://console.developers.google.com/)
![img-2023-04-06-20-53-49](https://user-images.githubusercontent.com/49077110/230457640-daf6049a-4277-452c-ad3f-c109d044f8dd.png)

**Comment by Set27** [comment]
They move it to 'Desktop'
