### ISSUE TITLE
Support for attributes on ApplicationPolicy (androidmanagement_v1)

### ISSUE THREAD

**Issue by bwchang** [googleapis/google-api-ruby-client#15092]
The ApplicationPolicy class in the androidmanagement_v1 gem does not currently support the following attributes:
- alwaysOnVpnLockdownExemption
- workProfileWidgets

I would like these attributes to be added to the class, as they are included in Google's documentation and API.

**Comment by bajajneha27** [comment]
Hi @bwchang 
I see that the mentioned attributes are there in the class [ApplicationPolicy](https://github.com/googleapis/google-api-ruby-client/blob/main/generated/google-apis-androidmanagement_v1/lib/google/apis/androidmanagement_v1/classes.rb#L526)
Were you talking about the same thing?
