### ISSUE TITLE
Is there a way of use addressvalidation using this gem?

### ISSUE THREAD

**Issue by fedefa** [googleapis/google-api-ruby-client#15406]
Is it possible to use it? https://developers.google.com/maps/documentation/address-validation/reference/rest
There a discovery service available for it [here](https://addressvalidation.googleapis.com) but there is not a generated service mapped.

**Comment by bajajneha27** [comment]
Hi @fedefa,
The `address-validation` service team will take a call on auto-generating the library. So, you can file a bug to the team and ask for the same. Or you can use the [API generator](https://github.com/googleapis/google-api-ruby-client/tree/main/google-apis-generator) to build your own client.
