### ISSUE TITLE
Play Custom App API is broken and return 404 since version 0.44.2

### ISSUE THREAD

**Issue by jeremybdk** [googleapis/google-api-ruby-client#1598]
#### Environment details

  - OS: Linux, macOS
  - Ruby version: 2.6.6
  - Gem name and version: google-api-ruby-client 0.44.2

#### Steps to reproduce

  1. Try to use the Play Custom APP API will return a 404 starting with version 0.44.2

- Version 0.44.1 generate this call :  https://www.googleapis.com/upload/playcustomapp/v1/accounts/xxxxxx/customApps
- Version 0.44.2+ generate this call : https://playcustomapp.googleapis.com/upload/playcustomapp/v1/accounts/xxxxxx/customApps which return a 404

The same code that was working in version 0.44.1 and below, returns 404 on version 0.44.2+

This change is not backward compatible, is breaking existing implementation and is not documented.

Please let me know if you need more details, 

Thanks!

**Comment by jeremybdk** [comment]
Hello,
I'm wondering if there's any update regarding this issue, it's blocking for us, as we need to update the gems for other endpoints but it will break this one.
Thanks

**Comment by dazuma** [comment]
I am not sure what is going on. The current discovery document for this service (https://playcustomapp.googleapis.com/$discovery/rest?version=v1) specifies the endpoint playcustomapp.googleapis.com, which is why recent versions of the client are using that endpoint. I've opened an internal issue (ID b/176140484) to the product team to inquire whether this is correct.

**Comment by jeremybdk** [comment]
That's weird, cause it's a breaking change and it not's working with the same setup as it was before.
Thanks for looking into it

**Comment by jeremybdk** [comment]
Hello, I wanted to know if you had any updates on this issue?

Thanks a lot,

**Comment by jeremybdk** [comment]
@dazuma is there anything I can do to help?

**Comment by dazuma** [comment]
I checked back with the team; the issue should have been resolved as of Feb 1. Are you still getting 404s?

**Comment by dazuma** [comment]
Closing, as this should be resolved. Feel free to reopen if it is still happening for you.

**Comment by jeremybdk** [comment]
Yes it's fixed thanks for letting me know.
