### ISSUE TITLE
encoding of response body

### ISSUE THREAD

**Issue by otn** [googleapis/google-api-ruby-client#160]
in api_client/gzip.rb:

```
def on_complete(env)
  ..........
  env[:body] = Zlib::GzipReader.new(StringIO.new(env[:body])).read
```

The encoding of result of `Zlib::GzipReader` depends on `Encoding.default_external`.
In Google API, `env[:body].encoding` must be `Encoding::UTF_8` in any environment.
Could someone add `force_encoding(Encoding::UTF_8)` ?

**Comment by epraveenns** [comment]
Hi,
I am trying POST /calendar/v3/calendars. In this I need to give some data in "request body". 

The data to be given is 

**

> 
> {
>  "end": {
>   "date": "2016-03-21"
>  },
>  "start": {
>   "date": "2016-03-21"
>  }
> }

**

However the API is throwing Parse Error when I encode the above data in UTF-8 format. Will the API decode the data if I give encoded input in body? Should I give any additional parameters for it to enable ?

(I am trying this in OAuth 2.0 Playground)
