### ISSUE TITLE
NoMethodError: undefined method `discovered_api' for nil:NilClass

### ISSUE THREAD

**Issue by yamini0312** [googleapis/google-api-ruby-client#16026]
#### Environment details

  - Ruby version: 2.4.10
  - Rails version: 5.0.1
  - google-api-client: 0.9.3

It is working proper in google-api-cleint 0.8.2 but getting two error in 0.9.3
1. NameError: uninitialized constant Faraday::Error::ClientError
2. NoMethodError: undefined method `discovered_api' for nil:NilClass

```
def call(method_string, body_object = nil, additional_parameters = {})
    Retryable.retryable(
      tries: 4, sleep: lambda { |n| 2**n }, on: [
        Faraday::Error::ClientError,
        GoogleRequestError
      ]
    ) do
      result(*parse(response(method_string, body_object, additional_parameters)))
    end
  end
```

`client.discovered_api(api_name, api_version).to_h`
Or
`google_client.discovered_api('drive', 'v2')`

Thank you in advance!

**Comment by bajajneha27** [comment]
Hi @yamini0312 ,
The `google-api-client` is [deprecated](https://github.com/googleapis/google-api-ruby-client/blob/main/obsolete-google-api-client/google-api-client.gemspec) and is no longer available for use. Based on your use case, you can install a specific library and call the corresponding API. Please refer to our documentation for further instructions on how to install and use the libraries.
