### ISSUE TITLE
Batch API calls don't automatically refresh token

### ISSUE THREAD

**Issue by ctweney** [googleapis/google-api-ruby-client#167]
When a Google::APIClient is instantiated with auto_refresh_token => true, single API calls will work even when the token has expired, through the clever auto-refresh mechanism. 

This behavior does not work when making batched calls through Google::APIClient::BatchRequest. If your access token is more than an hour old, all the batched calls return HTTP 401 Unauthorized. 

If you explicitly call client.authorization.fetch_access_token! before making the batch, the batch calls will succeed with the new token. 

Gist that demonstrates the issue: https://gist.github.com/ctweney/584ea5f6fd869faf5469#file-calendar-rb-L104

The code in that gist is based on https://github.com/google/google-api-ruby-client-samples/blob/master/calendar/calendar.rb

**Comment by antifun** [comment]
:+1: to noting this VERY noisily in the documentation, as I just burned 2 hours figuring this out myself (didn't look here except to confirm my suspicions). Having an add-documentation issue to that effect sitting here open rather than a fix-it request closed would at least help with visibility.
