### ISSUE TITLE
No examples of how to use the cloudrun client library (cloudrun fully managed)

### ISSUE THREAD

**Issue by davidmitchell2019** [googleapis/google-api-ruby-client#1755]
please see below

**Comment by davidmitchell2019** [comment]
Please provide an example of how to use the cloudrun fully managed ruby

**Comment by davidmitchell2019** [comment]
require 'google/apis/run_v1'
require "googleauth"

scopes =  [
  'https://www.googleapis.com/auth/cloud-platform'
]

authorization = Google::Auth.get_application_default(scopes)
Run = Google::Apis::RunV1 # Alias the module
service = Run::CloudRunService.new
service.authorization = authorization
service.delete_project_location_revision("namespaces/camargue-0001/revisions/test-00002-suv")

**Comment by davidmitchell2019** [comment]
8: from /Users/ddmc/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/google-api-client-0.44.0/lib/google/apis/core/http_command.rb:110:in `block in execute'
         7: from /Users/ddmc/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `retriable'
         6: from /Users/ddmc/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:56:in `times'
         5: from /Users/ddmc/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/retriable-3.1.2/lib/retriable.rb:61:in `block in retriable'
         4: from /Users/ddmc/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/google-api-client-0.44.0/lib/google/apis/core/http_command.rb:113:in `block (2 levels) in execute'
         3: from /Users/ddmc/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/google-api-client-0.44.0/lib/google/apis/core/http_command.rb:309:in `execute_once'
         2: from /Users/ddmc/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/google-api-client-0.44.0/lib/google/apis/core/http_command.rb:193:in `process_response'
         1: from /Users/ddmc/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/google-api-client-0.44.0/lib/google/apis/core/api_command.rb:118:in `check_status'
/Users/ddmc/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/google-api-client-0.44.0/lib/google/apis/core/http_command.rb:227:in `check_status': Invalid request (Google::Apis::ClientError)

**Comment by dazuma** [comment]
For `delete_project_location_revision`, it looks like the format is supposed to be `projects/{projectId}/locations/{locationId}/revisions/{revisionId}`. Please use that format instead. The name format you used is meant for the `delete_namespace_revision` call.

You are right that the call to `projects.locations.revisions delete` is not even documented. I do not know why that is, and it's not something that the generated API client can fix. (We're an open source project and have no control over the product documentation.) To report this to the product documentation team, go to https://cloud.google.com/run/docs/reference/rest and click the "send feedback" button toward the upper right.
