### ISSUE TITLE
Add `Errno::ECONNRESET` to retriable network errors

### ISSUE THREAD

**Issue by mzuzek** [googleapis/google-api-ruby-client#18902]
Would it make sense to also include `Errno::ECONNRESET` (broken network connections) in [`RETRIABLE_ERRORS`](https://github.com/googleapis/google-api-ruby-client/blob/google-apis-core/v0.14.1/google-apis-core/lib/google/apis/core/http_command.rb#L30-L33) ?
(via `Google::Apis::TransmissionError` - same like `ECONNREFUSED` and `ETIMEDOUT` in https://github.com/googleapis/google-api-ruby-client/pull/10026)

I've hit that recently in context of GCS file downloads on Windows Server 2019 Datacenter 10.0.17763, Ruby  3.0.4p208 (2022-04-12 revision 3fa771dded) [x64-mingw32] and `google-apis-core` 0.9.3.

**Comment by mzuzek** [comment]
@dazuma @bajajneha27 @NivedhaSenthil @SandeepTuniki 

Would you see any reason why `Errno::ECONNRESET` should not be made retriable ?

**Comment by dazuma** [comment]
I think this makes sense, and is in line with the Storage error strategy currently being worked on internally. We should add it here: https://github.com/googleapis/google-api-ruby-client/blob/main/google-apis-core/lib/google/apis/core/http_command.rb#L295

**Comment by mzuzek** [comment]
Thank you @dazuma for your feedback on this issue.
