### ISSUE TITLE
Constrain rexml version (or remove dep?)

### ISSUE THREAD

**Issue by adsr** [googleapis/google-api-ruby-client#18987]
Hello, given fallout from https://github.com/ruby/rexml/issues/131 I think it may be a good idea to version constrain rexml to a minor version.

Separately, is rexml actually used? I don't see anything requiring it.

**Comment by mishina2228** [comment]
I was also curious to see if rexml was being used, but I suspect it is not.
#11024 was proposed, but it was eventually closed without being merged.
Related:
- #871
- #899

**Comment by dazuma** [comment]
removed from dependencies
