### ISSUE TITLE
Document for Google::Apis::GroupssettingsV1::Groups#who_can_join is not correct

### ISSUE THREAD

**Issue by monkeyWzr** [googleapis/google-api-ruby-client#19535]
The description for `ANYONE_CAN_JOIN` and `ALL_IN_DOMAIN_CAN_JOIN` is reversed.

https://github.com/googleapis/google-api-ruby-client/blob/main/generated/google-apis-groupssettings_v1/lib/google/apis/groupssettings_v1/classes.rb#L420-L427

```ruby
        # - ANYONE_CAN_JOIN: Anyone in the account domain can join. This includes
        # accounts with multiple domains.
        # - ALL_IN_DOMAIN_CAN_JOIN: Any Internet user who is outside your domain can
        # access your Google Groups service and view the list of groups in your Groups
        # directory. Warning: Group owners can add external addresses, outside of the
        # domain to their groups. They can also allow people outside your domain to join
        # their groups. If you later disable this option, any external addresses already
        # added to users' groups remain in those groups.
```

[developers.google.com](https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups#:~:text=entry/apps%3AwhoCanJoin) shows the correct content.

<img width="1020" alt="image" src="https://github.com/googleapis/google-api-ruby-client/assets/12955546/f1a9be3e-12cd-4fcd-85a4-52fbae23d19b">

#### Environment details

  - Ruby version: `3.3.0`
  - Gem name and version: `google-apis-admin_directory_v1@0.53.0`

#### Steps to reproduce

https://github.com/googleapis/google-api-ruby-client/blob/main/generated/google-apis-groupssettings_v1/lib/google/apis/groupssettings_v1/classes.rb#L420-L427

Thanks!

**Comment by dazuma** [comment]
Thanks for pointing this out. The descriptions do appear to be swapped. This is due to an issue with the API description published by the Google API service team, and it's not something the auto-generated open source client library in this github repo can fix directly. The API description needs to be corrected upstream. I've submitted an issue to them on your behalf: https://issuetracker.google.com/issues/345499783
