### ISSUE TITLE
GA4 properties are not returned when using AnalyticsV3 Management

### ISSUE THREAD

**Issue by matheusteixeira** [googleapis/google-api-ruby-client#2384]
We're currently using the `Google::Apis::AnalyticsV3` services for querying and user authentication/profile selection. Since the end of last year we began to see an increase number of costumer for which the selection of the GA Profile to be associated was being shown as empty, those customers are mostly new customers that have recently created a new GA4 Account. The account itself is shown in the call results (as demonstrated below) but no properties are listed in the `web_properties`.

#### Environment details

  - OS: Ubuntu/Linux
  - Ruby version: 2.6.6
  - Gem name and version: 'google-api-client', '~> 0.50'

#### Steps to reproduce

  1. Create a new GA4 account
  2. Create a property for the given account
  3. Try and run the following example to retrieve account's properties

#### Code example

```ruby
# example
require 'google/apis/analytics_v3'

def google_analytics_service
  analytics_service = Google::Apis::AnalyticsV3::AnalyticsService.new
  analytics_service.authorization = google_auth_credentials
  analytics_service
end

def google_auth_credentials
  Google::Auth::UserRefreshCredentials.new(
    client_id: ENV['GOOGLE_APP_CLIENT_ID'],
    client_secret: ENV['GOOGLE_APP_CLIENT_SECRET'],
    scope: Google::Apis::AnalyticsV3::AUTH_ANALYTICS,
    access_token: access_token,
    refresh_token: refresh_token,
    expires_at: expires_at
  )
end

def load_accounts_summaries
  @accounts ||= google_analytics_service.list_account_summaries.items
end

@accounts.map do |google_account|
   puts google_account.web_properties #example
end

```

With these values what we do is get the `web_properties`, for my recently created GA4 what I get is:
```
 #<Google::Apis::AnalyticsV3::AccountSummary:0x00007f2ec03ea990
  @id="REDACTED",
  @kind="analytics#accountSummary",
  @name="Test-V4",
  @web_properties=[]>,
```

It's possible to see that `web_properties` is empty, but when looking at GA UI I have Properties listed for this account:
![image](https://user-images.githubusercontent.com/6616633/104465370-bc706200-5592-11eb-8c3e-5ceb5693c1ae.png)

**Comment by dazuma** [comment]
Please consult https://developers.google.com/analytics/help for support information and links to the Analytics team's issue tracker. Or alternatively, if you have a support contract with Google, that should be your first point of contact. This repo is just an open source project that generates client libraries based on the published service descriptions, and we have no visibility into the actual behavior of the API.

**Comment by Uysim** [comment]
Wow, I can't believe we close this issue immediately without the resolution. I should have issue open for discuss on open source so it can help the developer in the community. I also facing the same issue in version 0.53.0 and can not find help.
