### ISSUE TITLE
google-api-client 0.53.0 cannot coexist with Rails 6.1

### ISSUE THREAD

**Issue by qnighy** [googleapis/google-api-ruby-client#2412]
#### Environment details

  - Gem name and version: google-api-client 0.53.0

#### Steps to reproduce

Create the following Gemfile:

```ruby
source 'https://rubygems.org'

gem 'rails', '~> 6.1.0'
gem 'google-api-client', '~> 0.53.0'
```

And do a bundle install:

```
$ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies......
Bundler could not find compatible versions for gem "thor":
  In Gemfile:
    google-api-client (~> 0.53.0) was resolved to 0.53.0, which depends on
      google-apis-generator (~> 0.1) was resolved to 0.1.1, which depends on
        thor (~> 0.20)

    rails (~> 6.1.0) was resolved to 6.1.0, which depends on
      railties (= 6.1.0) was resolved to 6.1.0, which depends on
        thor (~> 1.0)
```

There are two causes of the problem:

- `thor` is too old.
- https://github.com/googleapis/google-api-ruby-client/commit/1cc46b843e87d7ce45c8e150598a8d6acd1cdb1c (https://github.com/googleapis/google-api-ruby-client/pull/2143) has promoted `thor` into a (indirect) runtime dependency.

**Comment by dazuma** [comment]
I can update the thor dependency to `~> 1.0`. However, please note that `google-api-client` is now deprecated. Please use the service-specific gem for the service you want to use. (For example, for Drive V3, use the `google-apis-drive_v3` gem.)

**Comment by dazuma** [comment]
This should be fixed now if you update the `google-apis-generator` gem to 0.1.2. But again, please consider dropping `google-api-client` altogether (which will also drop a lot of unused code, including `google-apis-generator`.)
