### ISSUE TITLE
Web sample sinatra project doesn't work

### ISSUE THREAD

**Issue by jasonkarns** [googleapis/google-api-ruby-client#2449]
#### Environment details

  - OS: macOS Big Sur
  - Ruby version: ruby 3.0.0p0
  - Gem name and version: google-apis-calendar_v3 (~> 0.1)
  google-apis-drive_v3 (~> 0.1)
  google-id-token (~> 1.3)

#### Steps to reproduce

  1. clone repo
  2. cd into samples/web
  3. bundle install
  4. ruby app.rb

->
```
/usr/local/share/gem/gems/sinatra-2.1.0/lib/sinatra/base.rb:1755:in `detect_rack_handler': Server handler (thin,puma,reel,HTTP,webrick) not found. (RuntimeError)
	from /usr/local/share/gem/gems/sinatra-2.1.0/lib/sinatra/base.rb:1493:in `run!'
	from /usr/local/share/gem/gems/sinatra-2.1.0/lib/sinatra/main.rb:45:in `block in <module:Sinatra>'
```

#### Code example

no change from sample project 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by dazuma** [comment]
Thanks for the report. We'll need to update the Gemfile to work with Ruby 3.

**Comment by dazuma** [comment]
This was done a week or so ago.
