### ISSUE TITLE
Push access

### ISSUE THREAD

**Issue by heathermercer163** [googleapis/google-api-ruby-client#2512]
**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Comment by dazuma** [comment]
@heathermercer163 Is there something specific that you need related to this repository?

**Comment by dazuma** [comment]
Closing this issue as I'm not sure what you're asking for. Please feel free to re-open if you have a specific issue you need to file.
