### ISSUE TITLE
Cannot create test order by Shopping content api

### ISSUE THREAD

**Issue by YodaFang** [googleapis/google-api-ruby-client#2681]
Now I cannot create test order by Shopping content api.
From the google api doc, the correct create test order URL is:
![image](https://user-images.githubusercontent.com/49583917/107936813-c4edfb00-6f8b-11eb-84cc-0b706f019517.png)
but from api code, the requested path not correct:
![image](https://user-images.githubusercontent.com/49583917/107936721-a12ab500-6f8b-11eb-8932-d1c5ecd1fd18.png)

**Comment by dazuma** [comment]
It looks like the discovery document (https://shoppingcontent.googleapis.com/$discovery/rest?version=v2.1) specifies the incorrect path. I've opened internal issue b/181030827 to report this.

**Comment by dazuma** [comment]
According to the internal team, this is unfortunately by design, as these calls are not technically part of the v2.1 API. They recommend a workaround like the following: https://github.com/googleads/googleads-shopping-samples/blob/053bc5500405b751c671b169748b963fc142e8cc/ruby/shopping_common.rb#L88
