### ISSUE TITLE
generate-api fails

### ISSUE THREAD

**Issue by mmotherwell** [googleapis/google-api-ruby-client#2712]
generate-api fails as there is no templates directory included in the  google-apis-generator gem.

1. https://github.com/googleapis/google-api-ruby-client/tree/master/google-apis-generator/lib/google/apis/templates/ <-- missing
2. e.g. https://github.com/googleapis/google-api-ruby-client/tree/master/google-apis-generator/lib/google/apis/templates/ dot-rspec.tmpl <-- called in the test I ran
3. Called from google-apis-generator/lib/google/apis/generator/template.rb

#### Environment details

  - OS: Mac OS X 10.15.6 
  - Ruby version: 2.6.6
  - Gem name and version: google-apis-generator v0.1.2

#### Steps to reproduce

  1. generate-api gen lib --url=https://developers.google.com/my-business/samples/mybusiness_google_rest_v4p8.json

#### Code example

ttps://github.com/googleapis/google-api-ruby-client/tree/master/google-apis-generator/lib/google/apis/generator/template.rb

`
module Google
  module Apis
    # @private
     class Generator
      # Directory containing ERB templates
     TEMPLATE_DIR = File.expand_path('../templates', __FILE__) # <--folder doesn't exist
`

**Comment by mmotherwell** [comment]
I fixed this by copying the templates folder from the repo into the gem path on my machine.

**Comment by dazuma** [comment]
Looks like I neglected to include the templates in the files list in the gemspec. Apologies, I'll get that fixed and re-released.

**Comment by dazuma** [comment]
This should have been fixed in version 0.2.0 (https://rubygems.org/gems/google-apis-generator/versions/0.2.0)
