### ISSUE TITLE
Seems to be no gem "google-api-analyticsreporting_v4" available?

### ISSUE THREAD

**Issue by dannyh79** [googleapis/google-api-ruby-client#2767]
First of all, thanks for the SDK that I have been using for long. You guys rock!

Is the ruby gem for "google/apis/analyticsreporting_v4" out? Per [generated doc](https://googleapis.dev/ruby/google-api-client/v0.53.0/index.html) it reads the ruby gem "google-api-client" is deprecated. Yet, as of 2021/02/24, it doesn't seem to be a corresponding gem for "google/apis/analyticsreporting_v4" on https://rubygems.org/.

**Comment by dazuma** [comment]
https://rubygems.org/gems/google-apis-analyticsreporting_v4

**Comment by dannyh79** [comment]
Thank you! I'm closing the issue now.
