### ISSUE TITLE
CalendarV3 insert_event throws NoMethodError undefined method 'each_with_index'

### ISSUE THREAD

**Issue by vanboom** [googleapis/google-api-ruby-client#3305]
#### Environment details

  - OS: Linux / Ubuntu 20.04
  - Ruby version: 2.5.0
  - Gem name and version:  'google-api-client', '0.53'

#### Steps to reproduce

  1. Create a CalendarV3::CalendarService
  2. Create a CalendarV3::Event
  3. Call `insert_event` on the calendar service with the event instance

#### Code example

```ruby
  @calendar = Google::Apis::CalendarV3::CalendarService.new
  @calendar.authorization = < I am using a Google::ApiClient::ClientSecrets object >

    event = Google::Apis::CalendarV3::Event.new(
      summary: "Board Meeting",
      location: "Conference Room",
      description: "Conference description",
      start: {
        date_time: Time.now.to_datetime.rfc3339
      },
      end: {
        date_time: (Time.now + 3.hours).to_datetime.rfc3339
      }
    )
   @calendar.insert_event "primary", event
```

Using the `@calendar` service object instance, I am able to fetch the calendar lists and existing events so I think the auth/connection is good.

But attempting to call insert_event results in the exception
```
  NoMethodError:
       undefined method `each_with_index' for nil:NilClass
```

Here is the backtrace...
```
    # /data/gems/google-api-ruby-client/google-apis-core/lib/google/apis/core/api_command.rb:84:in `prepare!'
     # /data/gems/google-api-ruby-client/google-apis-core/lib/google/apis/core/http_command.rb:99:in `execute'
     # /data/gems/google-api-ruby-client/google-apis-core/lib/google/apis/core/base_service.rb:377:in `execute_or_queue_command'
     # /data/gems/google-api-ruby-client/google-api-client/generated/google/apis/calendar_v3/service.rb:1189:in `insert_event'
```

I am attempting to debug but reaching my limits as the Google library code seems very obfuscated.  Thanks for any assistance.

**Comment by dazuma** [comment]
This is due to a regression in a dependency (declarative-option 0.1.1). See https://github.com/apotonick/declarative-option/issues/6#issuecomment-801098877

The offending gem version has been yanked, so if you re-update your bundle, you should revert to the working 0.1.0 version. That should fix your issue.

**Comment by vanboom** [comment]
Thanks.  Updated bundle, verified declarative-option (0.1.0) in Gemfile.lock and now getting - will attempt to debug further and post findings here. 

```
     Google::Apis::ClientError:
       badRequest: Bad Request
 ```

**Comment by vanboom** [comment]
I attempted to specify the start and end dates like this and get Bad Request...

```ruby
    start: Google::Apis::CalendarV3::EventDateTime.new(date_time: t1),
    end:  Google::Apis::CalendarV3::EventDateTime.new(date_time: t2),
```
Where `t1` and `t2` are both Time instances.  

This works...
```ruby
    start: {date_time: t1.to_datetime.rfc3339},
    end: {date_time: t2.to_datetime.rfc3339},
```
Will close this issue - thanks for the update.
