### ISSUE TITLE
How to create multiple Events in one request

### ISSUE THREAD

**Issue by devchris** [googleapis/google-api-ruby-client#3694]
I have an app where you can create Events in a Calendar. Now I added the ability that whenever a new Event or recurring Event gets created, modified or deleted, it will also make that change in the Google Calendar of the Client. The question is now how would I handle the initial setup where the events would get synced with google? A user could easily have 2000+ Events on the initial call. So far the User has to do an annoying work around -> I create a .ics file for the user, he can download it and import to his calendar. Of course that's not the best user experience. There's an issue with google (https://issuetracker.google.com/issues/36753322) where people ask for a feature to import an .ics file through the api but this isn't a thing apparently. Any help would be highly appreciated, thank you!

**Comment by dazuma** [comment]
The calendar client library can provide only the functionality that is exposed by the underlying API. If it's not feasible simply to loop over the existing events and make individual API calls to add them, then unfortunately there isn't a lot we can do in this open source library. What I recommend is, if you have a support contract with Google, please open a ticket through that channel and ask for help on the Calendar API. If you don't have a support contract, see https://developers.google.com/calendar/support for other means to contact that team.
