### ISSUE TITLE
Invalid credentials even after a successful refresh token

### ISSUE THREAD

**Issue by gnomonunes** [googleapis/google-api-ruby-client#379]
Hello @sqrrrl!

I'm using the gem version 0.8.6 to interact with Google Calendar, and I'm facing an issue with some users:

Before I make any operation in the user's Calendar, I manage to successfully get a new access_token by calling OAuth's refresh token.

But when I try to actually perform the operation on Calendar, I get the following exception: "Google::APIClient::AuthorizationError: Invalid Credentials"

When I verify the token in the tokeninfo endpoint (https://www.googleapis.com/oauth2/v3/tokeninfo), I got something like this:

```
{
 "azp": "XXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com",
 "aud": "XXXXXXXXXXXXXXXXXXXXXXXX.apps.googleusercontent.com",
 "sub": "999999999999999999",
 "scope": "https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/userinfo.email",
 "exp": "1457731304",
 "expires_in": "3101",
 "email": "xxxxx@example.com.br",
 "email_verified": "true",
 "access_type": "offline"
}
```

So, everything seems OK.

This happens only for a few users, so I believe is not an implementation problem.

Do you have any idea about what is causing this, and how could we solve this issue?

**Comment by sqrrrl** [comment]
Sorry, I don't know why that would happen to just a handful of users. Invalid credentials typically means the underlying grant was revoked. But if that were the case, tokeninfo would return the same error and attempts to refresh would fail. I can't think of any good reason (other than some backend issue or latency somewhere) that would give the behavior as described.

The general advice in the case of getting that error is to prompt for authorization again.

The only other thing I could think of would be something in how your using the client -- e.g. using a shared client instance in a multi-threaded app and setting authorization at the client level instead of per-request.

Is it always the same set of users affected and is the error repeatable in a standalone test? That is, could you grab the refresh token for an affected user and reproduce the error in a simple script that just gets an access token and calls the calendar API? If you can isolate it to that level, it might help narrow the problem down.

**Comment by danielbucher** [comment]
[This](https://developers.google.com/identity/protocols/OAuth2#expiration) link contains some reasons that can cause a token to expire. It may be of help to other people with the same problems.

**Comment by gnomonunes** [comment]
It's not the same set of users, but when this happens to a particular user, I'm not able to do any operation in the user's Calendar, so it's credentials become useless.
I can repeat this error with a standalone test as you suggested, and the problem occurs the same way.
By now the only solution I could think of is to notify the user to go through the authorization flow again.

**Comment by sqrrrl** [comment]
That's still very weird behavior -- if the underlying grant is revoked you shouldn't be able to refresh the token at all.

If you can reproduce this in a stand-alone test, could you try waiting a minute or two between when you refresh and when you use the token to see if it starts working?

**Comment by samlehman** [comment]
I too have this issue, but with Google Analytics.  

The GA account I'm trying to run reports off of has A LOT of Accounts/Web Properties/Profiles associated with it. Everything is going well, but sometimes, various calls get a 401 error.  Every call I make creates a new google api client, so there shouldn't be an issue with tokens expiring.  I'm confused.  

Using 0.8.6, Google Analytics API V3.

**Comment by gregorym** [comment]
I have the same issue.
It occurs after my first login or when I refresh the token.

```
{
 "azp": "xxx.apps.googleusercontent.com",
 "aud": "xxx.apps.googleusercontent.com",
 "sub": "xxx",
 "scope": "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/admin.directory.resource.calendar.readonly https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/plus.me https://www.googleapis.com/auth/admin.directory.resource.calendar",
 "exp": "1471158755",
 "expires_in": "3307",
 "email": "my@remail.io",
 "email_verified": "true",
 "access_type": "offline"
}
```

```ruby
class AccessToken
  attr_reader :token
  def initialize(token)
    token = token
  end

  def apply!(headers)
    headers['Authorization'] = "Bearer #{token}"
  end
end

service = Google::Apis::AdminDirectoryV1::DirectoryService.new
service.authorization = AccessToken.new(identity.token)
response = service.list_calendar_resources('my_customer')
```

**Comment by Lycy70** [comment]
Hi everybody, I have the same problem with Google Analytics, exactly as described by @samlehman ...
Did somebody find the solution in the meanwhile? Thank you for any help!

**Comment by dazuma** [comment]
I still don't know what was causing this, but we haven't heard any additional reports for a while, so I'm going to close this issue to avoid confusion. Feel free to reopen if you're still seeing this behavior.

**Comment by mitko-slapdash** [comment]
FWIW, we're experiencing this with a bunch of our users. Refreshing the token succeeds, but then the request still fails with 401 "Invalid Credentials". Would be awesome if you have any steps we can use to force reproduce this scenario on test accounts.

**Comment by strukturedkaos** [comment]
Seeing the same behavior as well - `<Google::Apis::AuthorizationError: Unauthorized status_code: 401` immediately following a token refresh. After failing, a subsequent token refresh results in a successful response. However, that token no longer works.

Right now, I'm rescuing `Google::Apis::AuthorizationError, Signet::AuthorizationError`, refreshing the access token, and retrying the request.

Are there better ways to troubleshoot / address this issue?
