### ISSUE TITLE
Fix readme: insert_file not available in V3

### ISSUE THREAD

**Issue by abhishek77in** [googleapis/google-api-ruby-client#3964]
As per my reading `V3` does not have a method called `insert_file`.

<img width="1024" alt="googleapis_google-api-ruby-client__REST_client_for_Google_APIs" src="https://user-images.githubusercontent.com/749134/117094051-58abb800-ad80-11eb-9106-5a75adc3bf41.png">

**Comment by dazuma** [comment]
Oh, that's embarrassing. I'll get that readme fixed.
