### ISSUE TITLE
The documentation for this gem is 8.6Gigabytes on my machine

### ISSUE THREAD

**Issue by sudhanshuraheja** [googleapis/google-api-ruby-client#425]
Here's a screenshot
https://cloudup.com/c2WwBg1LVDX

**Comment by icco** [comment]
Interesting... Are you just installing with normal gem install? Do you have any flags set in a gemrc or anything? What version of rubygems and ruby are you using?

**Comment by sudhanshuraheja** [comment]
Yes this is all normal gem install. I don't even work on Ruby, so I wasn't trying anything our really.
I usually wouldn't look it up, but my Air is only 128GB :)

**Comment by icco** [comment]
So weird, I normally don't install the docs for this gem, I wonder what's causing this. Until we figure it out @sudhanshuraheja, https://coderwall.com/p/spo6bq/default-no-ri-no-rdoc-on-ruby-gem-installation has instructions to not install docs locally so you can save the space.

**Comment by sudhanshuraheja** [comment]
Thanks Nat :)

On Fri, Jun 17, 2016 at 6:56 PM, Nat Welch <notifications@github.com> wrote:

> So weird, I normally don't install the docs for this gem, I wonder what's
> causing this. Until we figure it out @sudhanshuraheja
> <https://github.com/sudhanshuraheja>,
> https://coderwall.com/p/spo6bq/default-no-ri-no-rdoc-on-ruby-gem-installation
> has instructions to not install docs locally so you can save the space.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/google-api-ruby-client/issues/425#issuecomment-226768141>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABtADOZhzjPyXi695RKkJxho4MgjiLdks5qMqB6gaJpZM4I2M_r>
> .
>



-- 
Sudhanshu Raheja
Managing Director, Leftshift Technologies
http://leftshift.io | +91-9960980066 | @leftshifters

**Comment by icco** [comment]
Oh, I see what's happening, it's generating docs for everything... wow. Surprised it's that large, but it's basically recreating developers.google.com

I ran
```
$ gem install google-api-client --document -V > install-log.txt
```

And the log is: [install-log.txt](https://github.com/google/google-api-ruby-client/files/321079/install-log.txt)

**Comment by icco** [comment]
Hmm, looking at my files, it's only generating 155M of docs

**Comment by sqrrrl** [comment]
Looks like it's rdoc, not the interactive docs (ri). Not sure why it's generating rdoc by default for you. It doesn't for me, and I had to explicitly add --document=rdoc to get the same result.

Using --document=ri yields a much smaller doc set, around 150M.

Anyway, suggest using either --nodocument or --document=ri to work around this. There's not a lot I can do about it at the moment.

One thing I'm thinking about is splitting the generated API into separate gems so folks only need to pull in the ones they need. But no plans to do that any time soon.

**Comment by dazuma** [comment]
This is definitely a pain. The current plan is to address it in #450 so I'm going to close this as a duplicate.
