### ISSUE TITLE
Break services into separate gems

### ISSUE THREAD

**Issue by sqrrrl** [googleapis/google-api-ruby-client#450]
To minimize the footprint + fix some of the doc generation problems (ruby-doc has issues with the size of the gem), split the gem into parts:

google-apis-core: Common code & dependencies shared by all services
google-apis-generator: Code generator
google-apis-(service): Generated code for (service)
google-api-ruby-client: uber gem with all dependencies for compatibility

**Comment by pokonski** [comment]
Installed google-api-client gem takes 42.5MB which is crazy when needed for just a single service.

**Comment by Sharpie** [comment]
Noticed this when packing some Ruby tools into containers. Most of the size of the final container is the result of the `google-api-client`, yet I'm only using the BigQuery client --- so it's mostly wasted space.

**Comment by dazuma** [comment]
It's definitely on the roadmap to break this gem up, although realistically we're still a few months out. In preparation, we've been working internally on cleaning up the tools that generate this gem, and we have to figure out how libraries broken out of this gem should relate to the newer ones developed in https://github.com/googleapis/google-cloud-ruby.

**Comment by Sharpie** [comment]
Any update on the project to break the API client up? `google-api-ruby-client` 0.38.0 is still an absolute unit of a gem weighing in at 62.4 MB. That contributes 66% to the size of what would otherwise be a lean Alpine container.

**Comment by manufaktor** [comment]
I came across this issue while optimising my docker file for Cloud Run. 

I'm using the `google-cloud-storage` gem at version `1.2.6`, which brings in `google-api-client` as a dependency. 

The installed `google-api-client:0.4.2.1` gem comes in at about 67M (using `debian:stable-slim`), which is sadly more than a third of my whole container.

I'm trying some workarounds to remove all unused apis in `/var/lib/gems/2.5.0/gems/google-api-client-0.42.1/generated/google/apis` in my build step but it would be great to have separate, small gems.

**Comment by dazuma** [comment]
We finally got the green light to prioritize this. It's being worked on this quarter.

**Comment by dazuma** [comment]
An update: this is still being worked on. We're having to do a bunch of preliminary things first (in particular, updating the generation and release process to fit into the framework we use for other repos that generate dozens or hundreds of client libraries). It will probably be sometime in December before we actually have the library broken up, but this is a priority and being actively worked on.

**Comment by dazuma** [comment]
This has been completed. Service-specific gems have now been released for all 300+ service/version combinations covered by this gem, and the monolithic google-api-client gem is now deprecated. More info available here: https://github.com/googleapis/google-api-ruby-client/blob/master/google-api-client/OVERVIEW.md
