### ISSUE TITLE
bigquery: Streaming polling support / streaming buffer manual flushing

### ISSUE THREAD

**Issue by jessetuglu** [googleapis/google-api-ruby-client#4555]
Is your feature request related to a problem? Please describe.
Currently, as I see it, there is an option to stream data into bigquery, however there is a max 90 min – I have seen longer – waiting period in which this data is not queryable/editable.

Describe the solution you'd like
Is there a way to manually flush this streaming buffer? Or, at the very least check if there indeed is a buffer via included method?

Describe alternatives you've considered
As far as alternatives, I have been using load rather than insert, but I have noticed this is slow and is not as consistent compared to the services that streaming provides. Plus, it's far more convenient to load ruby native types rather than a csv or json file of some sort.

Thanks!

**Comment by shollyman** [comment]
Control over the buffer semantics are not exposed to end users; it's typically a function of time and data rate.  However, your description is incorrect; data streamed in is queryable immediately, the constraint applies to other operations.  More information here: https://cloud.google.com/bigquery/streaming-data-into-bigquery#dataavailability

That said, there's a [new mechanism in development](https://cloud.google.com/bigquery/docs/write-api) for performing streaming inserts.  However, at present there's only a high level client available via java, but that will improve over time.

**Comment by shollyman** [comment]
Closing this as there's been no further followup.
