### ISSUE TITLE
Conference data not be updated

### ISSUE THREAD

**Issue by jorgeandersonm** [googleapis/google-api-ruby-client#4848]
When try update an event calling :patch_event i have success in any attribute. however when I try to send the conference_data, it does not change.

```
def self.update_calendar_event(google_event)
    random_meet_id = "#{('a'..'z').to_a.shuffle[0,3].join}-#{('a'..'z').to_a.shuffle[0,4].join}-#{('a'..'z').to_a.shuffle[0,3].join}"

    update_event_payload = {
      conference_data: {
        create_request: {
          request_id: "#{('a'..'z').to_a.shuffle[0,10].join}"
        }
      }
    }
    updated_event = @client.patch_event('primary', google_event.id, update_event_payload, conference_data_version: 1)
end
```
I received this return when this method is call

`Sending HTTP patch https://www.googleapis.com/calendar/v3/calendars/primary/events/o7b2u6bf093pi4ef35fvc2b6cs?conferenceDataVersion=1`

**Comment by dazuma** [comment]
Unfortunately, we can't provide support for specific APIs, as this is just an open source project that generates clients given the API descriptions. If you're having issues with the Calendar API, please contact the Calendar team for support: https://developers.google.com/calendar/api/support
