### ISSUE TITLE
ClientSecrets uses pure Signet Client class in to_authorization method and not from google-auth library

### ISSUE THREAD

**Issue by pavelbulanov** [googleapis/google-api-ruby-client#499]
`ClientSecrets `class has `to_authorization `method, which currently uses "pure" `Signet::OAuth2::Client `class from 'signet/oauth_2/client' and not "patched" version from `google-auth-library-ruby` as it should.

[source](https://github.com/google/google-api-ruby-client/blob/master/lib/google/api_client/client_secrets.rb#L149)
```
 def to_authorization
        gem 'signet', '>= 0.4.0'
        require 'signet/oauth_2/client'
        # NOTE: Do not rely on this default value, as it may change
        new_authorization = Signet::OAuth2::Client.new
```

This way returned object won't have` apply!` method and therefore API commands won't update token upon expiration. Same time, official guide [here](https://developers.google.com/identity/protocols/OAuth2WebServer#libraries) states it will:

> The client object will refresh the access token as needed.

Version of class that should be used instead - [here](https://github.com/google/google-auth-library-ruby/blob/master/lib/googleauth/signet.rb) from official `google-auth-library-ruby`

 ```
 # Updates a_hash updated with the authentication token
      def apply!(a_hash, opts = {})
        # fetch the access token there is currently not one, or if the client
        # has expired
        fetch_access_token!(opts) if access_token.nil? || expires_within?(60)
        a_hash[AUTH_METADATA_KEY] = "Bearer #{access_token}"
      end

```

**Comment by dazuma** [comment]
This class is considered deprecated and we haven't been maintaining it. However, since it doesn't look like there's any replacement in `google-auth-library-ruby`, we'll put a fix in to ensure that the `googleauth` extensions are in place when this class is invoked.
