### ISSUE TITLE
undefined method `getByUrl' for #<Google::APIClient::Resource:0x51f860a NAME:blogs>

### ISSUE THREAD

**Issue by techvineet** [googleapis/google-api-ruby-client#50]
When I try to get blog by url it throws this error:-

undefined method `getByUrl' for #<Google::APIClient::Resource:0x51f860a NAME:blogs>

I am doing this:-

blogger = client.discovered_api('blogger', 'v3')
blogger.blogs.getByUrl

but this works 
blogger.blogs.get

Thanks in advance.

**Comment by casiopusat** [comment]
i donot understand
