### ISSUE TITLE
trainedmodels.insert gets "Model name is empty." error

### ISSUE THREAD

**Issue by apraditya** [googleapis/google-api-ruby-client#54]
I tried in the API Explorer on `trainedmodels.insert` passing `id`, `storageDataLocation` and `modelType` and it works. However, on the ruby client, I got error 400 saying "Model name is empty." I setup pretty much the same as in the README, I can execute trainedmodels.list successfully. Here's my code

```
prediction = client.discovered_api(:prediction, 'v1.5')
result = client.execute(
  api_method: prediction.trainedmodels.insert,
  id: 'SiteArticleCategorization',
  parameters: {'storageDataLocation' => storage_path, 'modelType' => 'classification'}
)

result.error_message
# => "Model name is empty."
```

This is my first time using the library, please let me know what other information I should provide to check this issue. Thank you.

**Comment by swapnilchincholkar** [comment]
you guys saved my day, for post requests we need required api's request object with data which we are supposed to pass in body. 

eg. for webmasters -> searchAnalytics/query I passed request body attributes by assigning to "search_analytics_query_request_object" of method "query_search_analytics"
