### ISSUE TITLE
`JSON.pretty_generate` on response objects doesn't actually prettify

### ISSUE THREAD

**Issue by saicheems** [googleapis/google-api-ruby-client#585]
While the call no longer raises an exception, the output is the same as a call to `to_json`.

For example, the expected pretty output a response containing `{'foo': 'bar'}` is
```
{
  "foo": "bar"
}
```

Right now, it's printed as `{"foo":"bar"}`.

**Comment by TheRoyalTnetennba** [comment]
Sorry for the delay. Are you still experiencing this issue?

**Comment by dazuma** [comment]
I can reproduce this. Created a PR with a fix.

**Comment by dazuma** [comment]
(This is actually an issue with the `representable` gem. The PR is a workaround.)
