### ISSUE TITLE
Verify integrity of ID tokens?

### ISSUE THREAD

**Issue by FranklinYu** [googleapis/google-api-ruby-client#596]
According to the [documentation](https://developers.google.com/identity/sign-in/web/backend-auth#using-a-google-api-client-library), it is recommended to validate Google ID token with library. Is it possible to do this in Ruby?

**Comment by 120687** [comment]
Id line:rindupoma

**Comment by ihatov08** [comment]
@franklinyu 

```ruby
require 'google/apis/oauth2_v2'
oauth2 = Google::Apis::Oauth2V2::Oauth2Service.new
access_token = 'XXXXXXXX'
userinfo = oauth2.tokeninfo(access_token: access_token)

=> #<Google::Apis::Oauth2V2::Tokeninfo:0x00555c07f5c158
 @access_type="online",
 @audience="wwwwwwwwwwww.apps.googleusercontent.com",
 @email="example@gmail.com",
 @expires_in=1111,
 @issued_to="wwwwwwwwwwwwww.apps.googleusercontent.com",
 @scope="https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/plus.me",
 @user_id="111111111111111111",
 @verified_email=true>
```

**Comment by franklinyu** [comment]
@ihatov08 Is `#tokeninfo` thread-save? If two threads share a `Google::Apis::Oauth2V2::Oauth2Service` instance and calls `#tokeninfo` concurrently, will there be race condition?

**Comment by yedhukrishnan** [comment]
@ihatov08 The code throws this error:

```
Error - #<Google::Apis::ClientError: Invalid request>
```

Any idea why?

**Comment by Nattfodd** [comment]
Same question here. Don't we need to pass APP key/secret to access token's info?

**Comment by j1wilmot** [comment]
I had success using the above tokeninfo call but passing a token_id instead of an access token.

The `#tokeninfo` call is a wrapper around a request to the /oauth2/v2/tokeninfo endpoint [https://github.com/google/google-api-ruby-client/blob/master/generated/google/apis/oauth2_v2/service.rb#L114] so it's easy enough to copy this functionality by making your own request. There is a v3 endpoint now, so it's probably best / easiest to send a request to the endpoint outside of this library. 

E.G.
    uri = URI 'https://www.googleapis.com/oauth2/v3/tokeninfo'
    response = Net::HTTP.post_form uri, token_id: YOUR_TOKEN_ID

**Comment by baxang** [comment]
https://github.com/google/google-id-token seems to be another option.

**Comment by TheRoyalTnetennba** [comment]
Sorry for the delay. Looking into updating the documentation on this.

**Comment by ihatov08** [comment]
@franklinyu 
`#tokeninfo` is thread-save.
I using this gem with Ruby on Rails, it work without problem.

**Comment by ihatov08** [comment]
@yedhukrishnan Please more information!

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.

**Comment by dazuma** [comment]
At this point, please use the `Google:Auth::IDTokens` class (in the googleauth gem) for ID token verification.

**Comment by nratter** [comment]
> At this point, please use the `Google:Auth::IDTokens` class (in the googleauth gem) for ID token verification.

It says to specify a key_source. I don't see where this is described in the docs. Can you let me know what key_source should consist of?

**Comment by courtneymiller2010** [comment]
@nratter - I was able to get this to work:

```
key_source = Google::Auth::IDTokens::JwkHttpKeySource.new("https://www.googleapis.com/oauth2/v3/certs")
Google::Auth::IDTokens::Verifier.new(key_source: key_source).verify(id_token, aud: client_id)
```
