### ISSUE TITLE
Request support for IdentityToolkit V1 and V2

### ISSUE THREAD

**Issue by kyontan** [googleapis/google-api-ruby-client#6019]
Hi, I found this gem is useful as an alternative to Firebase Admin SDK in Ruby.

When I had been writing code using Firebase Auth, I needed to manage session cookies (https://firebase.google.com/docs/auth/admin/manage-cookies).

I found `createSessionCookie` is implemented as a IdentityToolkit's V1 API (https://cloud.google.com/identity-platform/docs/reference/rest/v1/projects/createSessionCookie).
Though it is not supoprted in the V3 api, I needed to hand-transcoding it. (That worked in my environment)

Is there a plan to add IdentityToolkit V1 and V2 for this gem?

Thanks,

**Comment by dazuma** [comment]
Identity Toolkit V1 and V2 seem to be deprecated and no longer supported according to [this page](https://developers.google.com/identity/toolkit). In any case, this repo determines which services to support automatically by querying [Google's discovery service](https://developers.google.com/discovery), and Identity Toolkit V1 and V2 are not present. Consider the alternatives listed at the top of that page.
