### ISSUE TITLE
Link to the Ruby client libraries in Google documentation is broken

### ISSUE THREAD

**Issue by bringreaner** [googleapis/google-api-ruby-client#6102]
Hello,

The link to this repo is broken in [the official Google API documentation](https://support.google.com/area120-tables/answer/10011390?hl=en). It looks like the file structure has changed, leading to the broken link.

(There is a little link on the documentation that says "give feedback on this article", and I'd rather use that for this issue but unfortunately that also seems to be broken. Clicking it simply brings me to the top of the page.)

**Comment by dazuma** [comment]
Hi, thanks for bringing this to our attention! We can't fix it from here. (This is just an open source client library, and we don't control the support pages.) However, if you hover your pointer to the right of the table on that page, you should see a feedback icon.

![Screen Shot 2021-08-17 at 10 15 48](https://user-images.githubusercontent.com/8911/129771472-06fcf1ed-fac9-46fc-9e5c-59bb058267e9.png)

Click it and it will pop up a panel with a small form for you to report inaccurate content.

**Comment by bringreaner** [comment]
Ahh, thank you! I was confused when I clicked "Give feedback about this article" on your screenshot and it simply jumped to the top of the page. I've sent in the feedback now. I will close this issues. Thanks again!
