### ISSUE TITLE
Conflicting documentation - Is google-api-ruby deprecated?

### ISSUE THREAD

**Issue by AndrewRayCode** [googleapis/google-api-ruby-client#6141]
https://googleapis.dev/ruby/google-api-client/v0.53.0/index.html says the gem is deprecated

the google quickstart guide says to use this gem https://developers.google.com/drive/api/v3/quickstart/ruby

the readme here makes no mention of deprecation

what is the state of this library?

**Comment by dazuma** [comment]
The google-api-client gem is deprecated and is no longer being updated. That gem was a "kitchen sink" gem that included clients for ~300 different services all in one gem. It was more than 70 mb and growing, and was pretty much unsustainable.

Instead, we broke the gem up into separate gems for each individual service. e.g. google-apis-drive_v3. Those ~300 separate gems are the ones being maintained going forward. They also live in this repository.

The quick start guide you linked, has out of date info and needs to get updated.
