### ISSUE TITLE
How To Read Discovery Document for Pages API

### ISSUE THREAD

**Issue by adidaas** [googleapis/google-api-ruby-client#622]
My company application for Pages API - Partner Form was accepted and reading the documentation it told me to use the methods **Google::APIClient.register_discovery_document** and **Google::APIClient.discovered_api** on the plusPages discovery document that is provided. However I've noticed that both methods has been deprecated. 

How do I now read this local discovery document? 

**"generate-api gen <outdir> --file=<path>"** won't work because PlusPages isn't public.

**Comment by mattwhisenhunt** [comment]
Are you receiving an error message?

**Comment by rmorcos** [comment]
@mattwhisenhunt after upgrading to 0.10.3 we are unable to access plusPages api, any advice?

**Comment by dazuma** [comment]
If you have a local discovery document, the following should work, regardless of whether or not the API is public:

```
generate-api gen --file=/path/to/local_discovery.json /path/to/output_dir
```

Note that both the `google-api-client` gem and the `thor` gem must be installed. (Please update to the latest versions.)

If you are encountering an error, feel free to reopen and please post the specific error output you are receiving.
