### ISSUE TITLE
Lots of warnings

### ISSUE THREAD

**Issue by tscheingeld32** [googleapis/google-api-ruby-client#625]
A simple script with warnings enabled gives lots of warnings. The script:

    #!/usr/bin/ruby -w
    require 'google/apis/people_v1'

The warnings:

    /var/lib/gems/2.3.0/gems/google-api-client-0.15.0/lib/google/apis/core/batch.rb:169: warning: assigned but unused variable - length
    /var/lib/gems/2.3.0/gems/os-0.9.6/lib/os.rb:154: warning: mismatched indentations at 'end' with 'for' at 151
    /var/lib/gems/2.3.0/gems/os-0.9.6/lib/os.rb:158: warning: assigned but unused variable - kb
    /var/lib/gems/2.3.0/gems/os-0.9.6/lib/os.rb:198: warning: mismatched indentations at 'end' with 'def' at 190
    /var/lib/gems/2.3.0/gems/os-0.9.6/lib/os.rb:240: warning: mismatched indentations at 'end' with 'case' at 218
    /var/lib/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:51: warning: method redefined; discarding old initialize
    /var/lib/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_cert
    /var/lib/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_file
    /var/lib/gems/2.3.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:58: warning: method redefined; discarding old add_path
    /var/lib/gems/2.3.0/gems/google-api-client-0.15.0/lib/google/apis/core/base_service.rb:215: warning: method redefined; discarding old client

**Comment by bantini** [comment]
@tscheingeld32 I could not replicate it in my MacOSX 10.12.6 with ruby v2.4.2. What is your OS and Ruby version?

**Comment by tscheingeld32** [comment]
Operating system: Ubuntu Linux 16.04.1
Kernel and CPU: Linux 4.4.0-98-generic on x86_64
Processor information: Intel(R) Xeon(R) CPU E5-2630L v2 @ 2.40GHz, 2 cores
ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by tscheingeld32** [comment]
@bantini Just a thought, when you tested, did you make sure to turn on warnings?

**Comment by TheRoyalTnetennba** [comment]
Sorry for the slow response. We’re looking at old questions like this one. Are you still having trouble with the warnings?
