### ISSUE TITLE
Classroom: Creating a course with an id set to an arbitrary alias fails

### ISSUE THREAD

**Issue by jaapie** [googleapis/google-api-ruby-client#6259]
#### Environment details

  - OS: Ubuntu
  - Ruby version: ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
  - Gem name and version: google-apis-classroom_v1 0.6.0

#### Steps to reproduce

  1. setup as normal (authorise the app etc, create the service object)
  2. attempt to create a classroom with a string as an id
  3. experience a 400 Invalid Request

#### Code example

```ruby
# create service object, authorise like normal
$classroom_service = Google::Apis::ClassroomV1::ClassroomService.new
$classroom_service.client_options.application_name = APPLICATION_NAME
$classroom_service.authorization = authorize # pre-defined function

the_course = Google::Apis::ClassroomV1::Course.new(
  course_state: 'ACTIVE',
  name: 'My Course',
  section: 'Its Section',
  guardians_enabled: false,
  id: 'my-course-alias',
  owner_id: 'me@me.com'
)

$classroom_service.create_course(the_course) do |result, err|
.
.
.
end

```

A 400 Invalid Request error results with the message: Request contains an invalid argument. Removing the `id:` parameter in the creation of the Course object allows the `create_course` call to succeed.

According to the docs (https://developers.google.com/classroom/reference/rest/v1/courses#Course): 

> When creating a course, you may optionally set this identifier to an alias string in the request to create a corresponding alias. The id is still assigned by Classroom and cannot be updated after the course is created.
>
> Specifying this field in a course update mask results in an error.

GAM allows one to create a classroom with an ID set to a string, but I don't know the inner workings of it so I don't know the method it uses to accomplish this.

**Comment by dazuma** [comment]
According to https://developers.google.com/classroom/reference/rest/v1/courses.aliases#CourseAlias the alias string should have the format `d:<name>` (indicating a domain-scoped alias) or `p:<name>` indicating a project-scoped alias. For example, `d:math_101` might be valid, but `my-course-alias` would not.

**Comment by jaapie** [comment]
Ye gods. Sometimes you can't see the forest for the trees. I actually read that as well, and dismissed it not thinking I'd need it. Thanks for your help!
