### ISSUE TITLE
Bigquery::QueryData#all is very slow

### ISSUE THREAD

**Issue by ifarkas** [googleapis/google-api-ruby-client#627]
I tried to run a query on BigQuery using the ruby client (on ruby 2.4.2p198):
```
bigquery = Google::Cloud::Bigquery.new(project: project_id)

sql = "SELECT * FROM ..."
job = bigquery.query_job(sql, legacy_sql: false)
job.wait_until_done!

data = job.query_results
data.all do |row|
  # do stuff
end
```

A query with a resultset of 6.5M rows runs for 960 seconds. Performance of other client implementations doesn't seem to suffer that much:
- python - 180 seconds
- go - 140 seconds

Profiling the following line:
```
result = RubyProf.profile do
  job.query_results
end
```

(first 30 lines...)
```
Measure Mode: wall_time
Thread ID: 8736600
Fiber ID: 19644200
Total: 22.688366
Sort by: self_time

 %self      total      self      wait     child     calls  name
  9.34      5.710     2.120     0.000     3.590   800010   Representable::Binding::EvaluateOption#evaluate_option
  5.72      1.299     1.299     0.000     0.000  1200017   Hash#initialize_copy
  3.56      2.419     0.808     0.000     1.611  1000014   Hash#merge
  2.72      0.617     0.617     0.000     0.000  1000015   Representable::Binding#exec_context
  2.41      0.918     0.547     0.000     0.372  1000099   Representable::Binding#[]
  1.89      0.429     0.429     0.000     0.000   200005   BasicObject#instance_exec
  1.87      1.722     0.424     0.000     1.299  1200026   Kernel#initialize_dup
  1.68      1.117     0.381     0.000     0.736   400035  *Class#new
  1.64      0.372     0.372     0.000     0.000  1000119   Representable::Definition#[]
  1.35      0.306     0.306     0.000     0.000        1   JSON::Ext::Parser#parse
  1.30      1.035     0.296     0.000     0.740   200001   Representable::Hash#filter_wrap
  1.24      0.740     0.282     0.000     0.457   200001   Representable#representation_wrap
  1.17      2.067     0.267     0.000     1.800   200000   Representable::Function::Decorate#call
  1.10      0.371     0.248     0.000     0.122   100000   <Module::Google::Cloud::Bigquery::Convert>#format_value
  1.00      0.359     0.226     0.000     0.133   200001   Representable#representable_attrs
  0.93      0.212     0.212     0.000     0.000   300000   <Class::Hash>#[]
  0.91      0.207     0.207     0.000     0.000   800013   Module#===
  0.76      0.389     0.172     0.000     0.217   200001   Representable::Cached#representable_map
  0.75      0.170     0.170     0.000     0.000   500000   String#to_sym
  0.61      0.249     0.137     0.000     0.111   200012   Kernel#dup
  0.60      0.520     0.135     0.000     0.385   200000   Representable::Function::Decorate#prepare_for
  0.57      0.233     0.129     0.000     0.103   200005   Representable::Hash::Binding#read
  0.54      0.178     0.121     0.000     0.056   200001   <Class::Representable::Decorator>#map
  0.53      0.327     0.121     0.000     0.206   100000   Google::Apis::BigqueryV2::TableRow#initialize
  0.51      0.385     0.115     0.000     0.270   200000   <Class::Representable::Decorator>#prepare
  0.49      0.317     0.112     0.000     0.205   100000   Google::Apis::BigqueryV2::TableCell#initialize
  0.46      0.155     0.104     0.000     0.051   200001   Representable#normalize_options
  0.45      0.103     0.103     0.000     0.000   200018   Hash#has_key?
  0.44      2.337     0.099     0.000     2.238   400006  *Array#map
  0.43      0.098     0.098     0.000     0.000   200001   Representable::Config#wrap_for
```

It seems much of the execution is spent on converting the response to objects. Is this the expected behaviour? Or can we somehow avoid the conversion and return the JSON response instead?

**Comment by ifarkas** [comment]
Just a bit of clarification: 
`Bigquery::QueryData#all` can be found in the `google-cloud-bigquery` gem. I opened the ticket in this project because it ends up calling `Google::Apis::BigqueryV2::BigqueryService#list_table_data` in this project which does all the deserialization, hence causing the performance issue.

**Comment by sqrrrl** [comment]
Yes, deserialization is slow right now. There's a hacky workaround supported byt the client though. See https://github.com/google/google-api-ruby-client#using-raw-json

Basically you can just have it return the raw request body then handle the JSON deserialization yourself which some others have already found can be a substantial boost.

**Comment by mattwhisenhunt** [comment]
You might also want to take a look at https://github.com/GoogleCloudPlatform/google-cloud-ruby/tree/master/google-cloud-bigquery

**Comment by dazuma** [comment]
@blowmage Assigning this to you for now. The BigQuery veneer does use this client under the hood, so it's relevant.

**Comment by blowmage** [comment]
All google-cloud-bigquery versions 0.30.0 and later have changes that address this specific issue. The most performant approach using google-api-client is to set `skip_deserialization` when making RPC calls to return the raw JSON text.

```ruby
require "google/apis/bigquery_v2"
require "json"

bigquery = Google::Apis::BigqueryV2::BigqueryService.new
json_text = bigquery.list_table_data "my_project_id",
                                     "my_dataset_id",
                                     "my_table_id", 
                                     options: { skip_deserialization: true }
json_hash = JSON.parse json_text
```

We have some unfortunate timing for this issue, as googleapis/google-cloud-ruby#1779 was merged before this issue was opened, but not before version 0.30.0 was released. Because of this, I am inclined to close this issue as resolved. If you are experiencing a similar performance issue, please open a new issue against either googleapis/google-api-ruby-client or googleapis/google-cloud-ruby and reference this issue.
