### ISSUE TITLE
Avoiding an "empty batch request"

### ISSUE THREAD

**Issue by fukuchi** [googleapis/google-api-ruby-client#6543]
Batch processing using the code block mechanism of Ruby is really awesome. I'm really enjoying Google API programming with this library. Thank you all.

When I put a conditional branch inside a batch requesting code block as following:

```
ids = ['file_id_1', 'file_id_2', 'file_id_3', 'file_id_4']
drive.batch do |drive|
  ids.each do |id|
    if this_file_should_be_queued(id)
      drive.get_file(id) do |res, err|
         ...
      end
    end
  end
end
```

This process worked as expected if one or more files needed to be queued, but it raised `Google::Apis::BatchError` and said "Can not make an empty batch request" if none of them had been queued. I expected that the `drive.batch do ... ` exits silently.

Now I have three questions:

1)
Is it OK to catch the `BatchError` and ignore it and continue the following process like this?

```
begin
  drive.batch do |drive|
    ...(skipped)...
  end
rescue Google::Apis::BatchError => e
end
```

2)
As far as I checked the source code of the client library, `Google::Apis::BatchError` is also raised when the response's header line was invalid (batch.rb: split_header_and_body()). I'm afraid that I cannot distinguish between those two, where one could be harmless.

Can you raise a different error when the queue was empty to distinguish it from the invalid, non-recoverable situation?

3)
Why does not the `drive.batch do |drive|` exit silently when the queue is empty? I think you could simply skip the batch processing if it is empty.

**Comment by NivedhaSenthil** [comment]
I think filtering the array of ids based on the condition before doing batching can avoid this. Like
``` ruby
filtered_ids = ids.filter { |id| this_file_should_be_queued(id) }
```

Thanks for writing an elaborate issue with possible fixes. As we are not actively maintaining this gems and there is a work around, closing the issue for now. Feel free to reopen if you have more queries.
