### ISSUE TITLE
Support for different release types [Instant app, Automotive OS]

### ISSUE THREAD

**Issue by nate-eisner** [googleapis/google-api-ruby-client#6544]
I am trying to track down if there is an automated process to release Instant app or Android Automotive versions of our app. I don't see an option in the API to select which release type of to update.

Similar to how we can determine which track to update (production, beta, etc..) it would be nice to have the option to select your app release type. 

For reference, the Play console has a drop down to select your type of app for each track
![Screenshot at 2021-09-23 07-52-45](https://user-images.githubusercontent.com/8662843/134543898-04a0cc82-1e53-4d44-aba5-5fcf2c792807.png)

**Comment by danoscarmike** [comment]
Hi @nate-eisner! Not sure this is the best issue tracker. What console/platform are you working in that you'd like to see this feature? I'll try to direct as best I can.

**Comment by nate-eisner** [comment]
@danoscarmike I was trying to add functionality to fastlane to automate the release of our Android Automotive app and our Instant app. Seeing that they use this api client, I figured this would be the best place to start. Let me know if there is a better place for this.

**Comment by danoscarmike** [comment]
Gotcha. I'm afraid we don't have any input into the release/distribution of applications using our client libraries.

If I understand correctly the Android team would be the best point of contact here. They have a public issue tracker here: https://b.corp.google.com/u/0/issues/new?component=190923&template=841312&pli=1

I also found some relevant reference docs here: https://developer.android.com/distribute/best-practices/launch/distribute-cars

I'm going to close this issue out, but please feel free to reply.

**Comment by narko** [comment]
@danoscarmike is this still a feature that could be reconsidered? 
If this is not the right project as you mentioned, you would you mind sharing the public link to the issue tracker? This is link seems to be available only for Googlers: https://b.corp.google.com/u/0/issues/new?component=190923&template=841312&pli=1

**Comment by danoscarmike** [comment]
Sorry about the broken link 🙏🏻 

I'm no longer working on this project, but I'd guess the Google Play issue tracker that you link here is a good place to start. It's being actively triaged so the team there should be able to point you in the right direction.
