### ISSUE TITLE
watch_user endpoint returns Server Error

### ISSUE THREAD

**Issue by olegpanchenko** [googleapis/google-api-ruby-client#657]
I tried to set up a push notification watch on the given user mailbox
```ruby
watch_request_object = Google::Apis::GmailV1::WatchRequest.new topic_name: 'projects/:project_id/topics/:topic_name', label_ids: [':label_id']
res  = client.watch_user 'me', watch_request_object
```
I got backendError
```json
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 500,
  "message": "Backend Error"
 }
}
```
is this endpoint  supported?

**Comment by mattwhisenhunt** [comment]
It is. That generic 500 error makes me think something hasn't been completely set up yet.

Did you…
- [ ] Create topic
- [ ] Create a subscription for that topic
- [ ] Add gmail-api-push@system.gserviceaccount.com as a publisher

- [ ] Try the request without specifying any labelIds
?

**Comment by shout-developer** [comment]
Is _gmail-api-push@system.gserviceaccount.com_ something that I have to create? The closest I can get to is gmail-api-push@my-project.iam.gserviceaccount.com.

**Comment by shout-developer** [comment]
> ** Add [gmail-api-push@system.gserviceaccount.com](mailto:gmail-api-push@system.gserviceaccount.com) as a publisher **
> 
> Did not see that in any doc...I had the same issue and that did the trick for me.

To anyone reading [the gmail push notification docs](https://developers.google.com/gmail/api/guides/push), the docs specifically say to use `serviceAccount:gmail-api-push@system.gserviceaccount.com`. That is not a valid name, but as @devtoro pointed out, you can use `gmail-api-push@system.gserviceaccount.com` (note the omission of `serviceAccount:`), which is the right one to use.
