### ISSUE TITLE
Consider switch from mime-types dependency to mini_mime

### ISSUE THREAD

**Issue by jrun** [googleapis/google-api-ruby-client#659]
The [mime-types](https://github.com/mime-types/ruby-mime-types/) gem is used in [Google::Apis::Core::BaseUploadCommand](https://github.com/google/google-api-ruby-client/blob/master/lib/google/apis/core/upload.rb#L58) to determine the MIME type of the uploaded file via the filename.

The [mini_mime](https://github.com/discourse/mini_mime) library is an alternative which has a lower memory footprint. [This pull request on the mail library](https://github.com/mikel/mail/pull/1059) has some discussion on the topic.

This came to my attention because the mail library has switched to mini_mime as of version 2.7. The mail library is used by a large number of Rails apps through the actionmailer library. Switching to mini_mime will help eliminate a relatively resource intensive dependency (mime-types) which offers redundant functionality.

**Comment by bborn** [comment]
Bump - any updates on this?

**Comment by TheRoyalTnetennba** [comment]
Would you be open to creating a PR?

**Comment by blowmage** [comment]
FYI, the google-cloud-bigquery and google-cloud-storage gems have an undeclared runtime dependency on mime-types, expecting to get the dependency from google-api-client. I have an open PR to declare this dependency, but I would _prefer_ to have those releases out for a while before changing the dependency here, but I understand that this is not google-api-client's fault for these missing dependencies.

**Comment by bborn** [comment]
Just submitted a PR

**Comment by blowmage** [comment]
Closed by #789
