### ISSUE TITLE
Normal error response

### ISSUE THREAD

**Issue by makshark** [googleapis/google-api-ruby-client#671]
Hi, it is not fun when you work first with your API and fond a lot of strange not logical moments, 
for example, google my business, I want to create a local post - but get an error, 
something like 
`{"error"=>
  {"code"=>400,
   "message"=>"Request contains an invalid argument.",
   "errors"=>
    [{"message"=>"Request contains an invalid argument.",
      "domain"=>"global",
      "reason"=>"badRequest"}],
   "status"=>"INVALID_ARGUMENT"}}`

I am not a wizard to understand what it is wrong, i just try to reproduce all of this in your tryout/playground service and got - 
`{
  "error": {
    "status": "INVALID_ARGUMENT", 
    "message": "Request contains an invalid argument.", 
    "code": 400, 
    "details": [
      {
        "errorDetails": [
          {
            "message": "Do not specify category or price list item id for local post photos", 
            "code": 3
          }
        ], 
        "@type": "type.googleapis.com/google.mybusiness.v4.ValidationError"
      }
    ]
  }
}`
Wow, i see errorDetails, cool.
Could you add the same behaviour to your gem? 
P.S. Maybe better to remove Hurley logic? It is outdated and does not support anymore.

**Comment by alexshakura** [comment]
@JustinBeckwith any update on this issue?

**Comment by blowmage** [comment]
The google-api-client gem doesn't alter the error information in any way. The values returned are coming from the API, and the client is unable to infer the additional level of information you are asking for. It looks like the playground service in your example is a slightly different API that is returning slightly different results.

You can use the [My Business Support](https://developers.google.com/my-business/content/support) page to request that the level of detail in the error responses for the production API matches the playground API.
