### ISSUE TITLE
AndroidpublisherV3 incompatible with PagedResults

### ISSUE THREAD

**Issue by marcgreenstock** [googleapis/google-api-ruby-client#676]
It seems as through the `AndroidpublisherV3` is incompatible with the `Google::Apis::Core::PagedResults`. This may also be the case for other versions, although I haven't checked.

`PagedResults` is expecting the method assigned to `@response_page_token_field` to return the next page token however `#token_pagination` returns an instance of `TokenPagination`. 

https://github.com/google/google-api-ruby-client/blob/b35f5face3649f25a4f24413b1fc9288f8bbe732/lib/google/apis/core/base_service.rb#L83

**Comment by blowmage** [comment]
Hi @marcgreenstock, this seems to be correct. The Android Publisher API doesn't seem to be compatible with the paged results convention. How are you trying to use `PagedResults` with this API? Is this something you are doing? Or something the client is attempting to provide that is not working?

**Comment by blowmage** [comment]
I've [looked through the API](https://googleapis.dev/ruby/google-api-client/latest/Google/Apis/AndroidpublisherV3/AndroidPublisherService.html) and I don't see any use of PagedResults by the ruby client. It looks like the API is not intended to be paging compatible at the moment. [Here is a link](https://support.google.com/googleplay/android-developer/answer/7218994) to the Android dev team if you want to file a feature request for the Android API.
