### ISSUE TITLE
Google::Apis::DriveV3::DriveService#export_file returns empty response

### ISSUE THREAD

**Issue by paranoicsan** [googleapis/google-api-ruby-client#680]
Working with `google-api-client v 0.21.1`

Calling `export_file` on Google Sheet file 
```ruby
service.export_file('17DV_i-Q3wlYut8QTfWg0mZON-GZ_By0JefU2TQl1l5o', 'application/zip')
```

And getting back (looks very similar to #467)
```
Success - ""
```

Any other mime type returns the requested data.
Any ideas where to dig?

**Comment by SurferJeffAtGoogle** [comment]
@paranoicsan I apologize for the delay responding to this issue.  Is it still causing problems?  Have you found a work around?

**Comment by paranoicsan** [comment]
@SurferJeffAtGoogle I've just tried to export the sample file again and it works. Weird though. Something has been changed in Google service itself or inside `google-api-client` (I've just tested using _v0.31.0_) 

Closing it.
