### ISSUE TITLE
Support direct mapping of google.api.HttpBody fields to the http request/response

### ISSUE THREAD

**Issue by mijoharas** [googleapis/google-api-ruby-client#696]
If you try and use `predict_project` in `Google::Apis::MlV1::CloudMachineLearningEngineService` it will not work out of the box.

The `GoogleCloudMlV1PredictRequest` in `representations.rb` only has a property of `httpBody` which should be `instances` (as per https://cloud.google.com/ml-engine/docs/v1/predict-request )

The `GoogleApiHttpBody` in `representations.rb` only has the property `content_type`, `data` and the collection `extensions` it should include `predictions` (as per https://cloud.google.com/ml-engine/docs/v1/predict-request)

These problems can be worked around by a user by using `options: {skip_serialization: true, skip_deserialization: true}`

**Comment by dazuma** [comment]
Thanks for this report. It looks like directly mapping the http body is a feature of a small number of Google APIs that is not supported by the client. As far as I can tell, three APIs use it: Ml V1, HealthCare V1beta1, and DomainsRdap V1.

As you've noted, you can work around this by disabling serialization and deserialization. For now, I'm going to have to put this on the feature backlog, as implementing it will require tinkering with the generator and we don't have the bandwidth for it at the moment.

**Comment by bajajneha27** [comment]
Hi @mijoharas and @Tim-Casey,
We're not taking significant feature request for this repository and the workaround is documented in our [usage-guide.md](https://github.com/googleapis/google-api-ruby-client/blob/main/docs/usage-guide.md#using-raw-json).
I'll go ahead and close the issue for now. Please feel free to reopen it there's anything you need from us.
