### ISSUE TITLE
Insufficient tokens for quota WriteGroup

### ISSUE THREAD

**Issue by ghanshyam-schoolbook** [googleapis/google-api-ruby-client#697]
Hello,
I am getting following error
"Google::Apis::RateLimitError: rateLimitExceeded: Insufficient tokens for quota 'WriteGroup' and limit 'USER-100s' of service 'sheets.googleapis.com' for consumer 'project_number:864617607794'."
Can anyone guide me how to resolve this issue

**Comment by TheRoyalTnetennba** [comment]
Sorry your having this issue. What were you doing in the process? How might I reproduce this error?

**Comment by shaardul** [comment]
@TheRoyalTnetennba  
This is what honey badger told me, the error was triggered from the third line. I am using google_drive gem in ruby on rails
```
google_spreadsheet = google_drive_session.spreadsheet_from_key(spreadsheet_hash)
worksheet = google_spreadsheet.sheet_by_title(worksheet_type)
worksheet.update(insert_data, 'A' + (offset + 1).to_s, 'USER_ENTERED') [this line triggered the error]
```

**Comment by blowmage** [comment]
Please see the following link for information on this error and how to adjust your quota:

https://developers.google.com/sheets/api/limits
