### ISSUE TITLE
Most compute methods return an object if `nil` is passed in get

### ISSUE THREAD

**Issue by Temikus** [googleapis/google-api-ruby-client#698]
I would expect that, for example `@compute.get_image(project, nil)` should either return nil or raise an error. For most of compute methods, however it returns an object.

E.g. for `get_image`:
```
@compute.get_image(project, nil)
=> #<Google::Apis::ComputeV1::Image:0x00007fa663dfc4b8
 @id=0,
 @kind="compute#imageList",
 @self_link="https://www.googleapis.com/compute/v1/projects/my-project/global/images/">
```

**Comment by bajajneha27** [comment]
Hi @Temikus 
Thank you for your patience here. 
The [google cloud compute](https://github.com/googleapis/google-cloud-ruby/tree/main/google-cloud-compute) gem is now GRPC based. Would it be possible for you to use that instead? We're maintaining GRPC gems more currently.

**Comment by NivedhaSenthil** [comment]
Closing this issue in favour of the modern gem.
