### ISSUE TITLE
GCE instance creation issue : Not Found (Google::APIClient::ClientError)

### ISSUE THREAD

**Issue by ruby2001** [googleapis/google-api-ruby-client#700]
Hi Guys ,
  
Ruby : ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]
Fog : fog (1.37.0)
fog-google : (1.6.0, 1.3.3, 0.5.2, 0.0.7)
google-api-client : (0.23.3, 0.19.8, 0.8.6, 0.8.4)

When tried creating Google Compute Engine instance using below fog API , getting Not Found (Google::APIClient::ClientError) .

gclient=Fog::Compute.new({:provider => 'google',:google_project => @@google_project_name ,:google_client_email => @@gclient_mail,:google_json_key_location => @@google_key})

`
/home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:662:in `block (2 levels) in execute!': Not Found (Google::APIClient::ClientError)
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:645:in `block in execute!'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:636:in `execute!'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:368:in `discovery_document'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/google-api-client-0.8.6/lib/google/api_client.rb:413:in `discovered_api'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/fog-google-0.0.7/lib/fog/google/compute.rb:1064:in `initialize'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/fog-core-1.44.3/lib/fog/core/service.rb:115:in `new'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/fog-core-1.44.3/lib/fog/core/service.rb:115:in `new'
	from /home/ubuntu/.rvm/gems/ruby-2.0.0-p247/gems/fog-core-1.44.3/lib/fog/compute.rb:55:in `new'
`
Please take a look and help us out on this , this is blocking our instance creation flow . Let me know if any additional details are required .

Thanks ..

**Comment by dazuma** [comment]
You probably need to update your bundle. The stack trace looks like google-api-client version 0.8.6 is in use. This version is outdated and unsupported (and indeed you appear to have newer versions installed already). The most recent version of google-api-client is 0.25.0.
