### ISSUE TITLE
Instant App support

### ISSUE THREAD

**Issue by vanniktech** [googleapis/google-api-ruby-client#703]
Correct me if I'm wrong but it seems like instant app upload support is missing. This would eventually be required by upstream consumers such fastlane - https://github.com/fastlane/fastlane/issues/12865

**Comment by dazuma** [comment]
@vanniktech Are you talking about a particular API call that isn't covered by the client library? If so, can you specify which API and which call? (Maybe point to a line in the API reference documentation?)

Or are you saying there's a feature that isn't covered by any API call? If so, please contact the appropriate product team directly. For example, issues related to android can be reported at https://issuetracker.google.com/issues/new?component=190923&template=841312

**Comment by vanniktech** [comment]
For android app bundles there's a dedicated method for uploading / editing them. 

https://github.com/google/google-api-ruby-client/blob/ef45bf244353e338897ebb01e797b6573b332ed1/generated/google/apis/androidpublisher_v3/service.rb#L438

I'd assume / expect that there would also be a dedicated function for uploading instant apps.

**Comment by vanniktech** [comment]
Any update on this @dazuma?

**Comment by blowmage** [comment]
Which of the [API endpoints](https://developers.google.com/android-publisher/api-ref/) are missing from the client library?

**Comment by blowmage** [comment]
I am not an Android developer or user, but from what I can tell the only way to support Instant Apps is with a bundle. The instant app needs to be able to convert to a fully downloaded app, so I don’t see how an instant app could exist outside of a bundle. That, and the lack of support for them in the API makes me think the API and Ruby client are likely correct. 

Can you point to this feature in other language clients?

**Comment by vanniktech** [comment]
You don't necessarily need a bundle. You can also just upload the `zip` file.

![screenshot from 2018-12-24 17-41-17](https://user-images.githubusercontent.com/5759366/50403947-24349400-07a3-11e9-9a86-dfd72a89d039.png)

It seems like there's `Edits.apk`, `Edits.bundles` but no `Edits.instantapps`. That's weird. How can one use the API to upload instant apps?

**Comment by blowmage** [comment]
Have you tried uploading a zip file to `upload_edit_bundle`?

**Comment by RishabhTayal** [comment]
@blowmage I have tried uploading a zip to the `upload_edit_bundle` method. It gives the following error.

`appBundleUnsigned: The Android App Bundle was not signed. Please sign the bundle using jarsigner.`

**Comment by blowmage** [comment]
@RishabhTayal Does this help? https://developer.android.com/studio/publish/app-signing

**Comment by blowmage** [comment]
I am assuming that the Web UI is doing more than being a simple front end to the API. The URL I shared describes how the Web UI will sign bundles. But if you are using the API directly you will have to perform these prerequisite tasks.

**Comment by RishabhTayal** [comment]
@blowmage So I tried using `jarsigner` to sign the zip file and then upload. I am getting a different error this time.

`appBundleValidateToolFailure: We have failed to run bundle-tool validate on this Android App Bundle. Please ensure your bundle is valid by running this command. Error message output: The archive doesn't seem to be an App Bundle, it is missing required file 'BundleConfig.pb'.`

The jarsigner command I used: `$ jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore MYKEYSTORE ../path/to/instantapp-release.zip ALIAS`

**Comment by RishabhTayal** [comment]
@blowmage any idea about the solution?

**Comment by blowmage** [comment]
Unfortunately this is very much outside of my area of expertise. I would ask on StackOverflow or open a support ticket if you have a support contract.

AFAICT the ruby client is connecting to the API and performing as expected.

**Comment by vanniktech** [comment]
I've stopped caring about instant apps. Only using Android Bundles.
