### ISSUE TITLE
Intermittent OpenSSL::SSL::SSLError's: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello

### ISSUE THREAD

**Issue by akshaynathan** [googleapis/google-api-ruby-client#713]
I'm using this gem to make multiple calls to the Drive API in a Sidekiq worker. The worker is running in an Ubuntu 16.04 container (not MacOS like previous similar issues), and I'm sporadically seeing the error above in my application logs.

I'm unable to find any pattern in when or which calls cause this error, but in any case, they succeed on retry.

Any guidance in debugging this would be immensely helpful.

**Comment by mashedkeyboard** [comment]
Hey, sorry to reply to such an old issue, but did you make any headway on this @akshaynathan?

**Comment by akshaynathan** [comment]
Unfortunately not -- I'm not working on the related project anymore, but we eventually just ended up monitoring the exception rates and silencing it.

**Comment by gwilton** [comment]
@mashedkeyboard We recently started seeing these intermittent errors in our ruby application. Have you made any headway on your end. We are thinking of upgrading out HTTP client and openssl lib.

**Comment by meredithslota** [comment]
Hi all — I'm closing this out as I believe @DickyMacias identified the issue, but if folks are still having this problem, can you please open a new issue and provide updated debugging info? Thanks so much!
