### ISSUE TITLE
How do i use Google::Apis::ComputeBeta::InstanceGroupManagerList to get an existing instance group and perform a rolling update?

### ISSUE THREAD

**Issue by medigun** [googleapis/google-api-ruby-client#717]
Hi, i would like to know how i can use https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/ComputeBeta/InstanceGroupManagerList to capture a list of instanceGroups and perform a [rolling update](https://cloud.google.com/compute/docs/instance-groups/updating-managed-instance-groups#performing_a_rolling_replace_or_restart) on an instance. The docs seem outdated and i couldn't get the hang of it. Would really appreciate some help.

**Comment by dazuma** [comment]
To list instance group managers, you probably want this API: https://cloud.google.com/compute/docs/reference/rest/beta/instanceGroupManagers/list
Scroll to the bottom of that page to find some sample code. There's a Ruby tab that contains Ruby samples.

Then to perform a rolling update, if you look at the API tab in the docs, you'll see that you need to make a PATCH request on an instanceGroupManager (that presumably you got by calling the above list API). So go back to the API reference and find the patch call on instanceGroupManager, which is here: https://cloud.google.com/compute/docs/reference/rest/beta/instanceGroupManagers/patch
Again, at the bottom of the page is a sample code skeleton. You'll need to build a `Google::Apis::ComputeBeta::InstanceGroupManager` object as the request body, so look up that [class](https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/ComputeBeta/InstanceGroupManager) in the class reference, and fill the fields according to what the [documentation[(https://cloud.google.com/compute/docs/instance-groups/updating-managed-instance-groups) tells you.

Yes, you have to pick up information from a few different sources, but with so many programming languages and cases being supported, there isn't much way around that. And it's not bad once you get the hang of it.

Feel free to reopen if you still have questions. But you might consider using StackOverflow instead. There's usually better visibility there for questions and answers.
