### ISSUE TITLE
Autogenerated code creatse one giant file with multiple classes

### ISSUE THREAD

**Issue by quantumproducer** [googleapis/google-api-ruby-client#718]
https://github.com/googleapis/google-api-ruby-client/blob/master/generated/google/apis/analytics_v3/classes.rb

For example, should put each class into a separate file for easier developer readability.

**Comment by dazuma** [comment]
Thanks for the feedback. Agreed it would be better to split by classes; however, we're not likely to prioritize it for this codebase, as we're focusing development efforts on the modern clients in https://github.com/googleapis/google-cloud-ruby.
