### ISSUE TITLE
Do I need to write refresh token cron?

### ISSUE THREAD

**Issue by kazuooooo** [googleapis/google-api-ruby-client#719]
Hi, I make app using GoogleClendarApi.
I succeed to authorize user and use api, but after 1hour token expires and get authorization error.

It looks [java client library automatically refresh token](https://developers.google.com/api-client-library/java/google-api-java-client/oauth2)

ruby client also has this feature? or do I need to implement by myself?
I'm little bit confusing, glad to someone help.

thanks,

**Comment by TheRoyalTnetennba** [comment]
You need to implement it yourself. You can call `credential.refresh! if credential.expires_within?(number_of_seconds)` where you make your request if you'd like to avoid creating a cron job.

**Comment by kazuooooo** [comment]
Thank you for your reply.
OK I'm implementing by myself.

If I understand correctly, refresh token can not be used after access token expires. So If user make request after his access token expires, this  looks does not work.
In case user does not access for long time, I need to write cron job?

> credential.refresh! if credential.expires_within?(number_of_seconds) where you make your request if you'd like to avoid creating a cron job.

**Comment by TheRoyalTnetennba** [comment]
You should be able to refresh the token, even after expiration.

**Comment by kazuooooo** [comment]
Oh sorry, I misunderstand about it. 
Thank you so much 👍
