### ISSUE TITLE
invalid_grant error (Robot is disabled)

### ISSUE THREAD

**Issue by penakamaayo** [googleapis/google-api-ruby-client#720]
#authorization.fetch_access_token!

results to: 

```ruby
Signet::AuthorizationError: Authorization failed.  Server message:
{
  "error" : "invalid_grant",
  "error_description" : "Robot is disabled."
}
```

any idea on what's happening?

**Comment by travistruett** [comment]
Any luck here @penakamaayo ?

**Comment by penakamaayo** [comment]
@travistruett this is now resolved. It turns out that a google account which was associated to the project got deleted 😭 

Thanks!

**Comment by jorgeas80** [comment]
@penakamaayo having same problem here. How did you solve it? We lost access to all Drive docs created  with the deleted account :-(
