### ISSUE TITLE
May I have google-apis-analyticsreporting_v4 v0.6.0 released in in rubygems.org ?

### ISSUE THREAD

**Issue by s4na** [googleapis/google-api-ruby-client#7204]
I checked https://rubygems.org/gems/google-apis-analyticsreporting_v4 and there is no v0.6.0 in versions.

However, if you check [google-apis-analyticsreporting_v4/CHANGELOG.md](https://github.com/googleapis/google-api-ruby-client/blob/main/generated/google-apis-analyticsreporting_v4/CHANGELOG.md), it says it was released on 2021-10-21.

---

Best regards,
s4na

**Comment by dazuma** [comment]
Thanks for the heads-up. There was a hiccup in the release script. We got it resolved, and the library should be out now.

**Comment by s4na** [comment]
Thank you!
