### ISSUE TITLE
Author of `Google::Apis::YoutubeV3::LiveChatMessage`

### ISSUE THREAD

**Issue by AlexWayfer** [googleapis/google-api-ruby-client#723]
Hello!

I see the example for Java: https://developers.google.com/youtube/v3/live/docs/liveChatMessages/list#examples

And trying write something similar in Ruby.

Also I see the [`Google::Apis::YoutubeV3::LiveChatMessage#author_details`](https://www.rubydoc.info/gems/google-api-client/Google/Apis/YoutubeV3/LiveChatMessage#author_details-instance_method) method.

But! I'm receiving `Google::Apis::YoutubeV3::LiveChatMessage` instance with `@author_channel_id` in `@snippet` and without `author_details` (method returns `nil`).

Also value like `items(authorDetails(channelId,displayName,isChatModerator,isChatOwner,isChatSponsor),snippet),nextPageToken,pollingIntervalMillis` in `:fields` parameter for [`Google::Apis::YoutubeV3::YouTubeService#list_live_chat_messages`](https://www.rubydoc.info/gems/google-api-client/Google/Apis/YoutubeV3/YouTubeService#list_live_chat_messages-instance_method) doesn't help.

Something changed? I don't see `fields` in the [`liveChatMessages/list` documentation](https://developers.google.com/youtube/v3/live/docs/liveChatMessages/list).

How to check author of message is moderator?

Thanks.

**Comment by AlexWayfer** [comment]
Oh, I see now: `authorDetails` near `snippet` in the `part` param. Sorry. I thought I've checked all ways.

**Comment by AlexWayfer** [comment]
> JustinBeckwith assigned AlexWayfer 2 hours ago

Ehm, why?

**Comment by dazuma** [comment]
@AlexWayfer Apologies, it looks like Justin is running a script that assigns closed issues across Google's client library repositories, to the person who closed it, for internal metrics purposes. Please feel free to ignore this.

**Comment by AlexWayfer** [comment]
> @AlexWayfer Apologies, it looks like Justin is running a script that assigns closed issues across Google's client library repositories, to the person who closed it, for internal metrics purposes. Please feel free to ignore this.

OK, thank you.

(So much automation and false positives in Google API library!)
