### ISSUE TITLE
Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by storrence88** [googleapis/google-api-ruby-client#725]
Hello, trying to pull reviews using Google's My Business API. Having issues actually listing out the reviews after getting past authentication. I would appreciate any ideas or suggestions. Code is below:
```
require 'google/apis/mybusiness_v4'
require "googleauth"

credentials = 
  Google::Auth::UserRefreshCredentials.new(
    client_id: "608957854277-uqohp0gs6rp389cqofb2n3vk9njbt5mf.apps.googleusercontent.com",
    client_secret: "ykGNwE7kFz8qEiv_iBUFbuKU",
    scope: "plus.business.manage",
    additional_parameters: { "access_type" => "offline" })
    
credentials.refresh_token = '1/3EPLoMsAvmTRBfSjGxMybfrcNeXLW6MmE8PDibxvI4k'
credentials.fetch_access_token!
mybussiness = Google::Apis::MybusinessV4::MyBusinessService.new

mybussiness.authorization = credentials
```

I am calling `mybussiness.list_accounts` to try to get all reviews but the error I am getting is : `Error - #<Google::Apis::ClientError: forbidden: Request had insufficient authentication scopes.>`

**Comment by mattwhisenhunt** [comment]
@storrence88 Did this issue get resolved for you?

**Comment by storrence88** [comment]
Unfortunately, it did not.

**Comment by alexbel** [comment]
@storrence88 did you solve this issue?

**Comment by blowmage** [comment]
Great! Glad you got it figured out!
