### ISSUE TITLE
Get Error 500 invalid_grant when trying to Auth in Production Server

### ISSUE THREAD

**Issue by quando1910** [googleapis/google-api-ruby-client#731]
Hi everyone, please help me solve the problem. My code is work fine in local, it can run google auth, get access token, blabla... However, when I deploy it, I always get the 500 Error 
{ Signet::AuthorizationError (Authorization failed.  
Server message:
{
  "error": "invalid_grant",
  "error_description": "Bad Request"
})
I do not know why, trying to fix NTP too. I'm using with Docker.

**Comment by TheRoyalTnetennba** [comment]
Could you share how you are initializing authorization? On GCE instances, the googleauth gem will try to use credentials provided by the metadata server if it does not find credentials by other routes.

**Comment by mejiaro** [comment]
Did you ever find a way to fix this?

**Comment by mejiaro** [comment]
btw, in case anyone has this problem again, we ended up implementing a strategy around this: 

https://github.com/google/google-id-token

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
