### ISSUE TITLE
Missing methods for SheetsService class

### ISSUE THREAD

**Issue by corey2** [googleapis/google-api-ruby-client#733]
There are a few methods in that are supposed to exist in this class according to the documentation, but do not exist when I actually try to use them. The source code for the class, at C:\Ruby22-x64\lib\ruby\gems\2.2.0\gems\google-api-client-0.9.9\generated\google\apis\sheets_v4, doesn't show any sign of these methods. The missing methods are:
append_spreadsheet_value
batch_clear_values
batch_spreadsheet_value_clear_by_data_filter
batch_spreadsheet_get_by_data_filter
batch_spreadsheet_update_by_data_filter
clear_values
get_spreadsheet_by_data_filter
get_spreadsheet_developer_metadatum
search_developer_metadatum_developer_metadata

**Comment by TheRoyalTnetennba** [comment]
Have you tried updating the client to the latest version?
