### ISSUE TITLE
Sometimes , click allow to access google drive api is block and nothing redirect 

### ISSUE THREAD

**Issue by truonglocbinh** [googleapis/google-api-ruby-client#741]
I create web app to access google drive api , when user first login web , I require user must allow web can access google drive of them through google drive api. Everything is Ok but sometime when user click allow button to access google drive , web can not redirect to callback and keep screen allow . I check log on log file , and see ActionController::RoutingError (No route matches [POST] "/GponForm/diag_Form"):

**Comment by TheRoyalTnetennba** [comment]
Could you post your code (minus credentials, etc)? I'd like to try to reproduce the error.

**Comment by truonglocbinh** [comment]
I see my issues for my code , Sorry for you.
