### ISSUE TITLE
cannot load such file -- google/apis/pagespeedonline_v5

### ISSUE THREAD

**Issue by maxrosecollins** [googleapis/google-api-ruby-client#743]
#### Environment details

  - OS: OSX
  - Ruby version: ruby 2.5.1p57
  - Gem name and version: google-api-client-0.25.0

#### Steps to reproduce

  1. I try to require pagespeedonline_v5
  2. It can't find the file
  3. I can require pagespeedonline_v4 though

#### Code example

```ruby
rirb(main):004:0> require 'google/apis/pagespeedonline_v5'
Traceback (most recent call last):
        1: from (irb):4
LoadError (cannot load such file -- google/apis/pagespeedonline_v5)
irb(main):005:0> require 'google/apis/pagespeedonline_v4'
=> true
```

**Comment by TheRoyalTnetennba** [comment]
pagespeedonline_v5 has not been included in a release yet. The folder is ~12 days old while the latest gem was released ~28 days ago.

**Comment by dazuma** [comment]
The fact that we haven't had a release in 28 days is concerning. The gem is supposed to release weekly. I'll take a look at that.

**Comment by maxrosecollins** [comment]
Okay, thank you.
