### ISSUE TITLE
Unable to update self RSVP status

### ISSUE THREAD

**Issue by GopalChavan** [googleapis/google-api-ruby-client#744]
#### Steps to reproduce

Unable to update the my(currently logged in user)RSVP status i.e, the attendees[].responseStatus
api reference(https://developers.google.com/calendar/v3/reference/events/update)
The status get updated when i try with postman, but doesn't work when trying using this gem

#### Code example

```ruby
# example
  service = Google::Apis::CalendarV3::CalendarService.new
  service.authorization = @client
attendees_array = [
    {
      // authorized this user with google
      "email": "authenticated_user@gmail.com",
      "responseStatus": "tentative"
    },
    {
      "email": "other_user@gmail.com"
    }
]
google_event = Google::Apis::CalendarV3::Event.new({
      ....,
      'attendees': attendees_array,
      ....
    })
service.update_event(calendar_id, event_id, google_event, send_notifications: true)
```
#### debugging the source code
when i was debugging the source code, I found that, it finally calls to execute_once method in 
lib/google/apis/core/http_command.rb file
where the responseStatus property is removed from the body attribute

Thanks!

**Comment by blowmage** [comment]
Hi @GopalChavan, thanks for opening the issue. I think I know why you are seeing this behavior. It has to do with how the attribute names are cased. For JSON, the attribute names use "camelCase", but for a Ruby object and Ruby Hash, the attribute names use "snake_case". TL;DR is if you change "responseStatus" to "response_status" it will work just fine. To illustrate this, I have some code examples below.

[`Event#attendees`](https://www.rubydoc.info/gems/google-api-client/Google/Apis/CalendarV3/Event#attendees-instance_method) is an array of [`EventAttendee`](https://www.rubydoc.info/gems/google-api-client/Google/Apis/CalendarV3/EventAttendee) objects. The attribute [`#EventAttendee#response_status`](https://www.rubydoc.info/gems/google-api-client/Google/Apis/CalendarV3/EventAttendee#response_status-instance_method) exists, but `EventAttendee#responseStatus` does not. Creating a `EventAttendee` object with `responseStatus` does not set the attribute.

```ruby
attendee = Google::Apis::CalendarV3::EventAttendee.new(
  email: "authenticated_user@gmail.com",
  responseStatus: "tentative"
) #=> #<Google::Apis::CalendarV3::EventAttendee:0x00007fca500431d0 @email="authenticated_user@gmail.com">
```

As you can see, when you create a new [`Event`](https://www.rubydoc.info/gems/google-api-client/Google/Apis/CalendarV3/Event) object using Ruby Hashes and the `responseStatus` name, the resulting `EventAttendee` object does not include the value.

```ruby
attendees_array = [
  {
    email: "authenticated_user@gmail.com",
    responseStatus: "tentative"
  },
  {
    email: "other_user@gmail.com"
  }
]
google_event = Google::Apis::CalendarV3::Event.new({
  attendees: attendees_array,
})
google_event.to_json #=> "{\"attendees\":[{\"email\":\"authenticated_user@gmail.com\"},{\"email\":\"other_user@gmail.com\"}]}"
```

If you instead pass in `EventAttendee` objects it will work as expected:

```ruby
attendees_array = [
  Google::Apis::CalendarV3::EventAttendee.new(
    email: "authenticated_user@gmail.com",
    response_status: "tentative"
  ),
  Google::Apis::CalendarV3::EventAttendee.new(
    email: "other_user@gmail.com"
  )
]
google_event = Google::Apis::CalendarV3::Event.new({
  attendees: attendees_array,
})
google_event.to_json #=> "{\"attendees\":[{\"email\":\"authenticated_user@gmail.com\",\"responseStatus\":\"tentative\"},{\"email\":\"other_user@gmail.com\"}]}"
```

Or, if you make the Ruby Hash match the EventAttendee object's naming, then it will also work:

```ruby
attendees_array = [
  {
    email: "authenticated_user@gmail.com",
    response_status: "tentative"
  },
  {
    email: "other_user@gmail.com"
  }
]
google_event = Google::Apis::CalendarV3::Event.new({
  attendees: attendees_array,
})
google_event.to_json #=> "{\"attendees\":[{\"email\":\"authenticated_user@gmail.com\",\"responseStatus\":\"tentative\"},{\"email\":\"other_user@gmail.com\"}]}"
```

Lastly, if you really want to use the "snakeCase" naming convention, you can convert the Ruby Hash to a JSON String and load from the JSON String:

```ruby
attendees_array = [
  {
    email: "authenticated_user@gmail.com",
    responseStatus: "tentative"
  },
  {
    email: "other_user@gmail.com"
  }
]
google_event_json = {
  attendees: attendees_array,
}.to_json
google_event = Google::Apis::CalendarV3::Event.from_json(
  google_event_json
)
google_event.to_json #=> "{\"attendees\":[{\"email\":\"authenticated_user@gmail.com\",\"responseStatus\":\"tentative\"},{\"email\":\"other_user@gmail.com\"}]}"
```

Does this answer your question?

**Comment by GopalChavan** [comment]
Thank you very much Mike for the nice explanation.
