### ISSUE TITLE
Google Pay required file?

### ISSUE THREAD

**Issue by fmroske** [googleapis/google-api-ruby-client#747]
Hi. I'm trying to use google-api-client version 0.25.0. All the examples I find are for Google Drive, and seem straightforward.

However, I find no relevant generated file to use Google Pay (I read somewhere it's walletobjects_v1 but of course that file doesn't exist.)  Can someone point me in the right direction please?

**Comment by TheRoyalTnetennba** [comment]
It is out of date, but https://github.com/google-pay/s2ap-quickstart-ruby might be able to get you started. 

You can generate the client with `generate-api gen generated --file=wobs-discovery.json`

**Comment by fmroske** [comment]
Thanks @TheRoyalTnetennba!  I've spent days feeling super dumb trying to get this to work. 

Is this the route everyone has to take to use this gem with Google Pay?  Seems strange for a library that is fully supported by Google. Even the link to the quickstart guide in `s2ap-quickstart-ruby` repo 404s. :/

(For anyone also reading this, I copied `wobs-discovery.json` from `google-pay/s2ap-quickstart-ruby`  repo into the root of my application where I'm trying to use `google-api-client` gem. I also had to copy `api_names_out.yaml` from `google-api-client` repo into my directory for the gem, before running the above command, since it was removed from the gem assembly. Although the bug for the latter has been closed, the file was still not included when I re-installed installed the gem moments ago. :( )

**Comment by TheRoyalTnetennba** [comment]
Thank you so much for posting your solution.

Apologies for the awkward usage. This client covers apis listed in the [Google API discovery service](https://developers.google.com/discovery/), which doesn't include Google Pay. It can generate clients from other discover docs, but they aren't tested, included in the releases, etc.

I'm trying to track down what happened to the quickstart page.

**Comment by mladenilic** [comment]
The sample repo for ruby (and most of the other repos) has been removed from google-pay GH organization.

https://github.com/google-pay/s2ap-quickstart-ruby  – this now leads to 404.

Is there another way to obtain discovery document?

**Comment by mladenilic** [comment]
To reply my own question from last comment: https://walletobjects.googleapis.com/$discovery/rest?version=v1

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
