### ISSUE TITLE
Google+ gets shutdown on March 2019

### ISSUE THREAD

**Issue by chendanjie** [googleapis/google-api-ruby-client#761]
Hey, first of all: Thanks for this gem!  Google+ gets shut down at March 2019 this year. Are there plans on migrating already / alternatives at the moment? Best regards

**Comment by JustinBeckwith** [comment]
Greetings!  This will only affect API calls that are using the `plus.me` oauth2 scopes:
https://developers.google.com/+/api-shutdown

All other sign in stuff and APIs will continue to work as expected :) If you're using the Google+ api for people stuff, check out the people API!
https://developers.google.com/people/

If you want us to give your code a one-over and make sure you're safe - just let us know which specific API endpoints you're using, and which scopes you're using :) 

Hope this helps!

**Comment by tnaughts** [comment]
@JustinBeckwith should we migrate off the oauth2_v2 API?

**Comment by blowmage** [comment]
> should we migrate off the oauth2_v2 API?

No. The Oauth2 API is staying. Only the Google+ APIs are being shutdown.
