### ISSUE TITLE
Discontinuing support for JSON-RPC and Global HTTP Batch Endpoints

### ISSUE THREAD

**Issue by jchatel** [googleapis/google-api-ruby-client#769]
As mentioned in this [blog from Google](https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html):  JSON-RPC and Global HTTP Batch Endpoints support are being discontinued next month.

I'm assessing a project that uses an old version of this gem (0.8.7) but could not find any mention of this topic here.

Is this library using such protocols? (How would I know/test?) or has that been addressed in a newer version?

I'm worried that things will break.

I did find a few calls to Google::APIClient::BatchRequest.new. Should I assume that those calls are using those protocols and the easier way is just to remove those and everything will work normally?

I'd love to avoid touching this old project so it would be ideal if I could avoid the refactoring associated with migrating to the latest version (that I'm using on another project).

**Comment by jchatel** [comment]
Will removing all instances of Google::APIClient::BatchRequest.new be good enough to prevent calls to Global HTTP Batch Endpoints?

**Comment by edmundloo** [comment]
Following here for support as well. We're also using `Google::APIClient::BatchRequest.new` right now in `0.8.x`, but we're upgrading to `0.11.x` and still using the same call. I'd also like to know whether I should assume these will work as normal when the old endpoint is deprecated.

![Screenshot from 2019-03-19 08-52-38](https://user-images.githubusercontent.com/5935208/54624324-654ae600-4a2a-11e9-829f-c2e225a2ca84.png)

**Comment by jchatel** [comment]
Gotta love the reactivity. I guess we'll all see on Monday for ourselves.

**Comment by blowmage** [comment]
The problem here is that you are using very old versions of the gem. I would try upgrading to the latest version, and if that works then you should be fine.

Batch operations are not being deprecated, only the global endpoints, which were removed from the gem long ago. But again, you are using old versions. From what is written here I don’t know if you are using the global endpoints or not. As long as you are making batch calls on a specific API, such as Storage, you should be fine, AFAIK.

**Comment by jchatel** [comment]
So if no calls are made to Batch (Google::APIClient::BatchRequest.new) at all, it should be no problem even is the gem version is old?

**Comment by blowmage** [comment]
Yes. But BatchRequest can be used as long as it is not sent to the global endpoint. I don’t know when the global endpoints were removed from the gem, but I’ve been told they were.

If you have a conscern I would recommend posting some code so we can review.

**Comment by blowmage** [comment]
I don’t know this for sure, but Google knows what accounts are using the global endpoints. I would assume they would contact those accounts to tell them. Perhaps a Google employee can weigh in here?

**Comment by jchatel** [comment]
Being able to tell if a project is still calling them seems like a no-brainer really. Would have made things so much easier indeed and less time wasted on our end.

**Comment by edmundloo** [comment]
We have a fairly large project but ended up just upgrading to 0.28.x to be safe. It wasn't particularly easy since lots of things changed between 0.8.x and 0.28.x, but better safe than sorry I guess.

**Comment by jchatel** [comment]
Seems good now, but we don't know if the switch has been turned off yet?
