### ISSUE TITLE
unable to convert Google::Apis::AdminDirectoryV1::UserPhoto.photo_data to image

### ISSUE THREAD

**Issue by yogiv88** [googleapis/google-api-ruby-client#770]
#### Environment details

  - Ruby version: 2.3.1
  - Gem name and version: google-api-client - 0.19.4

I am unable to decode the data i get while fetching user photo Google::Apis::AdminDirectoryV1::UserPhoto.photo_data. How do i use this data to generate an image?

Documentation is not clear on how to use the data

**Comment by blowmage** [comment]
I believe the JSON REST services return binary data using Base64 encoding. Have you tried `Base64.decode64`?

**Comment by yogiv88** [comment]
yes...i got a string like 

`$R\x05\xF7P\x10j\xAD\x81\xDD\x16\xEB\xD4\x04*\xDA/x\v\x8C9\xBB\xA8\x960S\x14\xA8\x10\x17\x8B\x0F\xC4\xE3\x87]\x8B\xCDC\xC3F(*B\x90I\xD3\x025\t\e\x82G&0p\b(p\xE2\xBE(\xE3s\xC8\xB6\xCA\xFAX!\xEF\"\xF4\xB1]|e\xBC[\xD5} y,9R\xF1\x88/3\x8D~\xF5\xA5\xFC\x87\xCDQ*\xC5\x8AU#\xF9\x97\x8B\x8E\x1D\xD9\xE4\xB1\x1E{\xBE\n\x906M\xED\x1Aqc\xE1\xC5M\xE9\xC4\x17&\x1F_H\xD6\xFE\xF6\xE6\xED\x05\x9B\xECG\xEF\xCAhz3\xC3\xE8\xFA\b;\xB4\x1CIgP*\xED\xE6\xEA\x99\xE3\xA8`

**Comment by yogiv88** [comment]
this is the actual photo_data from the response i got

`\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xFF\xDB\x00\x84\x00\x05\x03\x04\t\b\a\x06\b\n\x06\t\b\t\t\t\v\t\t\b\t\b\b\x06\t\x06\t\t\a\t\a\t\b\t\t\t\n\x1C\r\t\b\x0E\t\t\t\x18!\x18\x1A\x1D\x1D\x1F\x1F\x1F\t\x17\"$\"\x1E$\x1C\x1E\x1F\x1E\x01\x05\x05\x05\b\a\b\x0F\t\t\x0F\x17\x15\x10\x12\x16\x12\x16\x1D\x12\x15\x15\x1F\x1A\x17\x1E\x16\x12\x1E\x15\x1A\x15\x12\x12\x17\x17\x15\x15\x1E\x15\x1E\x18\x1E\x16\x16\x15\x15\x15\x12\x1E\x17\x1E\x15\x1E\x15\x15\x12\x15\x15\x12\x1D\x12\x15\x15\x1E\xFF\xC0\x00\x11\b\x00`\x00`\x03\x01\"\x00\x02\x11\x01\x03\x11\x01\xFF\xC4\x00\x1C\x00\x00\x01\x05\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x03\x04\x05\a\b\x02\x01\x00\xFF\xC4\x009\x10\x00\x02\x01\x03\x02\x05\x02\x03\x06\x05\x02\a\x00\x00\x00\x00\x01\x02\x03\x04\x11\x12\x00!\x05\x06\x13\"1AQ\aaq\b\x14#2B\x913R\x81\xA1\xB1\xC1\xD1$%br\x82\x92\xA2\xFF\xC4\x00\x1A\x01\x00\x02\x03\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x04\x01\x03\x05\x00\x06\xFF\xC4\x00%\x11\x00\x02\x02\x01\x03\x03\x04\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x11\x03\x121A\x04!Q\x13\"q\xA1\x052\xF0\xFF\xDA\x00\f\x03\x01\x00\x02\x11\x03\x11\x00?\x00\xD3\xA4\xE9':\xE9\x8E\x92:i*(\xB194\xDEC\xA7\x0F\xA6\xD2\xA9\xD5\xA8\x064\x98\xE9\xAC\x9Aw*\x9D5\x91u6\b\xD5\xF4\x8B\xE9iWM\xDC\xE8\x1A$FM\"\xFAU\xC6\x92q\xA9\x89\fBA\xA4Xiw\xD2/\xAB\x11\x05\xA0\xDAE\xBF\xC6\xE7\xE84\xBB\xAE\x9A\xD7\x05\xE8\xCF\x9C\x9D4ddi-\x90\x8881\xE4}\x80\xBE\xA9\xB2\xEA\x06\xF9\x97\x9D\xE8\xE8\x19D\x8C\xF2w\x00\xC6>\x9D\x910Y\x1D\xF7o\xCA\xB1\xB0??K\xEA\xA7\xE6_\x8EkKQS d\x91\b\tM\n\xC9\x1E*C\xA6NQ\x9B)\x17\t\x10\xDFk\xDFb\x01\xD5g\xF1k\x98c\xA5\xE2mM[;H AI\xD3^\xE9`@K\a\x8CH\xB6\x9A\aD\x00\x13\xE0\x1F$\x13\xAA\xFA^ivi\xA5jjc8'\xEE\xA1\xA1\x81\xA2\xA5\x8Fi\x15\x922\xB7y\x01v\xF3p\x03\x1D\xBCYIe\x93}\x86\x168\xA4i^\\\xF8\xE5\x1C\xFD9&\x8A(\xFA\x92\bL*\xB3)FdfG\x8EW8\xC8\x8CW\xC6\xC4{\xE8\xEF\x929\xE2\x8B\x8C\xF5V\x19\x1A9\xA2 I\x04\x83\t,\xD7\xC1\xD3\xD2H\x9A\xC6\xC4{k\t\xD6s#\xCBOV\xD3L\x9FxiC\"\xAC!\v8\x01z\x9D\xBB,j\xBF\xE0X\x1D\xF57\xCB\x1C\xF9,1p\xD9\x8B\tf\xA6y\x03H\xF9z\xC6V\x04\xCC\e\x82\xBB\xB0\xF1\xBD\xFC[E\x1C\xB3[\x83,q{\e\xBEx\x0E\x98\xCB\x1E\x82>\xCF\x7F\x10\x17\x8C\xF0\xE5\x8AY\xD4\xD4\xC0p\xC9\xE5V\x92\xA1^I\x19.<\x92#\b/\xEBmX\xF3\xD3\xF7i\x954\xD5\x8A\xCA4\xE8\x86d\xD22\xAE\xA5e\x87\\\b\x17\xD7S\xA8\xEA!\x99\x0E\x91x\xCE\xA7\x8A\x0F\xE5\x03H\x18nu+!\xDAC\xD6:\xF2 \x0E@\xD8\x83pA\xF0\xC0\xFB\x83\xB1\a]2\xEB\xE8Te\xA5\xF5\f\xE90\xB7\xDA~\x19a\xE2\xF3\n\xA8c\x8DW\x13\x1CP\x16h\\\x1C\xAE\xD1\xA9[-\x86\xC7{\\x\xF3\xA5\xF9#\xE1U3px'\x95_\xEF\x8C\x81\xC3\x12\xEC\x17;\xB0\\\x0E\xC1Bc\xFB\xFC\xF5m\xFD\xA1>\x1E\xC7_\xCD<'\xA6\xAC\xA6H\xE3\xA8\x9A1\x9B\xA4\xA29\xDAI\x9C\xAB\xB61\xE4#\x8Dv\xDC\xF57\xF1}2\xF8\xA55u%>0\xD3(F\x89m(\x96\x16\xCD\xC0+\xB0xH\x8E[\x13\xB1\xB7\x8F7\xF1\x9F\x97'\t\x9A8p\xF2\xD7\b\xCF|o\xE1e@\xAC`jPD\xC6\xF7\x11\x846\x1F\xCA\xA0\xDBP\xFC\xCD\xC8oIO$\xE97Qc\x05\xA4S\xE5W\xD7\x13\xF2\xB7\xF6\xD5\xA7\xC1\xB8\xB5d\xB0\xD4\xC9Q\x1AK\x1C\eu\x123\x11m\xBF\xEA6p.n@\x1E<j\x00q\xC7\xAE\xFB\xCC-H\x8B\x04\x91\xC9\x18=GG\xB7D\xB1\xC5$\x88\a\xB07\xD8\xDFo\xE9\xA1\x8EY\xDF\xC1d\xB0c\xD3\xB7vL\xFD\x8E\xF9y\xAA\xB8\xCD4\xF2e\xD3\xA6C<v\x884n\xFB\xAE\xF2\x86\xEDa\x8B\xF6\x90|\x9F\x1A\xD9U)\xDD\xAA\xBB\xEC\x95\xCB\xF3Q\xF2\xDD7^\x83\xEE\x92\xB3\xBD\xEF\x0FBJ\xD46\x929\xE4\xBFq*\xAEV\xFB_\x0F\xA6\xAD\xF9!P\xAC\xEC\xD6P.\xC4\xD9B\x81\xE5\x8B\x1D\x80\x1A\xD1\x8BI\x18\xF3\xB6\xC8w\x8BQ|K\x89A\x04\xB1\xC5$\xC27\x91K\x02\xDD\xA8\x80x\xCD\x89\xB2\xDC\x83o\xA6\xA2y\xBB\x9B\xBB\x9A*[\xAAxi\xCFk\xBF\xBFLZ\xE8>~~\x9A\x04z\x8B\x99\v]\x8B\e\x92\xC7\"\xD7\xF9\x93s\xAB\x14\x80\xA2\xD3\xA7\x9A9W8\xE5I\x17\xDD\x188_\xAD\x8E\xDA\xEB\x1DTp\xCE\xF1>I#\xC6\xC3\xC3!(\xDF\xB8\xDF\xD3D<;\x9De\x8D\x7F\x15RX\xC6\xC5\x9A\xD0=\xCD\x94/Pv\x93r=7\xBE\xA6\xD1\b\xBA\xCBk\xA8\x0Fv\x9B\xA1\xBE\x96B\xAB\xBBH\xAB\xFF\x00{\x04\x1F\xBB\eiK\x1A\xA2\xBA\xF8\xCBR\xD0qN\t'P\x04ud\xD9J\xB6\xD7\xC9]\xCBY\xC0\xDA\xDB\v\\\xF9\xBE\xAA\xBF\x88\xFCr\x15\x87\xA8\xD8`\xBB\xB4\x8Fo\xCCN\xCAI\xF4\xB9\xD5\x87\xF6\x9E\x81\xA5\xE1\x1F{\x82A#\xD0\xFE!1\x9C\xF1R2|\xB6\xEE\x02;\xF8\xF7>\xDA\xCA|\xE1\xCC\xF1\xD7\xD2A\vH$\x8F\xA9\x13\xCC\xA8\xD8=\xBB\x95\x905\xF6\x05\xED\xFB\xE9)\xE3\xD5;F\x8E\x1C\xFA!Op\xC6\xAB\xE2w\v\x86\x9AJYd\xEA\x96\x8B>\xACJ\x1E9{\xCD\xA2\x8F\x11{\xD9\x93\xC9\xFD'\\\xF0/\xBA\xB2\xC5\"2\x18\xBA\x89\x99^\xE5\xE9\xE62`\xAAM\x89C\xE0{\xE8S\x8B%$kM\fqD`\x90w\x93W2\xC8\x8A\xC3!t7\x16\x16\em\xA7\x9Fg\x9E\x1A\xB3\xF1\x9A\xD5\x8F&\xA3\xA6\x94O/P\f2P\xD1\xC4\x97\e]\xE5\xC8\xFD!\x1A\x9FN\xF6\x0EY\xF4\xDD\xD3\xF86\x9F\x15\xE6\xFAH\xB2\xE9\xAC\x93\x9F\xD2\x15LI\xF2R\xCE.?\xA0:\a\xE3\\\xC3QY\x90y\x00\x8C\x1F\xE1'lw\x1E\xE3\xCB\x91\xB7\x9F\xED\xA8\xCE`\xE21\xC0\xAA\xD2l\x19\xD5\x16\xE4)b\xC7\x1C\x82\xB3\x7F\f\v\x9F;\x05\xD4\x7F\x11\xE2t\xE8\x9B\xD4\xC7ccq\"\xD9\x89\x01\xB6\n\xD7;\x11\xFB\xE9\xCFQ\x18\xF5G\xB5%q\xB9\xC6\xC3\xDF\xC2\xFF\x00\xA1\xF1\xA8.74\x82\x19$\x82\x98\xCC\xFB\x04\x85N,\xFE3\x90b\xA6\xCA\xABs\xE2\xDB[\xD7Mx\xF72G\x1F\xE0\xC4\xAAj\x99I\x8E'\x05\x93%G\x93\x19\x006\a\x04co\xF7\x1A\x8D\xA6\xA8\xAA\x92\x18\xCDmI\x90\xCB!\xE9\xF4\xE0\xE9\x06\e)i-\b\xC4\x04\rk\x8FO&\xE2\xEB\xE6\xEA\x94c\xED}\xCB\xF1t\xFA\xFB\xB1n\x11\xC4\xA7\x99\x7F\x12\x8AH\x0E7\xCD\x99qk\x93k(l\xAE\x05\xBE[\xFAjB\xA1\x04\xE9\x1CL\xA8c\f\\\x97\xF0\xB6\n\xDD\xD6\xF7*\x0F\xBF\xF6\x1A\xE5%C\x88X\\\x1CA\x19\xDD;Jv\xEC\xFE\b\xFF\x00M:\x8E\x9D\xF2\xDDlH\xBE\xCC/\xFC\xA2\xC0\xAFe\xC7\xF4\e\rd\xE6\xEBrO\xB4\x9Fo\x03\x98\xFAx\xC3\xBA4\f\x0FP\xD0\xF5:&\x13 \xBA$\x81VH\x90\xF8fI\x18\x04\x94\x8BlA\xB5\xF7\ehK\x8FWH\x8Bg\xA4[\xEE\x04\x92M\x8BJn{\x9D\xE3\x025\xB9#\xCE\xDF-\x12\xF3\x054\xC43\x98\xE2\xC7{\xE7K+\xE4G\x9B\xF7]-\xB7\xA6\xAA~i\xE2\xD2B\xCD\x11\xEDV\xBF\xE1\x89:\xB0\xB8\xDE\xCD\v\xDE\xF1\xB8\xDBm\xBDv\xF5\xD6\xECU\x89\xB7B<o\x8F%'Q\x8BI\n\x16\xE9M\x14\xA3\x1F\xCE\x0F\xF1\x15{^&\xDFqb./k\x8B\xE6\x9F\x88\xBC\x86\xEBW<\xD4L\x86\x9Ev\x12\x05\xFC\xB8?\xA2\xE6\x83\xC1\xEE\xDF\xDC\xEA\xD1\xF8\x8BS\xFF\x00+\xAD\x91\xD8\xE1\x1A+\x00|\xA0I\x91\x82\x81\xEC-\xB7\xD7@\xBC\xA1\xC5W\xADH\x04\x9DHe\x91 u\xBEC\xF1\x9CF\x8Dc\xBA8\x91\x90\xEF\xFC\xBA%\x15\xC1\r\xF9\x00\xF8o!q\x9A\xA9\xBA1\xD17R\xC4\x90\xD3E\x10X\xC5\xB2\x97&{\x18\x86C\xC6\xAFNG\xE5w\xE5\xFA\x19 \x8Dc\xAA\x96[KS#I\xD0L\x96\xF8\xA8G\xB9*\x17+\e\r\x19p\xCA\x13\x1A0[\x82T\x8D\x86G\xD1\x85\xBBI\xB1*?mG\xC7\xCBS\xC9\fyO(\x91\xDDsy-\xDA-\x8B\xAE(\xC1I$\x9Bb\x02\xEF\xE3Y]vY\xA7\xA1\xD5\x16F\n[\x11<>2\xD34\xD2,\x91t\x8B\x88\xE2\x90\xA3\xAD?\xF0\xD8t\xE3BK\\\x0F\eX\xAD\xED\xBE\x9Cp\x88\xAB0\xAF\x9Ax\xD0\x00\v\xD30\x8D\xA2\x91\x82F;\xA4i\x00\t\x9E\xFE\x80\x0F}N\xD2p\x98iQ\x90\xA9%\xAD\x93\x90\x8E\xF2\xF8\xBEo\x8D\xD8\x16'\xCF\xBE\xD6\xF1\xA2>\t\xC8\xFF\x00~\v\x1C\xD0,4aAE\"7g#\xF22\x86$(\xB5\xFC\x8B\x8D!\xEA1\x8Cx\x1F\x05;A\xCE\xB5IW\xD3\x96\x9Ax#k\x02b\r\x14j\x82\xD87QR\xEBw\xC0\x1F\"\xCB\xB5\xF4uC\xCB\xD5\x9CF(\x9A\x1F\xBCc\xBC\x91\xCD\#$\x11\xA9|\x99\x16\xF7\x02H\xD40\e\x12M\xBC\xEA\xD2\xE1\\\xABI@\xAC)\xE1\x8E2\x97+$\xC6j\x80\x96@\xA3\x18\x8C\x98\xA0\x00\x1F\x16\xF3\xF5\xB8\xC75\xF3\f\xB2\x7F\xC3G;F\xAA\xE3\xA9T0\x89\xE7\xC6\xF7T\nl\x91\x92\e\xE7\xB8\xD7Jq\x7F\xAA\x18X4\xAFs'h\x05=\x1D\"\xC5\xC4\x1A\x8Ey\x93r#\x81Y\xDC\x1F\xCBe+\x90o;\xEC\x05\xC6\xFE\xBA\x05\x93\x88S\xB4\xD2\b\xE3\x00H\xC5\xD2\x1C\xB2dR{n\xC1n\xDB_\xD7\xD3IQ\xA0\xC3\xA8\xF8\xC8\xCC,\xF2\x9E\xE0\xE4^\xDB\x9B\x9B\xDC\xFF\x00\xF5\xA7\xF1D\x06X\xE0\xA3\xD1@\n\x18\x8B\xDA\xE7\e{j\xAD\x98R\x97\x04\x9F4scD\xAC\xC9+\xC2\xC3\xC1\x8EC\x01c\xE9\x90Cg\x1F\"\b\xD0L\\e\xAB\xDAN\xAD\xBA\x8B\xBB\x90\x02\xF5W\xD1\xF1\e\t\x03\x01{{\x83\xB5\xED\xA1~3\\\xF36L\xDE\xBB\x01\xFAt\xA7\x03\xAB\x11J\xDD\xCB\x99\xA6\x95\x95I\xC4\xBE\x12S\xDE\xDF \xCE\x9F\xFBkg\x04\xDC]y\x03\xA9\x84f\xAF\xC0=\xF1\xBF\x8Bt\xB8|t\xA1\x86uR\"\x11}\xD68\xD8K'\xD5n\xA8?\xF3\xD5U\xC0\xC1Z\xEE\x1F\x8D\xC15t\xE3\xB6\xEAX\x1A\xA8\xFBv;\xDFKs\xB7\x1Dn#\xC4d\x99[\xF0\xA3,\x90\xFB2\x82sq\xBF\xEAo\xEC\x06\xA4\xBE\x18\xD0\x9A\x9E-L\xCE\xBF\x87N\xCB3\xD8\x06\xEF\x12,q.\xE7o\xC6d?H\xCE\x9F\xC6\xB83&\xF94='\x1E\x93\xABW\x19U\x8F\xA5\x91[~f\nw\xBD\xF6\xDC+h\x86~&:+ \xBF\xE5\x04[\xB41\xF4PI\xB7\x9D\x00UN\xD0\xF1f\x12/k\xB2\xDFlF2B\x97S\xF5\xEE\xD1\x87\xC3\xCE[\x92\xAE\xA1sT\x92:IX7RB\x02\xABe\xF8f0?\x12\xE0\x03\xFB\xEA?1\xD3\xC1\xE1S\xDA\xAB\xEF\xF9\x01\xF8\xFC\xB2y\x1C\x1F7\xF4\x10\xF2\x87+\xD5U\xCD\x05t\xF3\xBD4(sHQ\x96QP\x0E,\xAD!\fT\x00F\xC1lw\xDC\xEF\xAB<\xDB\x15\x02F\x16\xD8\xD8~\xDB\xDE\xFA\xE2\x96>\x9E#\x14\xB0\x16\xED\x18\x85\x03\xF2\xAA\x8F\x03o\xF1\xAF\xAB\x00\xE9Ie7\xC4\xDB\xF4\xFAz\x1FMyf\xEC\xF41J%k\xCE\x9C\xC3\xD7y)#\x8E\xD1G!\x12HN=r\x96\xBA\xEE\xB6\xB0k\xED\xF2\xD0\xA7\x15\xA7\x96HdXV5{l\xD2Y\x91\b\xB5\xAC19\x9F>\xF6\xFD\xB5\xDDk\xB7ZPf\e\xB1s\xE1\xB2*K\x1C\xB2\x16\xB0\xB8\xDB\xE5\xA7/'n\x02F$Xg\xBE^2\xCB\xC6\xDB0\xD7'\xEE\x16\x93r}\xCE\xE9.\xB1G\x9C\xA0\xB7\x82\xC2\xCB\xDCGr\xAA\xD8\r\xAD\xF5\xFAiZJ\x8E\xA0\xC9c90)v\xBA\x96d\xF3w\xBD\x81\x04\x1F_\"\xDA\x16\xE2\xB5\x93\x17\x8F\x15\x90\xE2\xEAJ\xA2\xC4\xC7\x02\vw\x80\xD7P\x18\xF9\xF3\xB7\x8D\xED\xA2\xD8\x15p\x8C\r\xC0$\x9B\x90\xD8\x82\x85\x8Bd6\vk\r\x1C\x95+g\x1F\xFF\xD9`

**Comment by blowmage** [comment]
A couple things. The [API documentation says that it is using the web-save encoding](https://developers.google.com/admin-sdk/directory/v1/reference/users/photos#photoData), so you would use `Base64.urlsafe_decode64`.

**Comment by blowmage** [comment]
Apologies, I didn't see your two recent comments. If I take the data in your most recent commit and save it to a file I am able to open the file as a JPG image.

![data](https://user-images.githubusercontent.com/730/53517253-6b811e80-3a8b-11e9-8490-705885b383f3.jpg)

**Comment by blowmage** [comment]
```ruby
data = "\xFF\xD8\xFF\xE0...\x1F\xFF\xD9"
File.binwrite "data.jpg", data
```

**Comment by yogiv88** [comment]
oh thanks a lot. is it possible to convert this bytes to File object in ruby in memory without creating a file?

**Comment by blowmage** [comment]
Depending on what you are doing, you can create a `IO` object that you can use in place for a `File` object.

```ruby
data_io = StringIO.new data
```

That said, I am not aware of a way to create a `File` object that does not refer to an entry in the filesystem.

**Comment by yogiv88** [comment]
this helps. thanks a lot.
