### ISSUE TITLE
ERROR -  LoadError - cannot load such file -- google/apis/safebrowsing_v4

### ISSUE THREAD

**Issue by yasithacp** [googleapis/google-api-ruby-client#777]
I have added `gem 'google-api-client'` and did a `bundle install` But when I require `require 'google/apis/safebrowsing_v4'` It gives me the following error.

> ERROR -  LoadError - cannot load such file -- google/apis/safebrowsing_v4

However, when I tried the usage example [here](https://github.com/googleapis/google-api-ruby-client#usage) (with `require 'google/apis/drive_v2'`) it works. Am I missing anything here?

**Comment by blowmage** [comment]
What version of the gem are you using?

**Comment by blowmage** [comment]
SafebrowsingV4 was added in version 0.13.3. So if you are using a version earlier than that it won't be there.

**Comment by yasithacp** [comment]
Thanks for the response.. yes, I just found out from the change log. Because of my other gem versions the latest that I can have is version 0.10.3.
