### ISSUE TITLE
Typo in Generated Shared Drive Docs

### ISSUE THREAD

**Issue by charleslee94** [googleapis/google-api-ruby-client#781]
Possibly a regression of this issue [here](https://github.com/googleapis/google-api-ruby-client/issues/562)

It seems that all of the [Shared Drive v3](https://github.com/googleapis/google-api-ruby-client/blob/50a63b45e3ced41bb102457d96c78d035db2f861/generated/google/apis/drive_v3/service.rb#L540) methods have a typo? For example 
```
def create_drife(...)
```

A similar issue seems to happen in the [Shared Drive v2](https://github.com/googleapis/google-api-ruby-client/blob/50a63b45e3ced41bb102457d96c78d035db2f861/generated/google/apis/drive_v2/service.rb#L885) docs as well.

```
def delete_drife(...)
```

All of the team drive methods seem to be called `drife` instead.

**Comment by charleslee94** [comment]
To anyone who is having similar issues.

the function [create_teamdrive](https://github.com/googleapis/google-api-ruby-client/blob/50a63b45e3ced41bb102457d96c78d035db2f861/generated/google/apis/drive_v3/service.rb#L1959) seems to work for now, although the docs mention that it's deprecated.

**Comment by dazuma** [comment]
Yes, this is the same issue reported in #562, due to the same issue (ActiveSupport::Inflector doesn't recognize the word "drive" as singular). I'll get this fixed.
