### ISSUE TITLE
Calendar insert_event does not send `conferenceData`

### ISSUE THREAD

**Issue by Samemura** [googleapis/google-api-ruby-client#784]
I followed below instruction to create event with hangout conference.
https://developers.google.com/calendar/create-events#conferencing

After event created, hangout conference is not set on event. (I checked Google Calendar Web UI)

Checking debug output of api client, it seems not hav conferenceData in http body. (conferenceDataVersion was showed)

How do I send conferenceData ? or could create conference ?

#### Environment details

  - OS: Mac OS 10.12.6
  - Ruby version: 2.6.2
  - Gem name and version: google-api-client (0.28.6)

#### Steps to reproduce

  1. 

#### Code example

```ruby
event = Google::Apis::CalendarV3::Event.new{
  summary: 'Google I/O 2015',
  location: '800 Howard St., San Francisco, CA 94103',
  description: 'A chance to hear more about Google\'s developer products.',
  start: {
    date_time: '2015-05-28T09:00:00-07:00',
    time_zone: 'America/Los_Angeles',
  },
  end: {
    date_time: '2015-05-28T17:00:00-07:00',
    time_zone: 'America/Los_Angeles',
  },
  conference_data: {
    create_request: {
      conference_solution_key: {
        type: 'hangoutsMeet'
      }
    }
  }
}

result = client.insert_event('primary', event, conference_data_version: 1)
```

**Comment by blowmage** [comment]
Your example didn't work for me. I got a `SyntaxError` because it is using squiggly braces (`{}`) for `Event.new`, and not parens (`()`). If I change it to use parens it seems to be okay. Is that the issue? Or was that a mistake when copying the code to the issue?

**Comment by Samemura** [comment]
@blowmage thank you for checking my issue.

Sorry but the detail of my report was incorrect. Probably `conferenceData` was sent but not actual conference created. (I've checked return of API client)

Then tried to follow exact same data with API guidance example. It succeeded with below code to create conference. (This is not exactly same as my code since it should be kept in private so may have syntax mistake)

Thank you for your kindly support and now this issue could be closed for me.
I hope this information will help someone in the future.

```
event = Google::Apis::CalendarV3::Event.new(
  summary: 'Google I/O 2015',
  location: '800 Howard St., San Francisco, CA 94103',
  description: 'A chance to hear more about Google\'s developer products.',
  start: {
    date_time: '2015-05-28T09:00:00-07:00',
    time_zone: 'America/Los_Angeles',
  },
  end: {
    date_time: '2015-05-28T17:00:00-07:00',
    time_zone: 'America/Los_Angeles',
  },
  conference_data: {
    create_request: {
       request_id: SecureRandom.uuid
    }
  }
)

result = client.insert_event('primary', event, conference_data_version: 1)
```

**Comment by blowmage** [comment]
Glad you got it figured out.
