### ISSUE TITLE
Support Models API in BigQuery v2 API

### ISSUE THREAD

**Issue by nagachika** [googleapis/google-api-ruby-client#790]
#### Environment details

  - OS: Everywhere
  - Ruby version: 2.5 and later
  - Gem name and version: google-api-client-0.29.1

#### Steps to reproduce

  1. `gem install google-api-client -v 0.29.1`

#### Code example

```ruby
require "google/apis/bigquery_v2"
Google::Apis::BigqueryV2::BigqueryService.instance_method(:list_tables) # => #<UnboundMethod: Google::Apis::BigqueryV2::BigqueryService#list_tables>
Google::Apis::BigqueryV2::BigqueryService.instance_method(:list_models) # => NameError: undefined method `list_models' for class `Google::Apis::BigqueryV2::BigqueryService'
```

I mean there's no methods for Models resource in BigQuery API v2 (https://cloud.google.com/bigquery/docs/reference/rest/v2/models).
I received email from GCP titled `[Action Required] Migrate your BigQuery ML model CRUD operations from Tables API to Models API before August 17, 2019` but I cannot migrate to Models API with latest google-api-client.gem.

In fact there were related methods in google-api-client-0.28.6 but they are vanished in 0.29.1.

I have confirmed the current metadata from Discovery API (download from https://www.googleapis.com/discovery/v1/apis/bigquery/v2/rest) contains related resources for Model APIs.
I hope new version will be released soon with the methods for BigQuery Models API (list_models, get_model etc..).

**Comment by blowmage** [comment]
@nagachika Thanks for the issue. I can confirm that the Models API was removed in the 0.29.1 release. For now, please downgrade to the 0.29.0 release.

**Comment by blowmage** [comment]
@dazuma @TheRoyalTnetennba The BigQuery Models API was [removed in the 0.29.1 release](https://github.com/googleapis/google-api-ruby-client/commit/cd3877754f88903bb56b2eae4830cec1e18d8334#diff-1e02ee6bd485be6362e50db50fe2e80aL3151). Any idea what happened?

**Comment by dazuma** [comment]
Looks like there was an issue with the bigquery team's discovery document (IDL). The team is trying to roll it back.

**Comment by nagachika** [comment]
The v0.29.2 was released and it contains methods for BigQuery Model API. Thank you.
