### ISSUE TITLE
patch_enterprise_policy not working

### ISSUE THREAD

**Issue by sheshnathiicmr** [googleapis/google-api-ruby-client#791]
#### Environment details

  - OS:  OSX 10.14.3
  - Ruby version:2.5.3p105
  - Gem name and version:
 rails 5
gem 'omniauth-google-oauth2'
gem 'google-api-client'

#### Steps to reproduce

 1. oauth for permission to manage  project i.e andoridmanagment
2. create signup url
3. create enterprise
4. create policy is not working

i am following - https://colab.research.google.com/github/google/android-management-api-samples/blob/master/notebooks/quickstart.ipynb 

#### Code example
1. Google oauth for project permission to user 

```
def google_secret
        model_class = Googleoauth.get_oauth_details(current_user.id)
        Google::APIClient::ClientSecrets.new(
          { "web" =>
            { "access_token" => model_class.google_token,
              "refresh_token" => model_class.google_refresh_token,
              "client_id" => "602514148522-ah146lahm0deqa772adedsf332ctu3hsq1pr20v.apps.googleusercontent.com",
              "client_secret" => "o7jTAG34dfake8O1Ww2iHcff5WSt0Is",
            }
          }
        )
      end

```

2. create signup url

```
def singup_url 
        # Create the API client.
        client = Google::Apis::AndroidmanagementV1::AndroidManagementService.new
        client.authorization = google_secret.to_authorization
        client.authorization.refresh! 
        signup_url = client.create_signup_url(:callback_url => "https://localhost:3000/signup_callback?userid=#{current_user.id}", :project_id =>  "dummy_project_id") { |status_code|
             puts "did stuffand got #{status_code}"
        }
       oauth_info = Googleoauth.get_oauth_details(current_user.id)
        oauth_info.signup_url_name = signup_url.name
        oauth_info.signup_url = signup_url.url
        oauth_info.save
        render plain: signup_url.url

      end
```

3. create enterprise
```
def create_enterprise 
        model_class = Googleoauth.get_oauth_details(current_user.id)

        client = Google::Apis::AndroidmanagementV1::AndroidManagementService.new
        client.authorization = google_secret.to_authorization
        client.authorization.refresh! 
        client.create_enterprise(:enterprise_token => model_class.enterprise_token, :project_id =>  "dummy_project_id", :signup_url_name => model_class.signup_url_name) { |response|
          puts "enterprise created response #{response.name}"
          oauth_info.enterprise_name = response.name
          oauth_info.save
          head :ok
        }
      end
```

4. create policy(this step is not working)
```
def create_policy
        model_class = Googleoauth.get_oauth_details(current_user.id)
        client = Google::Apis::AndroidmanagementV1::AndroidManagementService.new
        client.authorization = google_secret.to_authorization
        client.authorization.refresh! 
        policy_name =  "#{oauth_info.enterprise_name}/policies/policy1"
        client.patch_enterprise_policy(:name => policy_name) { |status_code|
          puts "did stuffand got #{status_code}"
        }
      end
```

Note - as per console log, url format to create policy seems invalid as there is (,) after name
but this api call is gRPC Transcoding, so i am not sure, do i need to make any changes to support this format.
reference for gRPC - https://developers.google.com/android/management/reference/rest/v1/enterprises.policies/patch

request console logs -
Sending HTTP patch https://androidmanagement.googleapis.com/v1/name,enterprises/LC01x9k0i9/policies/policy1?
404
#<HTTP::Message:0x00007fa2668c1aa8 @http_header=#<HTTP::Message::Headers:0x00007fa2668c1a80 @http_version="1.1", @body_size=0, @chunked=false, @request_method="PATCH", @request_uri=#<Addressable::URI:0x3fd133461880 URI:https://androidmanagement.googleapis.com/v1/name,enterprises/LC01x9k0i9/policies/policy1?>, @request_query=nil, @request_absolute_uri=nil, @status_code=404, @reason_phrase="Not Found", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Date", "Wed, 22 May 2019 15:09:43 GMT"], ["Content-Type", "text/html; charset=UTF-8"], ["Server", "ESF"], ["Content-Length", "1609"], ["X-XSS-Protection", "0"], ["X-Frame-Options", "SAMEORIGIN"], ["X-Content-Type-Options", "nosniff"], ["Alt-Svc", "quic=\":443\"; ma=2592000; v=\"46,44,43,39\""]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name CN=*.googleapis.com,O=Google LLC,L=Mountain View,ST=California,C=US>, issuer=#<OpenSSL::X509::Name CN=Google Internet Authority G3,O=Google Trust Services,C=US>, serial=#<OpenSSL::BN:0x00007fa2668ab820>, not_before=2019-04-30 09:22:31 UTC, not_after=2019-07-23 09:03:00 UTC>, @http_body=#<HTTP::Message::Body:0x00007fa2668c19e0 @body="<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/v1/name,enterprises/LC01x9k0i9/policies/policy1?</code> was not found on this server.  <ins>That’s all we know.</ins>\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
Caught error Invalid request
Error - #<Google::Apis::ClientError: Invalid request status_code: 404 header: #<HTTP::Message::Headers:0x00007fa266882a38 @http_version="1.1", @body_size=0, @chunked=false, @request_method="PATCH", @request_uri=#<Addressable::URI:0x3fd133461880 URI:https://androidmanagement.googleapis.com/v1/name,enterprises/LC01x9k0i9/policies/policy1?>, @request_query=nil, @request_absolute_uri=nil, @status_code=404, @reason_phrase="Not Found", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Date", "Wed, 22 May 2019 15:09:43 GMT"], ["Content-Type", "text/html; charset=UTF-8"], ["Server", "ESF"], ["Content-Length", "1609"], ["X-XSS-Protection", "0"], ["X-Frame-Options", "SAMEORIGIN"], ["X-Content-Type-Options", "nosniff"], ["Alt-Svc", "quic=\":443\"; ma=2592000; v=\"46,44,43,39\""]], @dumped=false> body: "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/v1/name,enterprises/LC01x9k0i9/policies/policy1?</code> was not found on this server.  <ins>That’s all we know.</ins>\n">

did stuffand got

**Comment by blowmage** [comment]
Where is `Googleoauth.get_oauth_details` defined and what type of object does it return?

**Comment by sheshnathiicmr** [comment]
`Googleoauth.get_oauth_details` is just a activerecord(model class) where i store _google_auth_token_ and `google_refresh_token` and some other details too

**Comment by blowmage** [comment]
What is the return value of the method? Is it a `Googleoauth` object? If so, then what is the return value of the `Googleoauth#enterprise_name` method? It looks like you are creating the `policy_name` variable using it, and I would look at those values to see if they are correct.

**Comment by sheshnathiicmr** [comment]
yes return is object _Googleoauth_ , return value of ` Googleoauth#enterprise_name => enterprises/LC01x9k0i9`

collectively it's `enterprises/LC01x9k0i9/policies/policy1 `

Note using same name i am able execute api - https://developers.google.com/android/management/reference/rest/v1/enterprises.policies/patch?apix_params=%7B%22name%22%3A%22enterprises%2FLC01x9k0i9%2Fpolicies%2Fp100%22%2C%22resource%22%3A%7B%7D%7D

and it's work fine on  above given link section Try this API provided by google.

**Comment by sheshnathiicmr** [comment]
I am not sure but highly suspect due to link is not forming well, as you can see there is comma(,) within a url after name, i don't know wither it's possible to have such pattern or not.

link copied from console logs

Sending HTTP patch https://androidmanagement.googleapis.com/v1/name,enterprises/LC01x9k0i9/policies/policy1?

**Comment by blowmage** [comment]
If you look at the [documentation for AndroidManagementService#patch_enterprise_policy](https://www.rubydoc.info/gems/google-api-client/Google%2FApis%2FAndroidmanagementV1%2FAndroidManagementService:patch_enterprise_policy), you will see that the `name` argument expects a string. You are passing a hash (`client.patch_enterprise_policy(:name => policy_name, ...)`) which is probably why it is injecting `name,` into the URL. I think updating your code to pass only the string (`client.patch_enterprise_policy(policy_name, ...)`) should fix this.

**Comment by sheshnathiicmr** [comment]
Thanks @blowmage you are right, it worked, i own you a beer 💃
