### ISSUE TITLE
Looking for documentation on the calendar_v3 API scopes type for services

### ISSUE THREAD

**Issue by uryelah** [googleapis/google-api-ruby-client#8019]
Is there documentation on which [calendar_v3 services](https://github.com/googleapis/google-api-ruby-client/blob/main/google-api-client/generated/google/apis/calendar_v3/service.rb) utilize sensitive and private scopes? 

In our application we use some of the calendar services in order to create and read calendar events.

Though the app passed the Google Console verification proccess for the app OAuth Consent screen, the unverified app page still shows to our users.
That leads me to believe we are unknownly calling sensitive scopes through the calendar services.

What is a good way or place to find the scope type called by each calendar service?

These are the services we are currently calling:
- list_events
- insert_event
- update_event
- delete_event
- get_calendar_list
- list_calendar_lists

**Comment by shivgautam** [comment]
Hi,
Calendar reference API can be found here: https://developers.google.com/calendar/api/v3/reference

I'm closing this issue.
