### ISSUE TITLE
Please elucideate "will not add any new features." in Readme.md

### ISSUE THREAD

**Issue by ghost** [googleapis/google-api-ruby-client#806]
I am confused and concerned about the wording in the openeing paragraph of the Readme which states, "we will not add any new features."

What precisely is meant by new features? Will new APIs that google may release not be supported by this library? Or is it simply that new usage patterns within the gem will not be added?

Basically, I want to know if we can expect this gem to be usable into the forseeable future or if we will have to find alternatives if new APIs/products are released by Google. If you could make the wording in the Readme slightly clearer that would be lovely.

Depending on the case something like: "all current and future apis will receive continued support, but we will not entertain feature requests for the library/gem."

or: "This gem is in maintenance mode and new APIs will not be supported."

Thank you for your consideration! Have a wondrous day!

**Comment by dazuma** [comment]
Hi @jgandt-hcs. Sorry, I agree that's not clear in the Readme.

This gem is in maintenance mode in that we're not actively doing significant manual improvements on it. But it's kind of a cool gem in that it is self-maintaining and self-developing. There's an automated process that checks the Google Discovery Service (Google's catalogue of APIs) and adds/updates clients as new APIs are released and updated, and then pushes out new releases of the gem (usually weekly). We are continuing to run and maintain that automated process. That means current and future APIs (including new APIs not yet released) will be supported, and we are fixing any blocking bugs as needed.

So yes, you can depend on this gem being usable for covered Google APIs for the foreseeable future. (Note this *doesn't* include *all* Google APIs, but only the ones covered by the [Discovery Service](https://developers.google.com/discovery/). This includes *most* APIs, but there are exceptions, including some older Ads-related APIs, some APIs originating from acquisitions, and a few others.) However, we are generally not entertaining feature requests beyond what the client code generation currently does.

We'll try to clarify this in the Readme. Thanks for the feedback!

**Comment by jgandt-hcs** [comment]
I didn't read the gem closely enough. Honestly my bad for not doing so.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
