### ISSUE TITLE
Error in ruby on rails Please help 

### ISSUE THREAD

**Issue by Siwarr** [googleapis/google-api-ruby-client#807]
/home/bondka/.rvm/gems/ruby-2.6.3/gems/actionview-6.0.0.rc1/lib/action_view/cache_expiry.rb:30:in `clear_cache_if_necessary': undefined method `execute_if_updated' for nil:NilClass (NoMethodError)
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/actionview-6.0.0.rc1/lib/action_view/cache_expiry.rb:11:in `before'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:429:in `block in make_lambda'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:201:in `block (2 levels) in halting'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:607:in `block (2 levels) in default_terminator'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:606:in `catch'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:606:in `block in default_terminator'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:202:in `block in halting'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:514:in `block in invoke_before'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:514:in `each'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:514:in `invoke_before'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/callbacks.rb:134:in `run_callbacks'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/execution_wrapper.rb:111:in `run!'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/execution_wrapper.rb:73:in `block in run!'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/execution_wrapper.rb:70:in `tap'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/execution_wrapper.rb:70:in `run!'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/execution_wrapper.rb:86:in `wrap'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/activesupport-6.0.0.rc1/lib/active_support/reloader.rb:51:in `reload!'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/application.rb:168:in `serve'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/application.rb:145:in `block in run'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/application.rb:139:in `loop'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/application.rb:139:in `run'
	from /home/bondka/.rvm/gems/ruby-2.6.3/gems/spring-2.1.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/bondka/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/bondka/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'

What is the solution for this error???? I get it whatever i execute whatever any command!

I run : rails generate model post title:string body:text

i'm using ubuntu
ruby 2.6.3
rails 6.0.0 rc1

**Comment by dazuma** [comment]
Can you please explain how this is related to the `google-api-client` gem? I don't see the connection.
