### ISSUE TITLE
::Google::Apis::FcmV1::FirebaseCloudMessagingService getting Google::Apis::AuthorizationError when using valid key

### ISSUE THREAD

**Issue by Ignatii** [googleapis/google-api-ruby-client#815]
**Environment details**:
- OS: Macos High Sierra 10.13.6
- Ruby version 2.6.2
- Gem name and version: gem 'google-api-client', 0.30.7

**Steps to reproduce**:
1. Trying to send push message trough ::Google::Apis::FcmV1::FirebaseCloudMessagingService

**Code example**:

```
service = ::Google::Apis::FcmV1::FirebaseCloudMessagingService.new .  
service.authorization = access_key_of_your_project_server_in_firebase .  
message = ::Google::Apis::FcmV1::SendMessageRequest.new({notification: {title: 'foo', body: 'bar'}, token: 'user_device_fcm_token'}) .  
result = service.send_message("projects/#{my_project_id}", message)
```

In the result i am receiving following:

```
Caught error Unauthorized
Error - #<Google::Apis::AuthorizationError: Unauthorized status_code: 401 header: #<HTTP::Message::Headers:0x00007fd9917ee2e0 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x3fecc8be63e8 URI:https://fcm.googleapis.com/v1/projects/my-project-id/messages:send?key=some-key>, @request_query=nil, @request_absolute_uri=nil, @status_code=401, @reason_phrase="Unauthorized", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Vary", "Origin"], ["Vary", "X-Origin"], ["Vary", "Referer"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["Date", "Tue, 23 Jul 2019 12:22:48 GMT"], ["Server", "ESF"], ["Cache-Control", "private"], ["X-XSS-Protection", "0"], ["X-Frame-Options", "SAMEORIGIN"], ["X-Content-Type-Options", "nosniff"], ["Alt-Svc", "quic=\":443\"; ma=2592000; v=\"46,43,39\""], ["Transfer-Encoding", "chunked"]], @dumped=false> body: "{\n  \"error\": {\n    \"code\": 401,\n    \"message\": \"Request is missing required authentication credential. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.\",\n    \"errors\": [\n      {\n        \"message\": \"Login Required.\",\n        \"domain\": \"global\",\n        \"reason\": \"required\",\n        \"location\": \"Authorization\",\n        \"locationType\": \"header\"\n      }\n    ],\n    \"status\": \"UNAUTHENTICATED\"\n  }\n}\n">
```

When i am checking credentials through other gems everything is fine, so the problem not in them, but why i receiving Unauthorized error?

Glad to get some help!

**Comment by blowmage** [comment]
What type of object is `access_key_of_your_project_server_in_firebase`?

**Comment by blowmage** [comment]
FYI: [Authorization using API keys](https://www.rubydoc.info/gems/google-api-client/0.30.7/#Authorization_using_API_keys)

**Comment by Ignatii** [comment]
@blowmage 
> What type of object is `access_key_of_your_project_server_in_firebase`?

Its a string containing api key.

If you mean pass it to service.key then i getting this:

`
401
#<HTTP::Message:0x00007ff21af09678 @http_header=#<HTTP::Message::Headers:0x00007ff21af09628 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x3ff90d760610 URI:https://fcm.googleapis.com/v1/projects/project-id/messages:send?key=some-key>, @request_query=nil, @request_absolute_uri=nil, @status_code=401, @reason_phrase="Unauthorized", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["WWW-Authenticate", "Bearer realm=\"https://accounts.google.com/\", error=\"invalid_token\""], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Vary", "Referer"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["Date", "Mon, 05 Aug 2019 09:23:12 GMT"], ["Server", "ESF"], ["Cache-Control", "private"], ["X-XSS-Protection", "0"], ["X-Frame-Options", "SAMEORIGIN"], ["X-Content-Type-Options", "nosniff"], ["Alt-Svc", "quic=\":443\"; ma=2592000; v=\"46,43,39\""], ["Transfer-Encoding", "chunked"]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name CN=edgecert.googleapis.com,O=Google LLC,L=Mountain View,ST=California,C=US>, issuer=#<OpenSSL::X509::Name CN=Google Internet Authority G3,O=Google Trust Services,C=US>, serial=#<OpenSSL::BN:0x00007ff21af306d8>, not_before=2019-07-29 18:38:19 UTC, not_after=2019-10-21 18:23:00 UTC>, @http_body=#<HTTP::Message::Body:0x00007ff21af09560 @body="{\n  \"error\": {\n    \"code\": 401,\n    \"message\": \"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.\",\n    \"errors\": [\n      {\n        \"message\": \"Invalid Credentials\",\n        \"domain\": \"global\",\n        \"reason\": \"authError\",\n        \"location\": \"Authorization\",\n        \"locationType\": \"header\"\n      }\n    ],\n    \"status\": \"UNAUTHENTICATED\"\n  }\n}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
Caught error Unauthorized
Error - #<Google::Apis::AuthorizationError: Unauthorized status_code: 401 header: #<HTTP::Message::Headers:0x00007ff21af39530 @http_version="1.1", @body_size=0, @chunked=false, @request_method="POST", @request_uri=#<Addressable::URI:0x3ff90d760610 URI:https://fcm.googleapis.com/v1/projects/project-id/messages:send?key=some-key>, @request_query=nil, @request_absolute_uri=nil, @status_code=401, @reason_phrase="Unauthorized", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["WWW-Authenticate", "Bearer realm=\"https://accounts.google.com/\", error=\"invalid_token\""], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Vary", "Referer"], ["Content-Type", "application/json; charset=UTF-8"], ["Content-Encoding", "gzip"], ["Date", "Mon, 05 Aug 2019 09:23:12 GMT"], ["Server", "ESF"], ["Cache-Control", "private"], ["X-XSS-Protection", "0"], ["X-Frame-Options", "SAMEORIGIN"], ["X-Content-Type-Options", "nosniff"], ["Alt-Svc", "quic=\":443\"; ma=2592000; v=\"46,43,39\""], ["Transfer-Encoding", "chunked"]], @dumped=false> body: "{\n  \"error\": {\n    \"code\": 401,\n    \"message\": \"Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.\",\n    \"errors\": [\n      {\n        \"message\": \"Invalid Credentials\",\n        \"domain\": \"global\",\n        \"reason\": \"authError\",\n        \"location\": \"Authorization\",\n        \"locationType\": \"header\"\n      }\n    ],\n    \"status\": \"UNAUTHENTICATED\"\n  }\n}\n">

Retrying after authentication failure
Google::Apis::AuthorizationError: Unauthorized
`

**Comment by blowmage** [comment]
Okay, that makes more sense. It looks to me that this API endpoint requires an OAuth access token, not an API key. The error response states:

> Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential.

Most Google APIs don't support API keys, only a few do. You should create an authorization object using [googleauth](https://www.rubydoc.info/gems/google-api-client/0.30.7/#Passing_authorization_to_requests). Here is an example from that library's README:

```ruby
scope = 'https://www.googleapis.com/auth/androidpublisher'

authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: File.open('/path/to/service_account_json_key.json'),
  scope: scope)

authorizer.fetch_access_token!
```

Here is a blog post I found that might be helpful: https://medium.com/@ThatJenPerson/authenticating-firebase-cloud-messaging-http-v1-api-requests-e9af3e0827b8

**Comment by Ignatii** [comment]
@blowmage thanks, i will take a look and will write feedback!

**Comment by blowmage** [comment]
@Ignatii Did you figure this out? Can this issue be closed?

**Comment by Ignatii** [comment]
Yep, it worked after getting oauth token, thanks!

**Comment by blowmage** [comment]
Glad to hear it!
