### ISSUE TITLE
Is it possible to watch changes to people resources?

### ISSUE THREAD

**Issue by geekontheway** [googleapis/google-api-ruby-client#818]
Is it possible to watch changes to people resources?

Just like GmailService `watch_user`, CalendarService  `watch_event`

Thank you all.

**Comment by blowmage** [comment]
What API are you asking about?

**Comment by geekontheway** [comment]
@blowmage Hi blowmage, i was asking about a push notification, when people/contact infomation, changed in G-suite, my server/app can receivie a webhook notification, so i can fetch the updated infomation

**Comment by blowmage** [comment]
I don't see watch listed as an RPC available on the [G-Suite People API](https://developers.google.com/people/api/rest/).
