### ISSUE TITLE
Veneers backed by google-api-client may duplicate "gl-ruby" in the x-goog-api-client header

### ISSUE THREAD

**Issue by dazuma** [googleapis/google-api-ruby-client#821]
Affected libraries are google-cloud-bigquery, google-cloud-dns, google-cloud-resource_manager, and google-cloud-storage.

This would happen because the veneer sets both gl-ruby/ and gccl/, and then google-api-client appends both gl-ruby/ and gdcl/, resulting in gl-ruby/ appearing twice. We probably should respond by examining any existing x-goog-api-client, and not adding gl-ruby/ if it is already present.

**Comment by quartzmo** [comment]
google-cloud-storage [sets the `gl-ruby` header here](https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-storage/lib/google/cloud/storage/service.rb#L56). Should `gl-ruby/#{RUBY_VERSION} ` be removed from this line?

**Comment by dazuma** [comment]
@quartzmo I think it's better for google-api-client to check if it was added upstream, and not add it a second time. Otherwise, google-cloud-storage would have to check what version of google-api-client it is calling, and decide whether or not to add gl-ruby, and that seems more fragile.

**Comment by quartzmo** [comment]
OK great, now I understand the issue. Thanks @dazuma.
