### ISSUE TITLE
Google::Apis::AdminDirectoryV1::DirectoryService, 503, Service unavailable. Please try again

### ISSUE THREAD

**Issue by radubogdan** [googleapis/google-api-ruby-client#824]
I struggle to fetch list of users using `Google::Apis::AdminDirectoryV1::DirectoryService` . After some failed attempts I setup domain-wide delegation for my service account and got to the point where API responds with: 

```
@body="{\n \"error\": {\n  \"errors\": [\n   {\n    \"domain\": \"global\",\n    \"reason\": \"backendError\",\n    \"message\": \"Service unavailable. Please try again\"\n   }\n  ],\n  \"code\": 503,\n  \"message\": \"Service unavailable. Please try again\"\n }\n}\n"
```

1. Does this means the setup is correct?
2. How can I proceed further?

Full code:

```ruby
require 'google/apis/admin_directory_v1'
service = Google::Apis::AdminDirectoryV1::DirectoryService.new
cred_file = 'credentials.json'
scopes = [Google::Apis::AdminDirectoryV1::AUTH_ADMIN_DIRECTORY_USER]
service.authorization = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: File.open(cred_file),
  scope: scopes
)
service.list_users(customer: 'my_customer')

```

Same if I try it from postman using the Bearer jwt token. 

```
{
    "error": {
        "errors": [
            {
                "domain": "global",
                "reason": "backendError",
                "message": "Service unavailable. Please try again"
            }
        ],
        "code": 503,
        "message": "Service unavailable. Please try again"
    }
}
```

**Comment by dazuma** [comment]
This seems to be a backend issue, especially if you're encountering it via postman. Support options and team contact info for the admin api can be found at https://developers.google.com/admin-sdk/directory/support (in particular, look at the issue tracker links).

**Comment by radubogdan** [comment]
Hi @dazuma, thank you for reaching my issue. 

It looks like before you make the request, you first need to "impersonate" a user with access on GSuite. After long digging in the gem since it's explicit how to do this, I found a [similar example for gmail](https://github.com/googleapis/google-api-ruby-client/blob/711dfb83b33c03535076917726956584d5c8bf9a/samples/cli/lib/samples/gmail.rb#L140). 

In case someone else needs this:

```ruby
require 'google/apis/admin_directory_v1'
service = Google::Apis::AdminDirectoryV1::DirectoryService.new
cred_file = 'credentials.json'
scopes = [Google::Apis::AdminDirectoryV1::AUTH_ADMIN_DIRECTORY_USER]
authorizer = Google::Auth::ServiceAccountCredentials.make_creds(
  json_key_io: File.open(cred_file),
  scope: scopes
)
authorizer.sub = EMAIL_OF_IMPERSONATED_USER # needs at least 1 login & terms accespted on GSuite.
service.authorization = authorizer
service.list_users(customer: 'my_customer')
```

Regards,
Radu
