### ISSUE TITLE
Firebase Remote Config Missing

### ISSUE THREAD

**Issue by jonasmora** [googleapis/google-api-ruby-client#825]
Why is firebaseremoteconfig_v1 missing from the generated apis?

**Comment by dazuma** [comment]
This library covers APIs that have an associated Discovery doc in the Google Discovery service. Firebase Remote Config for some reason has not added its Discovery doc to the Discovery service list, and I don't know why. A discovery doc does exist, and we could conceivably add it manually, but I'd like to check with the Firebase team to make sure they aren't intentionally keeping the API out of the client libraries for now.

**Comment by dazuma** [comment]
The Firebase team has asked us to hold off on client library support for now while they finalize some parts of the backend. When they're ready for widespread use, they'll add the service to Discovery, which will cause this client library to generate support for it.

In the meantime, if you want to evaluate remote config from Ruby, you can always make direct HTTP requests. See https://firebase.google.com/docs/reference/remote-config/rest for more information.

**Comment by josh-m-sharpe** [comment]
Looks like there's a discovery document now: https://firebase.google.com/docs/reference/remote-config/rest

But still no API? https://github.com/googleapis/google-api-ruby-client/tree/master/generated/google/apis

**Comment by dazuma** [comment]
@josh-m-sharpe Yes, as I mentioned before, the discovery document does exist, but the Firebase team has not added it to the main discovery index. Until they take that step, it doesn't get generated into this client.

**Comment by KevinDoom** [comment]
Hello @dazuma. Do you know if there's been any movement on this?
