### ISSUE TITLE
Docs aren't working on rubydoc.info

### ISSUE THREAD

**Issue by justinoue** [googleapis/google-api-ruby-client#839]
I apologize if this isn't the right place for it but trying to use https://www.rubydoc.info/github/google/google-api-ruby-client is super slow and causing 503s.

**Comment by TheRoyalTnetennba** [comment]
Thanks for bringing this up. The latest docs are uploaded https://googleapis.dev/ruby/google-api-client/latest/index.html.

**Comment by blowmage** [comment]
Should we update the RubyDoc badge on the README to point to this new site?

**Comment by TheRoyalTnetennba** [comment]
Readme link has been updated. For versions after 0.33.2 the rubygems.org documentation link will point to the googleapis.dev page
