### ISSUE TITLE
The documentation for google analytics reporting v4 lacks of practical examples

### ISSUE THREAD

**Issue by silva96** [googleapis/google-api-ruby-client#853]
The documentation for google analytics reporting v4 lacks of practical examples, it only documents the classes and methods, so it's very hard to guess how should we use the gem in real life. For example, I'm trying to obtain all purchases from enhanced ecommerce to see where they came from (Acquisition Channel or Channel Grouping), but im only interested on transactions that took 5 sessions to convert the transaction ( our unconvinced clients).

After a lot of digging, I could achieve what I needed, I wrote a stackoverflow question+answer

https://stackoverflow.com/questions/58976821/how-to-query-google-analytics-api-using-the-google-api-ruby-gem/

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
