### ISSUE TITLE
Google::Apis::ClientError: ipRefererBlocked: The request did not specify any referer. Please ensure that the client is sending referer or use the API Console to remove the referer restrictions

### ISSUE THREAD

**Issue by Sohair63** [googleapis/google-api-ruby-client#858]
#### Environment details

  - OS: Ubuntu (AWS)
  - Ruby version: google-api-client
  - Gem name and version: google-api-client (0.28.7)

#### Steps to reproduce

the code return error is: `calendar_service.list_events(calendar_id, params)`

#### Code example

```ruby
  def self.list_events_by_key(calendar_id:, key:, time_min:, time_max:)
    calendar_service = Google::Apis::CalendarV3::CalendarService.new
    calendar_service.key = key
    params = {
      time_min: time_min,
      time_max: time_max
    }
    calendar_service.list_events(calendar_id, params)
  end
```

**Comment by blowmage** [comment]
Did you use the API console to remove the referer restrictions for this API?

**Comment by Sohair63** [comment]
No I did not.

**Comment by blowmage** [comment]
It seems like you need to remove the restriction in order to use that API with the ruby client.

Or, you can set the referer header on [`RequestOptions#header`](https://googleapis.dev/ruby/google-api-client/latest/Google/Apis/RequestOptions.html#header-instance_method) for the request.

**Comment by simonahad** [comment]
I see this: `This key is unrestricted. Restrictions help prevent unauthorized use and quota theft` 


I will try your suggestion.

**Comment by Sohair63** [comment]
I see this: `This key is unrestricted. Restrictions help prevent unauthorized use and quota theft` 


I will try your suggestion.

**Comment by dazuma** [comment]
@Sohair63 Were you able to resolve this?

**Comment by ali-m-anwar** [comment]
@dazuma  yes I did resolve this by adding a referrer from developer console against my keys.

the second option was to select `None` in referrer restrictions. @blowmage answer gave me the hint. Thanks.

**Comment by Sohair63** [comment]
@dazuma  yes I did resolve this by adding a referrer from developer console against my keys.

the second option was to select `None` in referrer restrictions. @blowmage answer gave me the hint. Thanks.

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
