### ISSUE TITLE
unsupported_grant_type

### ISSUE THREAD

**Issue by TheMasterPrawn** [googleapis/google-api-ruby-client#862]
I am using a valid key file I got from the G Suite admin console. I am trying to read people. I keep getting this error 

```json
{
  "error": "unsupported_grant_type",
  "error_description": "Invalid grant_type: "
}
```

This is very frustrating as there are a number of ways of authenticating, and this looks correct, but I dont know if its a mistake I made or is it the library. Some posts tend to talk about forms encoding, but that cant be the issue as I cannot see anywhere to set that 
```ruby

require "google/apis/people_v1"
require "googleauth"
require "googleauth/stores/file_token_store"
require "fileutils"
require 'google/api_client/client_secrets'

CLIENT_SECRETS = Google::APIClient::ClientSecrets.load("client_secrets.json")

authorization = CLIENT_SECRETS.to_authorization

client = Google::Apis::PeopleV1::PeopleServiceService.new
# You can then use this with an API client, e.g.:
scopes = ['https://www.googleapis.com/auth/admin.directory.user.readonly']

authorization.scope = scopes
client.authorization = authorization

response = client.get_people
```

**Comment by gautamsawhney** [comment]
I have been facing the same issue  when I try to refresh the auth_token

     def create_service_auth
       @service = Google::Apis::CalendarV3::CalendarService.new
       @service.authorization = token.google_secret.to_authorization
       return unless token.expired?
      
       new_access_token = @service.authorization.refresh!
     end

**Comment by domi91c** [comment]
Getting this error as well, but only on Heroku. Did either of you find a solution?

**Comment by nathanbertram** [comment]
Seeing the same thing here on Heroku

**Comment by domi91c** [comment]
The issue I had was that the refresh token was not being saved to my users when they logged in, and so I was unknowingly passing nil refresh tokens to `Google::APIClient::ClientSecrets.new`. Not sure if that's relevant to your case.

**Comment by nathanbertram** [comment]
@domi91c ah, okay thanks for the tip!

**Comment by nathanbertram** [comment]
@domi91c refresh_token going in nil it was thanks. For anyone using the [omniauth-google-oauth2](https://github.com/zquestz/omniauth-google-oauth2) gem - you need `prompt: 'select_account consent'` set in the configuration to receive a refresh_token back.

**Comment by Younnah** [comment]
Hi!
I have the same error only with a few people who have nothing in common...

@nathanbertram I use omniauth-google-oauth2 gem in 0.5.2 btw, I will see if I can add this

**Comment by fhinkel** [comment]
Greetings, we're closing this. Looks like the issue got resolved. Please let us know if the issue needs to be reopened.
