### ISSUE TITLE
20% of requests to google docs api return 401 unauthorized

### ISSUE THREAD

**Issue by ChrisCPO** [googleapis/google-api-ruby-client#863]
#### Environment details

  - OS: Ubuntu server 18
  - Ruby version: 2.6.5p114
  - Gem name and version: google-api-client-0.36.4

#### Steps to reproduce

  1. We have a background job that syncs a little over a thousand google drive articles to our server. The job syncs all articles everyday. When this happens approx. 20 percent of the requests fail with a 401 response. It is not specific to any files somedays a file will get a 200 others it will get a 401, generally files towards the end fail.

This has been a pain to debug as it will only happen on our production server and only when syncing all article. The same articles with the same keys will pass even on production when synced individually.

I have tried so far:
  - checking googles rate limits.(user and app) both are within limits. 
  - delaying time between requests.
  - retry with delay. (currently 2 seconds)

Were using ruby and the google-api-client gem. Also V2 of their api.

I'm filing this here as a bug because it has continued to smell like a rate limit issue but without direct symptoms. Is there a possibility that a request is failing and then because of that request failing it trips up X number of requests? Does this gem have a custom rate limiting factor built in independent of the API? If it is not a rate limit error then I'm receiving an incorrect 401. 

At this point I'm currently out of options, and looking for ideas or wondering if someone else has had a similar issue.

#### Code example
N/A 

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

I have also asked this here https://stackoverflow.com/questions/60397808/20-of-requests-to-google-docs-api-return-401-unauthorized

**Comment by dazuma** [comment]
This gem does not do any custom rate limiting, so any 401 responses you see are actual server responses. Some questions:

* How close to the rate limit are you actually running? (Are you 50% of it? 80% of it? closer?)
* How are you authenticating? (Are you using ambient credentials on compute engine or app engine? Are you using a service account JSON file? Something else?)
* How long does it take for the first 401s to start happening? (One possibility is that an auth token is expiring, and the retries for subsequent requests are pushing you over the rate limit edge.)

**Comment by ChrisCPO** [comment]
Hi, thanks for responding

> How close to the rate limit are you actually running? (Are you 50% of it? 80% of it? closer?)

From what I can tell where not even close. Less then 10%

> How are you authenticating?

google auth gem version 0.9
Were authenticating same as example: https://github.com/googleapis/google-auth-library-ruby#example-usage

> How long does it take for the first 401s to start happening?

So I went back and view logs. Seems it takes just over an our for the job to run. apx 1 hour 10 min 90% of the requests fail after the 1st hour.

**Comment by strukturedkaos** [comment]
@ChrisCPO did you ever figure out a solution to this issue? We are seeing intermittent 401 errors with the Google Calendar API. There doesn't seem to be a cause from our end, and we are not hitting rate limits.

**Comment by ChrisCPO** [comment]
hi @strukturedkaos, it was us using the same session/token for over an hour which was the time till expired amount. 

Here is my commit message from our fix: |
```
[#1282] Reauthorize google auth when expired

Token expires after one hour; Not every request fails after that one hour
but every request that does fail happens after that hour. Weird
```
