### ISSUE TITLE
JSON::ParserError when Gmail response is empty

### ISSUE THREAD

**Issue by vahe** [googleapis/google-api-ruby-client#864]
#### Environment details

  - OS: Ubuntu 16.04
  - Ruby version: 2.6.2
  - Gem name and version: google-api-client (0.37.1)

#### Steps to reproduce

There seems to be a breaking change on Gmail backend where if there are no results for the request from the server, it will respond with 204 No Content (empty body). `google-api-ruby-client` attempts to parse this response and raises a `MultiJson::ParseError (JSON::ParserError)` instead of returning an empty list of results.

#### Code example

```ruby
service = Google::Apis::GmailV1::GmailService.new
service.authorization = # set credentials...
service.list_user_setting_filters(google_user_id)
```

The response is from Gmail is 204 No content. The last line raises `MultiJson::ParseError (JSON::ParserError)`

This only happens when there are no results to be returned and only for some users, ie. only happens to a small % of users with no filters.

For the affected user the response code is 204 with empty body:
```
@http_body=#<HTTP::Message::Body:0x00007f99d313f500 @body="", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
```

For unaffected users, the response code is 200 with a valid JSON body: 
```
@http_body=#<HTTP::Message::Body:0x00007f99cd60e780 @body="{}\n", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
```

In addition, the issue is not limited to `list_user_setting_filters` call. Other calls are also affected, eg. `list_user_messages`.

**Comment by mtomov** [comment]
I can confirm I'm experiencing the same issue. Thanks @vahe for reporting the problem so clearly!

**Comment by dazuma** [comment]
@vahe Could you provide a full stack trace for the error? The client code should not be attempting to parse JSON if the content-type is not set, so I suspect something more subtle is going on.

**Comment by bolom** [comment]
I have got the same issues also AndroidpublisherV3

**Comment by mtomov** [comment]
The error is pretty easy to reproduce. Just query any empty resource, like email drafts (`list_user_drafts`):

```
Sending HTTP get https://www.googleapis.com/gmail/v1/users/me/drafts?fields=drafts%28id%29%2CnextPageToken&q=older_than%3A1d
204
#<HTTP::Message:0x000055eebb8e1d18 @http_header=#<HTTP::Message::Headers:0x000055eebb8e1ca0 @http_version="1.1", @body_size=0, @chunked=false, @request_method="GET", @request_uri=#<Addressable::URI:0x2af75dbf0368 URI:https://www.googleapis.com/gmail/v1/users/me/drafts?fields=drafts%28id%29%2CnextPageToken&q=older_than%3A1d>, @request_query=nil, @request_absolute_uri=nil, @status_code=204, @reason_phrase="No Content", @body_type=nil, @body_charset=nil, @body_date=nil, @body_encoding=#<Encoding:UTF-8>, @is_request=false, @header_item=[["Content-Type", "application/json; charset=UTF-8"], ["Vary", "Origin"], ["Vary", "X-Origin"], ["Vary", "Referer"], ["Date", "Thu, 12 Mar 2020 12:18:38 GMT"], ["Server", "ESF"], ["Content-Length", "0"], ["X-XSS-Protection", "0"], ["X-Frame-Options", "SAMEORIGIN"], ["X-Content-Type-Options", "nosniff"], ["Alt-Svc", "quic=\":443\"; ma=2592000; v=\"46,43\",h3-Q050=\":443\"; ma=2592000,h3-Q049=\":443\"; ma=2592000,h3-Q048=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000"]], @dumped=false>, @peer_cert=#<OpenSSL::X509::Certificate: subject=#<OpenSSL::X509::Name CN=*.storage.googleapis.com,O=Google LLC,L=Mountain View,ST=California,C=US>, issuer=#<OpenSSL::X509::Name CN=GTS CA 1O1,O=Google Trust Services,C=US>, serial=#<OpenSSL::BN:0x000055eebb904f98>, not_before=2020-02-25 20:41:16 UTC, not_after=2020-05-19 20:41:16 UTC>, @http_body=#<HTTP::Message::Body:0x000055eebb8e1ac0 @body="", @size=0, @positions=nil, @chunk_size=nil>, @previous=nil>
Caught error JSON::ParserError
Error - #<MultiJson::ParseError: JSON::ParserError>
```

**Comment by mtomov** [comment]
Thanks @dazuma !
