### ISSUE TITLE
Ruby 2.8.0 removes rexml gem then Gemfile or gemspec needs to add rexml gem explicitly

### ISSUE THREAD

**Issue by yahonda** [googleapis/google-api-ruby-client#871]
Ruby 2.8.0 removes `rexml` gem then Gemfile or gemspec needs to add `rexml` gem explicitly.    

#### Environment details

  - OS: macOS 10.15.5 Beta (19F53f)
  - Ruby version: ruby 2.8.0dev (2020-04-01T10:29:39Z master fad0a1451b) [x86_64-darwin19]
  - Gem name and version: google-api-client master branch

#### Steps to reproduce

1. rbenv install 2.8.0-dev ; rbenv global 2.8.0 (or whatever install Ruby 2.8.0-dev)
2. git clone https://github.com/googleapis/google-api-ruby-client.git
3. cd google-api-ruby-client
4. bundle install
5. bundle exec rake

#### Expected behavior
It should pass.

#### Actual result
It gets this error. Entire output is https://gist.github.com/yahonda/f4eb287756e9656b0580def1c3d8291f

```
LoadError:
  cannot load such file -- rexml/parsers/streamparser
# ./spec/spec_helper.rb:42:in `require'
# ./spec/spec_helper.rb:42:in `<top (required)>'
# ./spec/google/api_client/auth/installed_app_spec.rb:1:in `require'
# ./spec/google/api_client/auth/installed_app_spec.rb:1:in `<top (required)>'
```

#### Code example
I have confirmed this change addresses this error.

```ruby
% git diff master                                                                                                                                                                                         ruby280
diff --git a/google-api-client.gemspec b/google-api-client.gemspec
index 699e5f25..62cb80f5 100644
--- a/google-api-client.gemspec
+++ b/google-api-client.gemspec
@@ -30,6 +30,7 @@ Gem::Specification.new do |spec|
   spec.add_runtime_dependency 'signet', '~> 0.12'
   spec.add_runtime_dependency 'googleauth', '~> 0.9'
   spec.add_runtime_dependency 'httpclient', '>= 2.8.1', '< 3.0'
+  spec.add_runtime_dependency 'rexml'
   spec.add_development_dependency 'thor', '~> 0.19'
   spec.add_development_dependency 'activesupport', '>= 4.2', '< 5.1'
 end
```

### Additional information
- Remove rexml and rss
https://github.com/ruby/ruby/pull/2832

- Feature #16485
https://bugs.ruby-lang.org/issues/16485
> Cons: The users need to add rexml to their Gemfile after Ruby 2.8(3.0)

**Comment by dazuma** [comment]
Will adding the `rexml` gem to dependencies cause issues for earlier versions of Ruby? (i.e. does the gem work back to Ruby 2.4.x or will it conflict with the standard library copy of rexml?)

**Comment by yahonda** [comment]
I think it is safe to adding `rexml` gem to dependencies because `rexml` CI has been running against Ruby 2.4 and higher. 

https://github.com/ruby/rexml/blob/be62163ba12a6657679a34e472b1d29d75e0e881/.travis.yml#L6-L13

**Comment by yahonda** [comment]
I have opened ruby/rexml#28 and confirmed my assumption is correct.

https://github.com/ruby/rexml/issues/28#issuecomment-617500556

**Comment by yahonda** [comment]
Opened #899
