### ISSUE TITLE
Admin Directory v1 service does not construct the correct url for channel stop for admin sdk

### ISSUE THREAD

**Issue by harshaljain27** [googleapis/google-api-ruby-client#874]
the url thats being generated is - 'https://www.googleapis.com/admin/directory/v1//admin/directory_v1/channels/stop'
instead of this - 'https://www.googleapis.com/admin/directory_v1/channels/stop'

potential fix - Need to change the post url [here ](https://github.com/googleapis/google-api-ruby-client/blob/5746a799bf4851578706ad88d7ffa1dec56363a3/generated/google/apis/admin_directory_v1/service.rb#L183)

**Comment by dazuma** [comment]
This is happening across multiple languages (i.e. the same incorrect URL is being generated by multiple independent code generators). It's possible there's an issue in the discovery doc.

**Comment by aseroff** [comment]
This was silently broken in my app for a month now, do we have any idea how long it will take for the discovery doc to be corrected? Can anyone share a workaround where they modify the endpoint before execution?

My path, by the way, is discovered_api.channels.list generating `https://www.googleapis.com/discovery/v1/apis/youtube/v3/youtube/v3/channels` (https://developers.google.com/youtube/v3/docs/channels/list)

**Comment by aseroff** [comment]
I managed to come up with a workaround, hope this can help someone else:
    
    @client = Google::APIClient.new(
      application_name: 'name',
      application_version: 'version',
      user_agent: ''
    )
    @youtube = @client.discovered_api(API_NAME, API_VERSION)
    # ...
    override = @youtube.channels.list
    override.instance_variable_set(:@uri_template, Addressable::Template.new('https://www.googleapis.com/youtube/v3/channels/'))
    channel_results = @client.execute!(
      api_method: override,
      parameters: {
        mine: true,
        part: 'contentDetails'
      }
    )
