### ISSUE TITLE
Support for ScriptService.ScriptApp

### ISSUE THREAD

**Issue by snowe2010** [googleapis/google-api-ruby-client#876]
**Is your feature request related to a problem? Please describe.**

The ScriptV1 API does not have methods to create new triggers on a project. The root problem is that Installable Triggers are not copied to new sheets when using the copy API. 

 **Describe the solution you'd like**
When using the SheetsV4 API to copy a spreadsheet, I would like to have the Installable Triggers be copied to the new sheet. 

Use Case: 

We use a tool to copy successive sheets for releases. When the sheet first opens up we run a few functions that cannot be done from the API like hiding columns and recalculating formulas. 

This scripts _needs_ to run the first time the sheet opens. I'm trying to set up a splash screen using HtmlService, which requires special permissions. I've set up the script to use an Installable Trigger that runs On Load. This works for the sheet that I create the trigger for, but when copying that sheet using the API, the Trigger is not copied. 

The [docs](https://developers.google.com/apps-script/guides/triggers/installable#managing_triggers_programmatically) state that you can create a Trigger using the ScriptService like so:

```
function createSpreadsheetOpenTrigger() {
  var ss = SpreadsheetApp.getActive();
  ScriptApp.newTrigger('myFunction')
      .forSpreadsheet(ss)
      .onOpen()
      .create();
}
```

Of course this doesn't work, because I want the trigger installed _before_ the sheet is loaded, not after, so using the API is necessary. But the [ScriptV1](https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/ScriptV1) api does not provide an API to do so. 

 **Describe alternatives you've considered**

I've tried:

* Using a Simple Trigger (`onLoad`). This doesn't work due to the scope needed (`https://www.googleapis.com/auth/script.container.ui`)
* setting up an Installable Trigger on the sheet to be copied. The Installable Trigger does not copy
* creating a Simple Trigger (`onLoad`) and then using the above code to try to create the Installable Trigger on first load and hope that the IT ran
* One thing I did not do, but considered and don't see how it would work. Create an IT that is not tied to a sheet, then applying it to each sheet after they are copied. I do not see an API call to apply an Installable Trigger to a Sheet/Project.

 **Additional context**

I don't actually care what mechanism I use to accomplish the above. The things I need to do seem to be caused by either missing sections of the API or issues with recalculating formulas based on ranges using the API. Workflow:

Using API:
* copy sheet
* copy a range (column) from the old sheet to a new column on the new sheet
* clear two ranges (column) on the new sheet

Using Script:
* hide columns based on data
* force recalculation of third range (column) that depends on data in the above two ranges. This is necessary because the sheet does not recalculate on load even though the two ranges it depends on have been modified.

**Comment by dazuma** [comment]
Thanks much for the feedback! This repo covers the Ruby client library for the API, but we are not the Sheets or Apps Script team, and we don't have the ability to affect the API functionality itself. Please instead file this issue here: https://b.corp.google.com/issues/new?component=191608&template=823917 which will go directly to the team actually responsible for the Sheets product and API. (In general, if you need to report issues with the API functionality itself, as opposed to the operation of the client library, you can usually find the issue tracker for the product team in the "Send Feedback" button near the upper right of the product's page on developers.google.com.)

**Comment by snowe2010** [comment]
@dazuma So this is not missing functionality from the library, but missing functionality from the API itself? I thought I had seen a method on the API that allowed doing this. 

I'm unable to access that link, I believe that is for Google Employees. I will file feedback using the Send Feedback button. Do you have any advice on getting this noticed, or do I just need to wait and hope it gets prioritized one day?
