### ISSUE TITLE
RubyDoc autogenerated GitHub links are broken

### ISSUE THREAD

**Issue by cguess** [googleapis/google-api-ruby-client#878]
When viewing the documentation for this library on GitHub all the "View on GitHub" links are broken and go to a 404 GitHub page.

Steps to reproduce:
1. Go to https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/SheetsV4/SheetsService#initialize-instance_method
1. Click "View on GitHub" on any method
1. A new tab will open with a url such as `https://github.com/googleapis/google-api-ruby-client/blob/Google/generated/google/apis/sheets_v4/service.rb#L518`
1. This will be a 404 error page

#### Environment details
Not applicable

**Comment by justinoue** [comment]
https://github.com/googleapis/google-api-ruby-client/issues/839

**Comment by danoscarmike** [comment]
@cguess per the linked issue (thanks @justinoue) Ruby docs have been migrated to googleapis.dev domain. As it happens it seems that the new docs no longer link out to GitHub directly but they reference the file and line number in the source snippet. So it's not that the link is fixed - it no longer exists :|

Can you point to how you navigated to rubydocs.info? Were you following a link from any cloud.google.com or Google maintained GitHub pages?

**Comment by danoscarmike** [comment]
@dazuma @TheRoyalTnetennba FYI

**Comment by cguess** [comment]
@danoscarmike that would make sense why that'd break then.

I got to the page by the following the Ruby link under "Client Library Reference" at the bottom of the left panel here: https://developers.google.com/sheets/api/reference/rest

**Comment by danoscarmike** [comment]
Thank you! Investigating this a bit more it might just be the GSuite APIs that are impacted. I'll work on a fix.

**Comment by justinoue** [comment]
FWIW I found this issue today after searching using Google for "AdminDirectoryV1" and ending back up here: https://www.rubydoc.info/github/google/google-api-ruby-client/Google/Apis/AdminDirectoryV1

I thought it was supposed to be deprecated so I came to the issues section to reread my old issue and then saw this one in open. I think it would be worthwhile to make sure the rubydoc.info pages do work.

**Comment by bajajneha27** [comment]
Hi @justinoue , could you please let me know how you got the link?

**Comment by justinoue** [comment]
> Hi @justinoue , could you please let me know how you got the link?

As I said, I had found it through Google search with the term "AdminDirectoryV1". It looks like now 2 years later there's no longer search results from rubydoc.info though.

**Comment by bajajneha27** [comment]
Yeah. Thank you for confirming the same and apologies for the delayed response. I'll go ahead and close the issue. Please feel free to reopen in case there's any other query. Thank you all again for reaching out to us.
