### ISSUE TITLE
CalendarV3::CalendarService#get_event not showing Group Attendee Data

### ISSUE THREAD

**Issue by dkaplan88** [googleapis/google-api-ruby-client#881]
When I create a google calendar event, I specify in `attendees` a group email address. This successfully sends out to all my group members. My group members respond to the invitation. 

However, when I query the event I am unable to see the group members or their responses to my event. 

#### Environment details

  - OS: Latest Mac
  - Ruby version: 2.6.3
  - Gem name and version: google-api-client (0.25.0) 

#### Steps to reproduce

  1.  Create Google Event. Add Group email address as attendee. 
  2. Sends out to all group members 
  3. Group Members respond to google calendar invite 
  4. get_event#attendees doesn't show those group members or their responses

Please let me know if more data is needed or if this is actually a feature request

**Comment by dazuma** [comment]
This is probably a feature request to the calendar back end, and not something we can do in the client library. Can you direct this to the Calendar API team: https://developers.google.com/calendar/support?hl=en
