### ISSUE TITLE
The requested URL '/discovery/v1/apis/sheets/v4/v4/spreadsheets' was not found on this server.

### ISSUE THREAD

**Issue by babarajay** [googleapis/google-api-ruby-client#884]
I've used 'google-api-client' gem to integrate spreadsheets with my rails app.

What I've done so far is this:

```ruby
client = Google::APIClient.new
service = client.discovered_api('sheets','v4')
```
but when I try to execute the API with:

```ruby
client.execute(api_method: service.spreadsheets.create, parameters: {}, body: JSON.dump({}), headers: {'Content-Type' => 'application/json'})
```
it gives me an error 'The requested URL '/discovery/v1/apis/sheets/v4/v4/spreadsheets' was not found on this server.'

I tried to figure it out and found that; the method below which is used to generate request object gives me the wrong URL

```ruby
service.spreadsheets.create.generate_request

OUTPUT:
[:post, #<Addressable::URI:0x3f91d00481ec URI:https://www.googleapis.com/discovery/v1/apis/sheets/v4/v4/spreadsheets>, {}, ""] 
```
Two times '/v4/v4/' in the URL.

**Comment by dazuma** [comment]
That looks like an extremely old version of `google-api-client`. The `Google::APIClient` generic class hasn't been part of the interface for years.

Please update to a more recent version of the library. (The latest version is 0.40.0). Then use the provided sheets client class:
```ruby
client = Google::Apis::SheetsV4::SheetsService.new
client.create_spreadsheet(...
```
