### ISSUE TITLE
`DateTime` fields changed to `String`

### ISSUE THREAD

**Issue by AlexWayfer** [googleapis/google-api-ruby-client#889]
Hello. I've updated the gem from version `0.37.2` to `0.41.1` and my code, working with YouTube API (Data 3) failed. 

Error looks like:

```
undefined method `strftime' for "2020-07-06T11:03:07.207000Z":String (NoMethodError)
```

I've checked the [CHANGELOG](https://github.com/googleapis/google-api-ruby-client/blob/master/CHANGELOG.md) and didn't find anything related to YouTube in "Breaking" sections.

So, I've found the problem field, it's `published_at` in `LiveChat` messages: https://github.com/googleapis/google-api-ruby-client/blame/c2e0bb3a5de57fdf7c4148b195ddf4a87a4ec5fe/generated/google/apis/youtube_v3/classes.rb#L7339

And I've found out that the `@return` is actually `String` and it was changed in 2020-05-21 from Ruby native `DateTime`: https://github.com/googleapis/google-api-ruby-client/commit/5905a32742bd13aa0b59db05fa3bbf4fde0d1611#diff-43c97e2cd94bffaf36403d1dcf933b13R614 (there are many `published_at` fields in many classes and all of them were changed).

Why? Is this an error? Or if you were intent to do so — this is a breaking change. Any type change is a breaking change.

**Comment by dazuma** [comment]
Hi Alex, you caught me in my day job.

This client library is automatically generated. I can confirm that the input IDL document changed and dropped the "date-time" format annotation for these fields, resulting in the breaking type change here. It seems to have happened for several services around the same time, and I'm not sure why. I'll inquire internally (tracking number: b/160689252) and update this issue if I learn anything.

Unfortunately, as the management of this library is 100% automated, we don't currently have the ability to control or flag breaking changes that might originate upstream in the IDLs published by the service teams. Breaking changes could happen in any release, even a patch release.

**Comment by AlexWayfer** [comment]
> Hi Alex, you caught me in my day job.
> 
> This client library is automatically generated. I can confirm that the input IDL document changed and dropped the "date-time" format annotation for these fields, resulting in the breaking type change here. It seems to have happened for several services around the same time, and I'm not sure why. I'll inquire internally (tracking number: b/160689252) and update this issue if I learn anything.

OK, thank you, I'm waiting.

> Unfortunately, as the management of this library is 100% automated, we don't currently have the ability to control or flag breaking changes that might originate upstream in the IDLs published by the service teams. Breaking changes could happen in any release, even a patch release.

I understand, especially for `0.x.x` versions, but get me right, please: I have tests for my project, which stubs YouTube responses by classes from this library, so I'm doing something like:

```ruby
expect(client).to receive(:list_videos).and_return(
  SpecificYouTubeClass.new(
    # ...,
    published_at: DateTime.new(2020, 2, 3, 4, 5, 6)
  )
)
```

So I'm unable to check such changes and getting crashes in production — that's sad.

And even if this client library is automatically generated — people writes staff from which it generates and code which generate a result, so…

**Comment by AlexWayfer** [comment]
Any news? And it doesn't seem like "question" for me.

**Comment by AlexWayfer** [comment]
It seems changed back to `DateTime` in `google-apis-youtube_v3` gem without any notes, change logs, something else…
