### ISSUE TITLE
Enable master branch protection

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-api-ruby-client#892]
This repository does not seem to have master branch
          protection enabled, at least in the way I'm expecting.
          I was hoping for:

          - master branch protection
          - requiring at least one code reviewer
          - requiring at least two status checks
          - enforcing rules for admins

          Please turn it on!

**Comment by hkdevandla** [comment]
@dazuma , friendly ping to take a look and fix it.

**Comment by SurferJeffAtGoogle** [comment]
Daniel, is there a reason not to enable master branch protection today?

**Comment by dazuma** [comment]
Branch protection cannot be enabled on this repo until the code generation process has been migrated to autosynth or kokoro.
