### ISSUE TITLE
Enable branch protection by 2020-09-18.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/google-api-ruby-client#909]
This repo does not have any branch protection rules.

Please visit Settings > Branches > and create a rule to prevent forced updates to the master branch.

**Comment by dazuma** [comment]
Branch protection cannot be enabled on this repo until the code generation process has been migrated to autosynth.

**Comment by dazuma** [comment]
We've migrated generation and release to autosynth and autorelease, so dartman no longer needs to push directly to master. Branch protection is now enabled.
