### ISSUE TITLE
Retrieving userinfo without Oauth2V2

### ISSUE THREAD

**Issue by ttzv** [googleapis/google-api-ruby-client#911]
Possibly a very noob question but until now I was using Oauth2Service to retrieve profile information about authorized user (picture, email, name etc.)
Since Oauth2V2 was recently removed what else can I use to retrieve this data?

**Comment by rwegrzyniak** [comment]
same issue here

**Comment by vitalinfo** [comment]
@dazuma any thoughts?
I don't know, how google updates the docs, but according to your comment https://github.com/googleapis/google-api-ruby-client/issues/904#issuecomment-689244126 this API has been removed, but as far as I can see Oauth2V2 moved to Oauth2V3, based on google docs

**Comment by ttzv** [comment]
Considering uncertainty of this issue and what happened to Oauth2V2 I decided to use standard API call to userinfo endpoint available in [Discovery document](https://developers.google.com/identity/protocols/oauth2/openid-connect#discovery) under 'userinfo_endpoint'
Implementation in Ruby is very simple following guidelines from [here](https://developers.google.com/identity/protocols/oauth2/openid-connect#obtaininguserprofileinformation) and Net::HTTP [documentation](https://ruby-doc.org/stdlib-2.7.0/libdoc/net/http/rdoc/Net/HTTP.html#class-Net::HTTP-label-GET+with+Dynamic+Parameters)
My code: 

`uri = URI('https://openidconnect.googleapis.com/v1/userinfo')`
`params = {access_token: '<your access_token goes here>'}`
`uri.query = URI.encode_www_form(params)`
`res = Net::HTTP.get_response(uri)`
`res.body #contains user information`

Response is a JSON so to retrieve email, for example, I did the following:

`user_info = JSON.parse(res.body, symbolize_names: true)`
`user_info[:email] #returns email address of authorized user`

Hope it can help someone.

**Comment by ojab** [comment]
```
Google::Apis::Oauth2V2::AUTH_USERINFO_EMAIL == Google::Apis::PeopleV1::AUTH_USERINFO_EMAIL
=> true
```

**Comment by dazuma** [comment]
I believe OAuth2 V2 was re-added to the directory, so this should no longer bean issue.
