### ISSUE TITLE
webrick should not be mandatory

### ISSUE THREAD

**Issue by pterjan** [googleapis/google-api-ruby-client#9560]
This is minor but webrick is only used in installed_app.rb which only uses it if the optional launchy is available, so it should not be a mandatory dependency of the gem.

**Comment by drewblas** [comment]
Given there an 8.8 CVE for older versions of webrick (like that specified here) - https://github.com/advisories/GHSA-369m-2gv6-mw28 would be a great reason to please remove webrick from required gems.  Thank you!

**Comment by edwardmp** [comment]
@drewblas small note: it's for all versions of Webrick, but if you are vulnernable depends on your Ruby version you use it with. Any version before Ruby v2.2.8 is vulnerable.
